### ISSUE TITLE
Linux: NoClassDefFoundError org/python/core/PyException

### ISSUE THREAD

**Issue by Vanuan** [OpenRefine/OpenRefine#1006]
Running openrefine-2.6-rc1 on Ubuntu 14.04 results in this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/python/core/PyException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
	at java.lang.Class.privateGetPublicMethods(Class.java:2651)
	at java.lang.Class.getMethods(Class.java:1467)
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:380)
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:335)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:450)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:76)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:838)
	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:84)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:78)
	at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:164)
	at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:114)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:1617)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1437)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1423)
...
```

Web browser shows "Butterfly is still initializing..." message.

What am I missing?

**Comment by tfmorris** [comment]
Off the top of my head, I'd say the class org.python.core.PyException.

What were you attempting to do when you got the error?

**Comment by jackyq2015** [comment]
Seems the jython library can not be loaded.
Check if you have the file in place under:
OpenRefine\extensions\jython\module\MOD-INF\lib\jython-standalone-2.5.3.jar

**Comment by Vanuan** [comment]
> What were you attempting to do when you got the error?

Just start it from the console.

> Check if you have the file in place under:
> OpenRefine\extensions\jython\module\MOD-INF\lib\jython-standalone-2.5.3.jar

Is it the same path for Linux?

**Comment by Vanuan** [comment]
Found under ./webapp/extensions/jython/module/MOD-INF/lib/jython-standalone-2.5.3.jar

**Comment by Vanuan** [comment]
Additional trace:
```
Caused by: java.lang.ClassNotFoundException: org.python.core.PyException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

**Comment by tfmorris** [comment]
What version of Java are you running?  Are you using the `refine` shell script to start things?

I just verified that the kit is OK and works fine for me (running the Linux kit on OS X, but that should be pretty close).  The only other things that come to mind off the top of my head are: 1) the classpath isn't getting set correctly because you're not using the shell script or 2) you've got an older version of Java which is incompatible with the distribute class files (although in that case, I'd expect to see a nested exception complaining about the incompatibility.

**Comment by Vanuan** [comment]
Which version of Java should I use?
```
$ java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```

>  Are you using the refine shell script to start things?

Yes.

**Comment by Vanuan** [comment]
This is the command executed:
```
/usr/bin/java -cp server/classes:server/lib/* -Xms256M -Xmx1400M
-Drefine.memory=1400M -Drefine.max_form_content_size=1048576
-Drefine.verbosity=info -Dpython.path=main/webapp/WEB-INF/lib/jython
-Dpython.cachedir=/home/john/.local/share/google/refine/cachedir
-Drefine.webapp=main/webapp
-Drefine.port=3333 -Drefine.host=127.0.0.1 com.google.refine.Refine
```

**Comment by Vanuan** [comment]
Seems like prepackaged jython-standalone-2.5.3.jar indeed lacks the class above.
After downloading jython-standalone-2.5.3.jar from official repo I have this error:
```
01:13:24.071 [         butterfly.module] Error initializing module freebase by script function init() (1058ms)
org.mozilla.javascript.EcmaError: ReferenceError: "ClientSideResourceManager" is not defined. (file:/home/john/Downloads/openrefine-2.6-rc1/webapp/extensions/freebase/module/MOD-INF/controller.js#88)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3654)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3632)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3717)
	at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1692)
	at org.mozilla.javascript.gen.c4._c1(file:/home/john/Downloads/openrefine-2.6-rc1/webapp/extensions/freebase/module/MOD-INF/controller.js:88)
	at org.mozilla.javascript.gen.c4.call(file:/home/john/Downloads/openrefine-2.6-rc1/webapp/extensions/freebase/module/MOD-INF/controller.js)
```

**Comment by jackyq2015** [comment]
If you build the source yourself, try this:
```
cd OpenRefine/extensions
ant
```
then run it again.

**Comment by tfmorris** [comment]
I'm running out of ideas.  I installed Ubuntu 15.04 on Virtualbox, along with the default-jre (OpenJDK 1.7.0_79) and the OpenRefine 2.6-rc1 kit works fine.  I also verified that the jython jar contains the PyException class.

Perhaps your kit was corrupted somehow during download.  Could you try downloading and unpacking a fresh copy?

**Comment by Vanuan** [comment]
Strange. Downloading fresh copy helped. Can't reproduce this anymore.
