### ISSUE TITLE
How to solve "Can't find project: missing ID parameter" when I download the file from project?

### ISSUE THREAD

**Issue by VitoLiao** [OpenRefine/OpenRefine#1165]
Here is the detail error message:
`javax.servlet.ServletException: Can't find project: missing ID parameter
	at com.google.refine.commands.Command.getProject(Command.java:173)
	at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:77)
	at com.google.refine.RefineServlet.service(RefineServlet.java:177)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:155)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by tfmorris** [comment]
There is so much missing here.

What version of Refine?
What operating system and what version of it?
What were you doing when you got the error? (step by step)
Is the error reproducible (ie it happened more than once)?

**Comment by davbre** [comment]
I have experienced the same issue. It occurs when I try to export to CSV. Oddly, if I export a second time I get the same error message yet the csv file is successfully exported (i.e. downloaded automatically).

My setup:
openrefine-2.6-rc.2
Ubuntu 16.04.1 LTS

I can't reproduce the error at will. It occurs after I have worked on a dataset for a while. I'll update here if/when I have more info.

**Comment by thadguidry** [comment]
@VitoLiao Did you solve this somehow Vito ?

**Comment by VitoLiao** [comment]
@thadguidry yah, I did, but I really forgot the way cause time has passed too long  : )

**Comment by thadguidry** [comment]
@VitoLiao No problem. OK thanks anyway.
