### ISSUE TITLE
Error 500 Failed to initialize module rdf-exporter-extension

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#118]
_Original author: thadguidry (August 24, 2010 15:57:04)_

<b>What steps will reproduce the problem?</b>
1. Checkout source
2. Follow GetDevelopmentVersion
3. Run gridworks

<b>What is the expected output? What do you see instead?</b>

HTTP ERROR 500

Problem accessing /. Reason:

```
Butterfly Error
```

Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-exporter-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
    at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:458)
    at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:431)
    at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:297)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
    at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
    at com.google.gridworks.GridworksServer.configure(Gridworks.java:243)
    at com.google.gridworks.GridworksServer.init(Gridworks.java:166)
    at com.google.gridworks.Gridworks.init(Gridworks.java:83)
    at com.google.gridworks.Gridworks.main(Gridworks.java:77)
Caused by: org.mozilla.javascript.EvaluatorException: Java class &quot;com.google.gridworks.operations.OperationRegistry&quot; has no public instance field or method named &quot;registerOperation&quot;. (file:/C:/Users/tguidry/Downloads/Freebase/gridworks/main/webapp/../../extensions/rdf-exporter/module/MOD-INF/controller.js#18)
    at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:109)
    at org.mozilla.javascript.Context.reportRuntimeError(Context.java:938)
    at org.mozilla.javascript.Context.reportRuntimeError(Context.java:994)
    at org.mozilla.javascript.Context.reportRuntimeError2(Context.java:964)
    at org.mozilla.javascript.JavaMembers.reportMemberNotFound(JavaMembers.java:870)
    at org.mozilla.javascript.NativeJavaClass.get(NativeJavaClass.java:135)
    at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:1617)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2227)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2214)
    at org.mozilla.javascript.gen.c8._c1(file:/C:/Users/tguidry/Downloads/Freebase/gridworks/main/webapp/../../extensions/rdf-exporter/module/MOD-INF/controller.js:18)
    at org.mozilla.javascript.gen.c8.call(file:/C:/Users/tguidry/Downloads/Freebase/gridworks/main/webapp/../../extensions/rdf-exporter/module/MOD-INF/controller.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.gen.c8.call(file:/C:/Users/tguidry/Downloads/Freebase/gridworks/main/webapp/../../extensions/rdf-exporter/module/MOD-INF/controller.js)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
    at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:456)
    ... 8 more

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=118_

**Comment by eliohb** [comment]
I have install red extension 1.1.0 and i put all the file in  ..\openrefine-3.1\webapp\extensions
and when i run the program the following error appear:
HTTP ERROR 500
Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later. (file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8._c_init_4(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js:89)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later.
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:213)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:302)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:286)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:938)
	at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:74)
	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
	at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 18 more
any advice

**Comment by wetneb** [comment]
@eliohb please report any issue related to the RDF extension here: https://github.com/stkenny/grefine-rdf-extension/issues

I will keep deleting your posts in this repository as they are off-topic.
