### ISSUE TITLE
"Store file source" doesn't work for multiple sheets in Excel file

### ISSUE THREAD

**Issue by thatbudakguy** [OpenRefine/OpenRefine#1181]
**System:**

OpenRefine Version 2.6-rc.2 [TRUNK]
Google Chrome Version 56.0.2924.87 (64-bit)
Mac OSX 10.11.6

**Issue:**

I have a .xlsx file with about 8 sheets, each of which has a few hundred rows. I want to import all the sheets to a single project, including the file/sheet source as a column. When I check "store file source", only the source of the first sheet whose box I check will be stored - all of the others will have a "source" column set to blank.

![screen shot 2017-03-16 at 10 01 26 am](https://cloud.githubusercontent.com/assets/4924494/24009031/e082770c-0a30-11e7-874b-9eb815039b76.png)

**Steps:**

1. Click "create project" and choose .xlsx source file with multiple sheets. Click "next".
2. Uncheck "parse column headers", as my sheets have none.
3. Check "store file source in each row".
4. Begin checking boxes for each sheet I want to include.

**Current results:**

The "store file source" option works fine for the first sheet (it shows `my_file.xlsx#sheet_n`) but no information shows in the preview for any of the other sheets (the source column is blank). Updating the preview does nothing, and when I create the project the results are the same as the preview. If I uncheck all of the sheets, then begin checking them again, *only the sheet that I check first* - regardless of which sheet it is - will have its source stored. All of the rest will be blank.

**Expected results:**

Each sheet would have an entry in the source column similar to `my_file.xslx#sheet_1`, so that I could extract the `sheet_1` information and use it.

**Comment by adieyal** [comment]
This works for me in Version 2.6-beta.1 [TRUNK] so I suspect that the regression happened between those two versions.

**Comment by adieyal** [comment]
This is the stack trace that I get with 2.6-rc.2
`
08:27:02.840 [      ImportingParserBase] ModelException adding Filename column (18ms)
com.google.refine.model.ModelException: Duplicated column name
	at com.google.refine.model.ColumnModel.addColumn(ColumnModel.java:120)
	at com.google.refine.importers.ImportingParserBase.addFilenameColumn(ImportingParserBase.java:169)
	at com.google.refine.importers.TabularImportingParserBase.readTable(TabularImportingParserBase.java:110)
	at com.google.refine.importers.ExcelImporter.parseOneFile(ExcelImporter.java:217)
	at com.google.refine.importers.ImportingParserBase.parseOneFile(ImportingParserBase.java:118)
	at com.google.refine.importers.ImportingParserBase.parse(ImportingParserBase.java:89)
	at com.google.refine.importing.ImportingUtilities.previewParse(ImportingUtilities.java:956)
	at com.google.refine.importing.DefaultImportingController.doUpdateFormatAndOptions(DefaultImportingController.java:185)
	at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:93)
	at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:62)
	at com.google.refine.RefineServlet.service(RefineServlet.java:177)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
08:27:02.852 [                   refine] POST /command/core/get-models (12ms)
08:27:02.863 [                   refine] POST /command/core/get-rows (11ms)
`

Looking at the code this is where it breaks in com.google.refine.importers.ImportingParserBase:
`
165     protected static int addFilenameColumn(Project project) {
166         String fileNameColumnName = "File";
167         assert project.columnModel.getColumnByName(fileNameColumnName) == null;
168         try {
169             project.columnModel.addColumn(
170                 0, new Column(project.columnModel.allocateNewCellIndex(), fileNameColumnNa    me), false);
171             return 0;
172         } catch (ModelException e) {
173             // Shouldn't happen: We already checked for duplicate name.
174             logger.error("ModelException adding Filename column",e);
175         }
176         return -1;
177     }
`

**Comment by thadguidry** [comment]
@thatbudakguy Curious, can you try again with OpenRefine 2.7rc2 beta release ?

**Comment by adieyal** [comment]
Same problem - see below. I also attached a test file

```
⇒  ./refine
Starting OpenRefine at 'http://127.0.0.1:3333/'

22:46:57.781 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
22:46:57.784 [            refine_server] refine.memory size: 1400M JVM Max heap: 1304952832 (3ms)
22:46:57.809 [            refine_server] Initializing context: '/' from '/Users/adieyal/Development/OpenRefine/main/webapp' (25ms)
22:46:57.903 [            refine_server] Starting autoreloading scanner...  (94ms)
22:46:58.450 [                   refine] Starting OpenRefine 2.7 [TRUNK]... (547ms)
22:47:06.405 [                   refine] POST /command/core/load-language (7955ms)
22:47:06.436 [                   refine] POST /command/core/load-language (31ms)
22:47:06.597 [                   refine] POST /command/core/get-importing-configuration (161ms)
22:47:06.622 [                   refine] GET /command/core/get-all-project-metadata (25ms)
22:47:06.661 [                   refine] GET /command/core/get-languages (39ms)
22:47:06.699 [                   refine] GET /command/core/get-version (38ms)
22:49:44.849 [                   refine] POST /command/core/create-importing-job (158150ms)
22:49:44.881 [                   refine] POST /command/core/importing-controller (32ms)
22:49:45.864 [                   refine] POST /command/core/get-importing-job-status (983ms)
22:49:45.934 [                   refine] POST /command/core/importing-controller (70ms)
22:49:47.575 [                   refine] POST /command/core/importing-controller (1641ms)
22:49:47.741 [                   refine] POST /command/core/get-models (166ms)
22:49:47.754 [                   refine] POST /command/core/get-rows (13ms)
22:50:03.417 [                   refine] POST /command/core/importing-controller (15663ms)
22:50:03.462 [                   refine] POST /command/core/get-models (45ms)
22:50:03.468 [                   refine] POST /command/core/get-rows (6ms)
22:50:05.858 [                   refine] POST /command/core/importing-controller (2390ms)
22:50:05.903 [      ImportingParserBase] ModelException adding Filename column (45ms)
com.google.refine.model.ModelException: Duplicated column name
	at com.google.refine.model.ColumnModel.addColumn(ColumnModel.java:120)
	at com.google.refine.importers.ImportingParserBase.addFilenameColumn(ImportingParserBase.java:169)
	at com.google.refine.importers.TabularImportingParserBase.readTable(TabularImportingParserBase.java:110)
	at com.google.refine.importers.ExcelImporter.parseOneFile(ExcelImporter.java:217)
	at com.google.refine.importers.ImportingParserBase.parseOneFile(ImportingParserBase.java:118)
	at com.google.refine.importers.ImportingParserBase.parse(ImportingParserBase.java:89)
	at com.google.refine.importing.ImportingUtilities.previewParse(ImportingUtilities.java:956)
	at com.google.refine.importing.DefaultImportingController.doUpdateFormatAndOptions(DefaultImportingController.java:185)
	at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:93)
	at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:62)
	at com.google.refine.RefineServlet.service(RefineServlet.java:177)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
22:50:05.924 [                   refine] POST /command/core/get-models (21ms)
22:50:05.937 [                   refine] POST /command/core/get-rows (13ms)
```

[Untitled spreadsheet.xlsx](https://github.com/OpenRefine/OpenRefine/files/980298/Untitled.spreadsheet.xlsx)
