### ISSUE TITLE
Custom Tabular Export fails for .XLSX

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1185]
OpenRefine 2.7 rc2

```
16:54:22.830 [                   refine] POST /command/core/export-rows/EBI_RC_5
2_01_85.xlsx (552023ms)
16:54:22.986 [                  project] Loaded project 1723481959391 from disk
in 0 sec(s) (156ms)
ERROR:  ''
16:54:23.517 [          org.mortbay.log] /command/core/export-rows/EBI_RC_52_01_85.xlsx (531ms)
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/core.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.ZipPackagePropertiesMarshaller@7f7cc6b3
        at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:503)

        at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1441)
        at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:212)
        at com.google.refine.exporters.XlsExporter.export(XlsExporter.java:145)
        at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:107)
        at com.google.refine.RefineServlet.service(RefineServlet.java:177)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)

        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/core.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.ZipPackagePropertiesMarshaller@7f7cc6b3
        at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:486)

        ... 27 more
```

**Comment by ostephens** [comment]
I'm not seeing this error on the current master - @thadguidry are you able to re-test with the same file as reported above?

**Comment by thadguidry** [comment]
@ostephens Nope.  Can't recreate now.  Seems like from the log that Apache POI had a marshalling problem probably thrown up from some bit/byte that it didn't like while Zipping.  I'll close this.  We can reopen when I or someone else comes across the issue again on export creating large-ish .XLSX files
