### ISSUE TITLE
I cannot install OpenFire

### ISSUE THREAD

**Issue by wingedpanther** [OpenRefine/OpenRefine#1201]
Windows 10 64 Bit OS
`java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)`

when I double click on **openrefine.exe** I get following error,
`13:19:18.391 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
13:19:18.435 [            refine_server] Initializing context: '/' from 'E:\AFNAM\openrefine-2.7\webapp' (44ms)
13:19:21.178 [          org.mortbay.log] EXCEPTION  (2743ms)
java.lang.ClassNotFoundException: com.google.refine.RefineServlet
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:401)
        at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:363)
        at org.mortbay.util.Loader.loadClass(Loader.java:91)
        at org.mortbay.util.Loader.loadClass(Loader.java:71)
        at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:73)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
        at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
        at org.mortbay.jetty.Server.doStart(Server.java:224)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at com.google.refine.RefineServer.init(Refine.java:202)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)
13:19:21.187 [                        /] unavailable (9ms)
javax.servlet.UnavailableException: com.google.refine.RefineServlet
        at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:79)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
        at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
        at org.mortbay.jetty.Server.doStart(Server.java:224)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at com.google.refine.RefineServer.init(Refine.java:202)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)
13:19:21.197 [          org.mortbay.log] failed refine: java.lang.NullPointerException (10ms)
13:19:21.227 [          org.mortbay.log] Failed startup of context org.mortbay.jetty.webapp.WebAppContext@2752f6e2{/,E:\AFNAM\openrefine-2.7\webapp} (30ms)
java.lang.NullPointerException
        at java.lang.Class.isAssignableFrom(Native Method)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
        at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
        at org.mortbay.jetty.Server.doStart(Server.java:224)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at com.google.refine.RefineServer.init(Refine.java:202)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)
13:19:21.259 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (32ms)
13:19:21.260 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (1ms)
13:19:21.263 [          org.mortbay.log] EXCEPTION  (3ms)
java.lang.ClassNotFoundException: com.google.refine.RefineServlet
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.mortbay.util.Loader.loadClass(Loader.java:91)
        at org.mortbay.util.Loader.loadClass(Loader.java:71)
        at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:73)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
        at com.google.refine.RefineServer.configure(Refine.java:294)
        at com.google.refine.RefineServer.init(Refine.java:208)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)
13:19:21.265 [                        /] unavailable (2ms)
javax.servlet.UnavailableException: com.google.refine.RefineServlet
        at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:79)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
        at com.google.refine.RefineServer.configure(Refine.java:294)
        at com.google.refine.RefineServer.init(Refine.java:208)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)
Exception in thread "main" java.lang.NullPointerException
        at java.lang.Class.isAssignableFrom(Native Method)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
        at com.google.refine.RefineServer.configure(Refine.java:294)
        at com.google.refine.RefineServer.init(Refine.java:208)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)`

**refine.bat** did not help!

**Comment by joewiz** [comment]
Is the title of this issue a typo - perhaps autocorrect? :-)

**Comment by jackyq2015** [comment]
I just tired on refresh windows 10 64 bit Java 8. It works well. Are you sure you downloaded the binary [here](https://github.com/OpenRefine/OpenRefine/releases/download/2.7/openrefine-win-2.7.zip) not the source code?

**Comment by jyf1997** [comment]
How do you solve it?

**Comment by wetneb** [comment]
@jyf1997 please report your problem to the mailing list:

https://groups.google.com/forum/#!forum/openrefine
