### ISSUE TITLE
CacheLoader error when fetching URL

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1219]
I'm trying to extract  some Json from the Wikipedia API. When I use "Add column by fetching URLs" on URL like this one : 

https://fr.wikipedia.org/w/api.php?format=json&action=query&titles=Ab%C3%A9e%20(Belgique)&exlimit=2&prop=categories%7Cextracts%7Cinfo%7Crevisions&inprop=url&exintro=&explaintext=&redirects=&rvprop=content&rvsection=0

I get this error message (Windows 10, OpenRefine 2.7): 

```
Exception in thread "Thread-5" com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key https://fr.wikipedia.org/w/api.php?format=json&action=query&titles=Abée (Belgique)&exlimit=2&prop=categories%7Cextracts%7Cinfo%7Crevisions&inprop=url&exintro=&explaintext=&redirects=&rvprop=content&rvsection=0.
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2407)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2375)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3990)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3994)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4878)
        at com.google.refine.operations.column.ColumnAdditionByFetchingURLsOperation$ColumnAdditionByFetchingURLsProcess.cachedFetch(ColumnAdditionByFetchingURLsOperation.java:306)
        at com.google.refine.operations.column.ColumnAdditionByFetchingURLsOperation$ColumnAdditionByFetchingURLsProcess.run(ColumnAdditionByFetchingURLsOperation.java:267)
        at java.lang.Thread.run(Unknown Source)
```

Not really explicit... What's the problem ?

**Comment by wetneb** [comment]
@ettorerizza hmm, this bug seems to have been introduced by my caching feature… I will investigate asap.

**Comment by wetneb** [comment]
@ettorerizza This should be fixed in the development version. Sorry again!

**Comment by wetneb** [comment]
There are issues with the following urls:
https://api.oadoi.org/10.13306/j.1672-3813.2015.03.001?email=dev@openrefine.org
https://api.oadoi.org/10.13306/j.1672-3813.2015.03.001?email=dev@openrefine.org

**Comment by wetneb** [comment]
I confirm that this is fixed on master.
