### ISSUE TITLE
Exporting to Excel on attached project raises server exception

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#122]
_Original author: bil...@gmail.com (September 02, 2010 19:08:22)_

<b>What steps will reproduce the problem?</b>
1. Import the attached project.  (I tried to create a smaller TSV file that exhibits the problem but I couldn't.)
2. Attempt to export filtered records (all of them, by default) to Excel.
3. The operation fails; the following web page is generated:

<b>What is the expected output? What do you see instead?</b>

Instead of generating an Excel file, a web page with the following is generated:

HTTP ERROR 500

Problem accessing /command/core/export-rows/test3.xls. Reason:

```
STREAM
```

Caused by:

java.lang.IllegalStateException: STREAM
    at org.mortbay.jetty.Response.getWriter(Response.java:616)
    at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.getWriter(GzipFilter.java:358)
    at com.google.gridworks.commands.Command.respond(Command.java:194)
    at com.google.gridworks.commands.Command.respondException(Command.java:262)
    at com.google.gridworks.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:59)
    at com.google.gridworks.GridworksServlet.service(GridworksServlet.java:120)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Powered by Jetty://

<b>What version of the product are you using? On what operating system?</b>

Trunk, Windows 7

<b>Please provide any additional information below.</b>

The exception does not occur if you export to CSV or TSV (but there is another problem, which I'll report separately).

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=122_

**Comment by tfmorris** [comment]
svn r1370 is 194fb5e70699bab8515ca79cc71f37c5261e00b8 in git
