### ISSUE TITLE
Issue ERROR 503 in version 2.8

### ISSUE THREAD

**Issue by hpiedcoq** [OpenRefine/OpenRefine#1344]
Hi everybody,

I just downloaded version 2.8 for linux (ubuntu 17.04 up-to-date).
I get an error : 

-------
HTTP ERROR 503

Problem accessing /. Reason:

    java.lang.NumberFormatException: null

Caused by:

javax.servlet.UnavailableException: java.lang.NumberFormatException: null
	at org.mortbay.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:415)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:458)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:294)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)

-------
The complete log is the following : 

14:35:12.680 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
14:35:12.684 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (4ms)
14:35:12.713 [            refine_server] Initializing context: '/' from '/home/herve/Applications/Openrefine2.7/webapp' (29ms)
14:35:13.573 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (860ms)
14:35:13.694 [                        /] unavailable (121ms)
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at com.google.refine.RefineServlet.init(RefineServlet.java:132)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:180)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:294)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)
14:35:13.698 [          org.mortbay.log] Nested in javax.servlet.ServletException: java.lang.NumberFormatException: null: (4ms)
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at com.google.refine.RefineServlet.init(RefineServlet.java:132)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:180)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:294)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)
14:35:15.788 [          org.mortbay.log] /: javax.servlet.UnavailableException: java.lang.NumberFormatException: null (2090ms)
14:35:25.686 [          org.mortbay.log] /: javax.servlet.UnavailableException: java.lang.NumberFormatException: null (9898ms)

-------

Any clue?

Thanks

Hervé

P.D : the 2.7 directory in the log is normal : I didn't change its name, in order to not break a shortcut. But the actual version is 2.8.

Jdk version : 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by jackyq2015** [comment]
Your exception comes when setting the refine.autosave parameter from
refine.ini file.

 Did you make the change to that file? can you delete the old version and
try again?

I tried on my own Ubuntu. it works fine.

Jacky

**Comment by jackyq2015** [comment]
Just for you reference, the last part of refine.ini under the root of installation folder should be like this:
# Uncomment to increase autosave period to 60 mins (default: 5 minutes) for better performance of long-lasting transformations
#REFINE_AUTOSAVE_PERIOD=60

**Comment by hpiedcoq** [comment]
I didn't make any change to this file.
Line is commented. But to be sure, I'm going to make a fresh install (downloading from github is pretty slow today). Very strange indeed.

**Comment by hpiedcoq** [comment]
Yes you were right! fresh install did the trick!
Thanks jacky!
