### ISSUE TITLE
Upload  to Google SpreadSheet

### ISSUE THREAD

**Issue by emoron** [OpenRefine/OpenRefine#1363]
Appears the error: org.apache.xerces.kaxp.SAXParserFactoryImp cannot be cast to javax.xml.parsers.SAXParserFactory

**Comment by thadguidry** [comment]
@emoron Thanks for the issue!  However, we know we need to update our code base to work with the newest Google API's to get this working again.  We have this in our plans.

Similarly, I do get a slightly different error on a 36634 row by 13 column data set.

```
21:17:40.844 [                   refine] POST /command/gdata/upload (167256ms)
Exception in thread "Thread-5" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:958)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
        at javax.crypto.Cipher.doFinal(Cipher.java:2377)
        at sun.security.ssl.CipherBox.decrypt(Unknown Source)
        at sun.security.ssl.InputRecord.decrypt(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
        at sun.security.ssl.AppInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read1(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at sun.net.www.http.ChunkedInputStream.readAheadBlocking(Unknown Source)
        at sun.net.www.http.ChunkedInputStream.readAhead(Unknown Source)
        at sun.net.www.http.ChunkedInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
        at java.util.zip.InflaterInputStream.fill(Unknown Source)
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.util.zip.GZIPInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at java.io.PushbackInputStream.read(Unknown Source)
        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at com.google.gdata.util.io.base.UnicodeReader.read(UnicodeReader.java:110)
        at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)
        at org.apache.xerces.impl.XMLEntityScanner.scanContent(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
```

**Comment by jackyq2015** [comment]
Upgraded to new API.
