### ISSUE TITLE
Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1364]
Under JDK 8, windows 10, got exception 

```
11:17:58.979 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
11:17:58.987 [          org.mortbay.log] Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog (8ms)
11:17:58.991 [            refine_server] Initializing context: '/' from 'C:\jar\OpenRefine\main\webapp' (4ms)
11:17:59.017 [          org.mortbay.log] jetty-6.1.22 (26ms)
11:17:59.190 [          org.mortbay.log] NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet (173ms)
11:17:59.519 [          org.mortbay.log] Started SocketConnector@127.0.0.1:3333 (329ms)
11:17:59.522 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (3ms)
11:17:59.524 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (2ms)
11:17:59.533 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (9ms)
11:17:59.540 [       FileProjectManager] Using workspace directory: C:\Users\QC27926\AppData\Roaming\OpenRefine (7ms)
11:17:59.542 [       FileProjectManager] Loading workspace: C:\Users\QC27926\AppData\Roaming\OpenRefine\workspace.json (2ms)
11:17:59.574 [       FileProjectManager] Recovered project named Gramineae_2nd_test tsv in directory 1513869305742.project (32ms)
11:17:59.575 [       FileProjectManager] Recovered project named ?ukasz.csv in directory 1519610759618.project (1ms)
11:17:59.578 [       FileProjectManager] Recovered project named ?ukasz.csv in directory 1667915442467.project (3ms)
11:17:59.579 [       FileProjectManager] Recovered project named grid_small json in directory 2204240496311.project (1ms)
11:17:59.582 [       FileProjectManager] Skipping unnecessary workspace save (3ms)
11:17:59.593 [                butterfly] Starting butterfly ... (11ms)
11:17:59.593 [                butterfly] Properties loaded from C:\jar\OpenRefine\main\webapp\WEB-INF\butterfly.properties (0ms)
11:17:59.621 [                butterfly] > process properties (28ms)
11:17:59.621 [                butterfly]  Butterfly home: C:\jar\OpenRefine\main\webapp (0ms)
11:17:59.621 [                butterfly] < process properties (0ms)
11:17:59.621 [                butterfly] > load modules (0ms)
11:17:59.639 [                butterfly] < load modules (18ms)
11:17:59.639 [                butterfly] > create modules (0ms)
11:17:59.648 [                butterfly] < create modules (9ms)
11:17:59.648 [                butterfly] > load module wirings (0ms)
11:17:59.648 [                butterfly]  Loaded module wirings from: C:\jar\OpenRefine\main\webapp\WEB-INF\modules.properties (0ms)
11:17:59.649 [                butterfly] < load module wirings (1ms)
11:17:59.649 [                butterfly] > wire modules (0ms)
11:17:59.649 [                butterfly]  mounting modules (0ms)
11:17:59.649 [                butterfly]  No mount point defined for module 'jython', mounting to '/extension/jython' (0ms)
11:17:59.649 [                butterfly]  No mount point defined for module 'pc-axis', mounting to '/extension/pc-axis' (0ms)
11:17:59.649 [                butterfly]  No mount point defined for module 'gdata', mounting to '/extension/gdata' (0ms)
11:17:59.649 [                butterfly]  No mount point defined for module 'sample', mounting to '/extension/sample' (0ms)
11:17:59.650 [                butterfly] < wire modules (1ms)
11:17:59.650 [                butterfly] > configure modules (0ms)
11:17:59.903 [                butterfly] < configure modules (253ms)
11:17:59.903 [                butterfly] > initialize modules (0ms)
console: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
	at org.mozilla.javascript.gen.c4._c1(file:/C:/jar/OpenRefine/main/webapp/../../extensions/jython/module/MOD-INF/controller.js:46)
	at org.mozilla.javascript.gen.c4.call(file:/C:/jar/OpenRefine/main/webapp/../../extensions/jython/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.gen.c4.call(file:/C:/jar/OpenRefine/main/webapp/../../extensions/jython/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:296)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)

```

**Comment by thadguidry** [comment]
Tested and this is now resolved on Windows 10 with latest version from master branch (currently 3.1 beta).
Closing.
