### ISSUE TITLE
OR loads up every project on startup

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1385]
It's not clear to me which change introduced that, but when starting OpenRefine (as it currently is in master), it loads up every project I have in my workspace. That is of course out of question given that many of them only fit tightly in RAM.

```
10:55:43.842 [                  project] Loaded project 2475361881455 from disk in 0 sec(s) (525ms)
10:55:44.234 [                  project] Loaded project 1528435350264 from disk in 0 sec(s) (392ms)
10:55:44.265 [                  project] Loaded project 2349088755454 from disk in 0 sec(s) (31ms)
10:55:44.275 [                  project] Loaded project 1584801522352 from disk in 0 sec(s) (10ms)
10:55:44.280 [                  project] Loaded project 1929556086025 from disk in 0 sec(s) (5ms)
10:55:45.952 [                  project] Loaded project 2143810420148 from disk in 0 sec(s) (1672ms)
10:55:45.975 [                  project] Loaded project 2381805552844 from disk in 0 sec(s) (23ms)
10:55:49.063 [                  project] Loaded project 2277373365081 from disk in 3 sec(s) (3088ms)
10:55:49.119 [                  project] Loaded project 1505112078777 from disk in 0 sec(s) (56ms)
10:55:49.228 [                  project] Loaded project 1637861842177 from disk in 0 sec(s) (109ms)
10:55:49.244 [                  project] Loaded project 1530973533462 from disk in 0 sec(s) (16ms)
10:55:49.488 [                  project] Loaded project 2041620752791 from disk in 0 sec(s) (244ms)
10:55:49.511 [                  project] Loaded project 2117394407999 from disk in 0 sec(s) (23ms)
10:55:49.536 [                  project] Loaded project 1674057303368 from disk in 0 sec(s) (25ms)
10:55:49.643 [                  project] Loaded project 1658286079337 from disk in 0 sec(s) (107ms)
10:55:52.632 [                  project] Loaded project 2487546892659 from disk in 2 sec(s) (2989ms)
10:55:52.715 [                  project] Loaded project 1925779735488 from disk in 0 sec(s) (83ms)
10:55:52.741 [                  project] Loaded project 1634496109214 from disk in 0 sec(s) (26ms)
10:57:19.740 [                  project] Loaded project 2216860015693 from disk in 81 sec(s) (86999ms)
10:58:06.000 [                  project] Loaded project 2428035712111 from disk in 26 sec(s) (46260ms)
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.fasterxml.jackson.core.util.BufferRecycler.calloc(BufferRecycler.java:156)
	at com.fasterxml.jackson.core.util.BufferRecycler.allocCharBuffer(BufferRecycler.java:124)
	at com.fasterxml.jackson.core.io.IOContext.allocTokenBuffer(IOContext.java:197)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:904)
	at com.fasterxml.jackson.core.JsonFactory.createJsonParser(JsonFactory.java:1108)
	at com.google.refine.model.Row.loadStreaming(Row.java:223)
	at com.google.refine.model.Row.load(Row.java:218)
	at com.google.refine.model.Project.loadFromReader(Project.java:222)
	at com.google.refine.model.Project.loadFromInputStream(Project.java:185)
	at com.google.refine.io.ProjectUtilities.loadFromFile(ProjectUtilities.java:157)
	at com.google.refine.io.ProjectUtilities.load(ProjectUtilities.java:118)
	at com.google.refine.io.FileProjectManager.loadProject(FileProjectManager.java:246)
	at com.google.refine.ProjectManager.getProject(ProjectManager.java:507)
	at com.google.refine.io.FileProjectManager.saveToFile(FileProjectManager.java:302)
	at com.google.refine.io.FileProjectManager.saveWorkspace(FileProjectManager.java:259)
	at com.google.refine.io.FileProjectManager.recover(FileProjectManager.java:459)
	at com.google.refine.io.FileProjectManager.initialize(FileProjectManager.java:80)
	at com.google.refine.RefineServlet.init(RefineServlet.java:129)

```

**Comment by jackyq2015** [comment]
I cannot reproduce on master. But I can see it from my own repo metadata branch. The only thing I can think of is that you did not fire a build after switch back to the master.

I will fix it on my branch though.

**Comment by ostephens** [comment]
Just to check - is this loading projects every time, or just those that don't have (certain) metadata set?

**Comment by wetneb** [comment]
@ostephens it looks like it triggers the recovery procedure for damaged projects - as if OR could not find the project metadata file and had to infer it from the data itself. When starting OR again from an earlier version I can see many new projects, created from the original ones (which are still available).


![screenshot](http://pintoch.ulminfo.fr/0f9ad73f95/2017-12-19-092617_1280x800_scrot.png)

**Comment by wetneb** [comment]
That was indeed a bug on jacky's branch - sorry about that!
