### ISSUE TITLE
Erro when import xml file in version 2.7 and 2.8

### ISSUE THREAD

**Issue by lafaurie** [OpenRefine/OpenRefine#1391]
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.google.refine.importers.tree.XmlImportUtilities.findRecord(XmlImportUtilities.java:298)
        at com.google.refine.importers.tree.XmlImportUtilities.importTreeData(XmlImportUtilities.java:263)
        at com.google.refine.importers.tree.TreeImportingParserBase.parseOneFile(TreeImportingParserBase.java:222)
        at com.google.refine.importers.XmlImporter.parseOneFile(XmlImporter.java:202)
        at com.google.refine.importers.tree.TreeImportingParserBase.parseOneFile(TreeImportingParserBase.java:120)
        at com.google.refine.importers.tree.TreeImportingParserBase.parse(TreeImportingParserBase.java:86)
        at com.google.refine.importing.ImportingUtilities.previewParse(ImportingUtilities.java:956)
        at com.google.refine.importing.DefaultImportingController.doUpdateFormatAndOptions(DefaultImportingController.java:185)
        at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:93)
        at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:62)
        at com.google.refine.RefineServlet.service(RefineServlet.java:177)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
16:11:30.539 [          org.mortbay.log] /command/core/importing-controller (1ms)

**Comment by jackyq2015** [comment]
can you provide a sample xml file and the procedure you import the file?

**Comment by lafaurie** [comment]
This is the xml file [](https://drive.google.com/file/d/1ovhgPyPn6EpKpBfMwIihFWXdydbQza-R/view?usp=sharing ) it dosen't import completed

**Comment by jackyq2015** [comment]
Tried your file. I have no problem to load it. Did you use mouse to select whole document before creating the project? or you just select part of it so it only extract that block of xml?

**Comment by ostephens** [comment]
I can't recreate the error, but I would note that from what I can see this XML file doesn't work well in OpenRefine because it isn't a single hierarchical document, but rather contains 51 different types on thing each with it's own properties. From what I can see there are relationships defined between the entities described in the document based on 'id'. So this single file seems to me to be like a set of tables from a relational database, rather than a single table.

Loading this into OpenRefine doesn't work well as it can't be easily represented as a single table of data. In fact, OpenRefine ends up putting data in the same row which should be in separate rows, and groups rows together as 'records' when it shouldn't. There are also a large number of columns in the project because of all the different types.

The issue you've encountered loading the xml aside, you may want to consider what you are trying to achieve with this data in OpenRefine, and whether it will work for you. The [OpenRefine Google Group](https://groups.google.com/forum/#!forum/openrefine) is a good place to ask questions about the best approaches to different data and data structures, based on what you are trying to achieve.

**Comment by thadguidry** [comment]
I have no problem with this file when I selected with my mouse on the whole document element 

```<Documento version='1'>```

![screenshot-2017-12-23 impzdst 00120171019t0 xml - openrefine](https://user-images.githubusercontent.com/986438/34323486-0587601c-e811-11e7-8280-767dd8683cac.png)

The import and record view will be very slow to use because of technical details that we plan to fix later next year, but for now, its still usable, just slow and sluggish.

**Comment by ostephens** [comment]
@lafaurie any more information on this one? We've not been able to replicate the error you reported, so hard for us to progress unless you have any other details you can share with us?

**Comment by Hossein-Gholami** [comment]
Hi everyone,
faced the same issue. sure there is no problem when using workspace. this happens when using OpenRefine API.

**Comment by tfmorris** [comment]
@Hossein-Gholami A few things:
* Please don't piggy back on unrelated (and closed) bug reports
* If you've got an issue with a current release of OpenRefine, please[ create an issue ](https://github.com/OpenRefine/OpenRefine/issues/new/choose) with all the appropriate details requested in the template
* OpenRefine doesn't have any APIs documented for external use (except for the extension APIs). The client/server protocol is an internal interface.
