### ISSUE TITLE
Large tsv files raise "Java heap space" error

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#145]
_Original author: mcnamara.tim@gmail.com (September 30, 2010 10:33:20)_

<b>What steps will reproduce the problem?</b>
1. Attempt to create a project with large file (88mb was sufficient to cause error)

<b>What is the expected output? What do you see instead?</b>
Slow running, but completed import. HTTP 500 Error.

Traceback:

HTTP ERROR 500

Problem accessing /command/core/create-project-from-upload. Reason:

```
Java heap space
```

Caused by:

java.lang.OutOfMemoryError: Java heap space
    at java.util.ArrayList.&lt;init&gt;(ArrayList.java:112)
    at com.google.gridworks.model.Row.&lt;init&gt;(Row.java:29)
    at com.google.gridworks.importers.TsvCsvImporter.read(TsvCsvImporter.java:128)
    at com.google.gridworks.importers.TsvCsvImporter.read(TsvCsvImporter.java:41)
    at com.google.gridworks.commands.project.CreateProjectCommand.internalInvokeImporter(CreateProjectCommand.java:443)
    at com.google.gridworks.commands.project.CreateProjectCommand.load(CreateProjectCommand.java:311)
    at com.google.gridworks.commands.project.CreateProjectCommand.internalImportFile(CreateProjectCommand.java:297)
    at com.google.gridworks.commands.project.CreateProjectCommand.internalImport(CreateProjectCommand.java:139)
    at com.google.gridworks.commands.project.CreateProjectCommand.doPost(CreateProjectCommand.java:79)
    at com.google.gridworks.GridworksServlet.service(GridworksServlet.java:120)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:619)

Powered by Jetty://

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=145_

**Comment by thadguidry** [comment]
Closing as unreproducible. Data files needed for investigation.
