### ISSUE TITLE
Cannot open projects created with current Master branch build with OR 2.8

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1508]
Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
-----
Current build from Master branch

Operating Systems and version:
-----
MacOS High Sierra

Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
-----
All

Steps followed to create the issue:
-----
Build OR from current Master branch. Run, and create a project.
Close down OR and run OR 2.8
Try to open the project you've just created

If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):
-----

Current Results:
-----
Trying to open projects created with the current Master branch build with OR2.8 results in a null pointer exception in the console:

```
09:47:41.807 [                   refine] GET /command/core/get-all-project-metadata (2199ms)
09:47:41.810 [                   refine] GET /command/core/get-version (3ms)
09:47:41.813 [                   refine] GET /command/core/get-preference (3ms)
09:47:41.832 [                   refine] GET /command/core/get-languages (19ms)
09:47:41.922 [                   refine] POST /command/core/load-language (90ms)
09:47:41.930 [                   refine] POST /command/core/load-language (8ms)
09:47:41.974 [                   refine] POST /command/core/get-importing-configuration (44ms)
09:47:58.295 [                   refine] GET /command/core/get-project-metadata (16321ms)
09:47:58.297 [                   refine] GET /command/core/get-models (2ms)
09:47:58.303 [                   refine] GET /command/core/get-history (6ms)
09:47:58.303 [          org.mortbay.log] /command/core/get-history (0ms)
java.lang.NullPointerException
09:47:58.309 [                   refine] GET /command/core/get-preference (6ms)
09:47:58.440 [                   refine] POST /command/core/load-language (131ms)
09:47:58.450 [                   refine] POST /command/core/load-language (10ms)
09:47:58.495 [                   refine] GET /command/core/get-history (45ms)
09:47:58.496 [          org.mortbay.log] /command/core/get-history (1ms)
java.lang.NullPointerException
09:47:58.496 [                   refine] POST /command/core/get-rows (0ms)
09:48:31.303 [           ProjectManager] Saving some modified projects ... (32807ms)
java.lang.NullPointerException
java.lang.NullPointerException
09:48:31.326 [        project_utilities] Saved project '2163984995183' (23ms)
```
and an error in the browser console:
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)` 

The same project will open without a problem if you switch back to using the Master branch build.

Expected Results:
-----
Project should load in previous versions of OpenRefine, ideally back to 2.5

**Comment by jackyq2015** [comment]
PR #1524 created

**Comment by magdmartin** [comment]
I cannot open or create project after building OpenRefine from master 14e49d0099d9

system: Ubuntu 16.04 LTS
browser: chromium

The two project open properly in 2.8. 


```
 ./refine 
You have 15747M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
Starting OpenRefine at 'http://127.0.0.1:3333/'

22:55:47.530 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
22:55:47.531 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (1ms)
22:55:47.541 [            refine_server] Initializing context: '/' from '/home/martin/app/OpenRefine/main/webapp' (10ms)
22:55:47.594 [            refine_server] Starting autoreloading scanner...  (53ms)
22:55:47.936 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (342ms)
22:55:47.936 [                   refine] initializing FileProjectManager with dir (0ms)
22:55:47.936 [                   refine] /home/martin/.local/share/openrefine (0ms)
22:55:48.814 [       database-extension] Initializing OpenRefine Database... (764ms)
22:55:48.817 [       database-extension] Database Extension Mount point /extension/database/ [*] (3ms)
22:55:48.817 [       database-extension] Registering Database Extension Commands...... (0ms)
22:55:48.825 [       database-extension] Database Extension Command Registeration done!! (8ms)
22:55:48.826 [       database-extension] Database Operations Registered successfully... (1ms)
22:55:48.826 [       database-extension] Database Functions Registered successfully... (0ms)
22:55:48.830 [       DatabaseModuleImpl] *** Database Extension Module Initialization Completed!!*** (4ms)
Created new window in existing browser session.
[25814:25850:0307/225552.789968:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
22:55:53.646 [       database-extension] receiving request for styles/jquery.contextMenu.css (4816ms)
22:55:53.654 [       database-extension] receiving method for GET (8ms)
22:55:53.705 [       database-extension] receiving request for styles/pure.css (51ms)
22:55:53.708 [       database-extension] receiving method for GET (3ms)
22:55:53.715 [       database-extension] receiving request for styles/bootstrap.css (7ms)
22:55:53.724 [       database-extension] receiving method for GET (9ms)
22:55:53.744 [       database-extension] receiving request for styles/database-import.less (20ms)
22:55:53.747 [       database-extension] receiving method for GET (3ms)
22:55:54.336 [                   refine] POST /command/core/load-language (589ms)
22:55:54.378 [                   refine] GET /command/core/get-preference (42ms)
22:55:54.389 [                   refine] POST /command/core/load-language (11ms)
22:55:54.401 [                   refine] POST /command/core/load-language (12ms)
22:55:54.589 [                   refine] POST /command/core/get-importing-configuration (188ms)
22:55:54.604 [                   refine] GET /command/core/get-all-project-tags (15ms)
22:55:54.633 [                   refine] GET /command/core/get-all-project-metadata (29ms)
22:55:54.680 [                   refine] GET /command/core/get-languages (47ms)
22:55:54.722 [                   refine] GET /command/core/get-version (42ms)
22:55:54.903 [       database-extension] receiving request for scripts/index/database-import-form.html (181ms)
22:55:54.903 [       database-extension] receiving method for GET (0ms)
22:55:54.913 [                   refine] GET /command/database/saved-connection (10ms)
22:56:02.214 [                   refine] POST /command/core/create-importing-job (7301ms)
22:56:02.224 [                   refine] POST /command/core/importing-controller (10ms)
22:56:03.219 [                   refine] POST /command/core/get-importing-job-status (995ms)
22:56:03.235 [                   refine] GET /command/core/get-all-project-tags (16ms)
22:56:03.261 [                   refine] POST /command/core/importing-controller (26ms)
22:56:03.313 [                   refine] POST /command/core/importing-controller (52ms)
22:56:03.362 [                   refine] POST /command/core/get-models (49ms)
22:56:03.370 [                   refine] POST /command/core/get-rows (8ms)
22:56:09.110 [                   refine] POST /command/core/importing-controller (5740ms)
22:56:10.118 [                   refine] POST /command/core/get-importing-job-status (1008ms)
22:56:10.121 [                   refine] POST /command/core/cancel-importing-job (3ms)
22:56:11.191 [                   refine] POST /command/core/load-language (1070ms)
22:56:11.213 [                   refine] GET /command/core/get-preference (22ms)
22:56:11.219 [                   refine] POST /command/core/load-language (6ms)
22:56:11.223 [                   refine] POST /command/core/load-language (4ms)
22:56:11.310 [                   refine] GET /command/core/get-project-metadata (87ms)
22:56:11.311 [          org.mortbay.log] Error for /command/core/get-project-metadata (1ms)
java.lang.NoSuchMethodError: com.google.refine.ProjectManager.getProjectMetadata(J)Lcom/google/refine/ProjectMetadata;
	at com.google.refine.commands.project.GetProjectMetadataCommand.doGet(GetProjectMetadataCommand.java:62)
	at com.google.refine.RefineServlet.service(RefineServlet.java:171)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
22:56:36.725 [                   refine] POST /command/core/load-language (25414ms)
22:56:36.745 [                   refine] POST /command/core/load-language (20ms)
22:56:36.750 [                   refine] POST /command/core/load-language (5ms)
22:56:36.955 [                   refine] POST /command/core/get-importing-configuration (205ms)
22:56:37.279 [       database-extension] receiving request for scripts/index/database-import-form.html (324ms)
22:56:37.279 [       database-extension] receiving method for GET (0ms)
22:56:37.292 [                   refine] GET /command/database/saved-connection (13ms)
22:56:45.741 [                   refine] POST /command/core/create-importing-job (8449ms)
22:56:45.750 [                   refine] POST /command/core/importing-controller (9ms)
22:56:46.746 [                   refine] POST /command/core/get-importing-job-status (996ms)
22:56:46.761 [                   refine] GET /command/core/get-all-project-tags (15ms)
22:56:46.785 [                   refine] POST /command/core/importing-controller (24ms)
22:56:47.031 [                   refine] POST /command/core/importing-controller (246ms)
22:56:47.039 [           ProjectManager] Saving all modified projects ... (8ms)
22:56:47.059 [        project_utilities] Saved project '1806062362487' (20ms)
22:56:47.075 [                   refine] POST /command/core/get-models (16ms)
22:56:47.080 [                   refine] POST /command/core/get-rows (5ms)
22:56:49.509 [                   refine] POST /command/core/importing-controller (2429ms)
Exception in thread "Thread-7" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at com.google.refine.importing.ImportingUtilities.inferColumnType(ImportingUtilities.java:1143)
	at com.google.refine.importing.ImportingUtilities.createProjectSynchronously(ImportingUtilities.java:1130)
	at com.google.refine.importing.ImportingUtilities.access$200(ImportingUtilities.java:115)
	at com.google.refine.importing.ImportingUtilities$7.run(ImportingUtilities.java:1076)
22:56:50.515 [                   refine] POST /command/core/get-importing-job-status (1006ms)
22:56:51.514 [                   refine] POST /command/core/get-importing-job-status (999ms)
22:56:52.516 [                   refine] POST /command/core/get-importing-job-status (1002ms)
22:56:53.515 [                   refine] POST /command/core/get-importing-job-status (999ms)
22:56:54.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:56:55.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:56:56.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:56:57.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:56:58.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:56:59.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:00.514 [                   refine] POST /command/core/get-importing-job-status (999ms)
22:57:01.515 [                   refine] POST /command/core/get-importing-job-status (1001ms)
22:57:02.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:03.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:04.516 [                   refine] POST /command/core/get-importing-job-status (1001ms)
22:57:05.517 [                   refine] POST /command/core/get-importing-job-status (1001ms)
22:57:06.515 [                   refine] POST /command/core/get-importing-job-status (998ms)
22:57:07.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:08.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:09.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:10.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:11.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:12.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:13.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:14.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:15.516 [                   refine] POST /command/core/get-importing-job-status (1001ms)
22:57:16.516 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:17.514 [                   refine] POST /command/core/get-importing-job-status (998ms)
22:57:18.515 [                   refine] POST /command/core/get-importing-job-status (1001ms)
22:57:19.517 [                   refine] POST /command/core/get-importing-job-status (1002ms)
22:57:20.515 [                   refine] POST /command/core/get-importing-job-status (998ms)
22:57:21.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:22.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:23.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:24.515 [                   refine] POST /command/core/get-importing-job-status (1000ms)
22:57:24.780 [                   refine] POST /command/core/cancel-importing-job (265ms)
^C
gi22:57:31.130 [           ProjectManager] Saving all modified projects ... (6350ms)
22:57:31.136 [        project_utilities] Saved project '1806062362487' (6ms)
22:57:31.137 [        project_utilities] Saved project '1862328122730' (1ms)

```

FYI the second load was a very small XLS file and take few seconds to create a project from it with 2.8. 
When I go back to the home page, the two projects are listed under `open project`. When I try to open them I got the spinner running and the following logs
```
23:01:51.599 [          org.mortbay.log] Error for /command/core/get-project-metadata (5ms)
java.lang.NoSuchMethodError: com.google.refine.ProjectManager.getProjectMetadata(J)Lcom/google/refine/ProjectMetadata;
	at com.google.refine.commands.project.GetProjectMetadataCommand.doGet(GetProjectMetadataCommand.java:62)
	at com.google.refine.RefineServlet.service(RefineServlet.java:171)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by magdmartin** [comment]
doing some investigation. I got the error up to commit c4b0ff6b which is for data package metadata (#1398). I can open and create projects when I checkout 47f44b06c45

**Comment by jackyq2015** [comment]
@magdmartin Most likely it is build issue. there is some class can not be found. If you do a "ant clean" should fix the issue.

**Comment by magdmartin** [comment]
@jackyq2015 thanks for the tip. Using `ant clean build` fixed the issue.
