### ISSUE TITLE
NullPointerException when importing an XML file due to the Data Package integration

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1509]
When importing an XML file with OpenRefine (master branch, https://github.com/OpenRefine/OpenRefine/commit/ad06d4c7a3b2ea53d8b302f4c758fac1d991146c), I get the following exception:

```
10:18:55.608 [                   refine] POST /command/core/importing-controller (18765ms)
Exception in thread "Thread-6" java.lang.NullPointerException
	at io.frictionlessdata.tableschema.TypeInferrer.infer(TypeInferrer.java:161)
	at com.google.refine.importing.ImportingUtilities.createProjectSynchronously(ImportingUtilities.java:1137)
	at com.google.refine.importing.ImportingUtilities.access$1(ImportingUtilities.java:1083)
	at com.google.refine.importing.ImportingUtilities$7.run(ImportingUtilities.java:1075)
```

This is a critical bug because Data Package integration breaks an unrelated existing importer.

The following file can be used to reproduce the bug:
http://pintoch.ulminfo.fr/ebae3e8b22/jorf.xml

**Comment by jackyq2015** [comment]
@wetneb Thanks for the sample. will look into this.
