### ISSUE TITLE
JSON deserialization exception due to the upgrade of org.json library in data package PR

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1517]
Yet another bug introduced by the data package PR:

OpenRefine is now unable to deserialize its own StandardReconConfig from JSON:
```
16:14:54.821 [             recon-config] Reconstruct failed (84ms)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.refine.model.recon.ReconConfig.reconstruct(ReconConfig.java:100)
	at com.google.refine.operations.recon.ReconOperation.reconstruct(ReconOperation.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.refine.operations.OperationRegistry.reconstruct(OperationRegistry.java:83)
	at com.google.refine.history.HistoryEntry.load(HistoryEntry.java:165)
	at com.google.refine.history.History.load(History.java:314)
	at com.google.refine.model.Project.loadFromReader(Project.java:210)
	at com.google.refine.model.Project.loadFromInputStream(Project.java:180)
	at com.google.refine.io.ProjectUtilities.loadFromFile(ProjectUtilities.java:187)
	at com.google.refine.io.ProjectUtilities.loadDataFile(ProjectUtilities.java:123)
	at com.google.refine.io.ProjectUtilities.load(ProjectUtilities.java:135)
	at com.google.refine.io.FileProjectManager.loadProject(FileProjectManager.java:258)
	at com.google.refine.ProjectManager.getProject(ProjectManager.java:507)
	at com.google.refine.commands.Command.getProject(Command.java:181)
	at com.google.refine.commands.project.GetProjectMetadataCommand.doGet(GetProjectMetadataCommand.java:56)
	at com.google.refine.RefineServlet.service(RefineServlet.java:171)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.json.JSONException: JSONObject["limit"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:721)
	at com.google.refine.model.recon.StandardReconConfig.reconstruct(StandardReconConfig.java:115)

```

This happens even without having to switch versions: create a project with the master version, reconcile a column to wikidata, and reopen this project with the master version: you will get this bug. This is because the `org.json` library was updated to a newer version, which changes the behaviour of `JSONObject.getString`, which fails if the target value is not a `String` (whereas it used to convert it silently to a string before).

This is a big issue: it means the same problem could happen potentially in any class that deserializes numbers. This confirms the concern I had when reviewing the PR: updates of libraries are important changes that need to be discussed in their own PRs. The Data Package PR has introduced many serious bugs (see #1509). I suspect it is also the cause of #1508.

@jackyq2015 we need to consider reverting that PR.

**Comment by thadguidry** [comment]
@wetneb Agreed, revert the PR.  Then @jackyq2015 can fix, and we can put more robust tests in place.

**Comment by jackyq2015** [comment]
Fixed this issue. Reviewed other possible JsonObject.toString cases, seems this is the only one which try to read a int as string. Will create PR after more checking.
