### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError in Windows 8.1 (BootCamp)

### ISSUE THREAD

**Issue by Stolyassa** [OpenRefine/OpenRefine#1522]
OpenRefine2.8
Windows 8.1 Pro 64 Bit  (BootCamp version in MacBook Pro)
Google Chrome 64.0.3282.167  64 Bit

### Steps to reproduce

(1) Download OpenRefine from "https://github.com/OpenRefine/OpenRefine/releases/download/2.8/openrefine-win-2.8.zip"
(2) Eject .zip into folder.
(3) Click "openrefine.exe" or "refine.bat"
(4) It recycles on "http://127.0.0.1:3333/" that "Butterfly still initializing...". 
(5) OpenRefine never starts.

### Current Results
Error message on command line:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:100)
        at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
        at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
        at com.google.refine.jython.JythonEvaluable.<clinit>(JythonEvaluable.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
        at org.mozilla.javascript.gen.c4._c1(file:/C:/Users/Hayriye/Downloads/openrefine-win-2.8%20(1)/openrefine-2.8/webapp/extensions/jython/module/MOD-INF/controller.js:46)
        at org.mozilla.javascript.gen.c4.call(file:/C:/Users/Hayriye/Downloads/openrefine-win-2.8%20(1)/openrefine-2.8/webapp/extensions/jython/module/MOD-INF/controller.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
        at org.mozilla.javascript.gen.c4.call(file:/C:/Users/Hayriye/Downloads/openrefine-win-2.8%20(1)/openrefine-2.8/webapp/extensions/jython/module/MOD-INF/controller.js)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
        at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
        at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
        at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
        at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
        at com.google.refine.RefineServer.configure(Refine.java:296)
        at com.google.refine.RefineServer.init(Refine.java:208)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
        at org.python.core.PyString.<init>(PyString.java:57)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.PyString.<init>(PyString.java:74)
        at org.python.core.Py.newString(Py.java:647)
        at org.python.core.PyJavaType.init(PyJavaType.java:585)
        at org.python.core.PyType.createType(PyType.java:1523)
        at org.python.core.PyType.addFromClass(PyType.java:1462)
        at org.python.core.PyType.fromClass(PyType.java:1551)
        at org.python.core.PyObject.<init>(PyObject.java:93)
        at org.python.core.PySingleton.<init>(PySingleton.java:9)
        at org.python.core.PyNotImplemented.<init>(PyNotImplemented.java:10)
        at org.python.core.Py.<clinit>(Py.java:94)
        ... 27 more

```
### Expected Results
I want to start and use OpenRefine in my Windows 8.1 rather than MacOSX. I always had to switch operating systems because of this error.

**Comment by thadguidry** [comment]
@Stolyassa Hi, it looks like you might have some non-English characters in your username perhaps ?  Try to extract the contents of the .zip file again to a more basic path like just C:\OpenRefine2.8\ 

My hunch is that `%`sign in the path of `\openrefine-win-2.8%20(1)` is what is causing this issue for you, so try to avoid creating that when you extract the zip file.

Let us know if the new path works for you.

**Comment by Stolyassa** [comment]
Hello @thadguidry , Thank for the answer. I do not know why the error shows % symbol because there was not any in the actual path. I changed the path name with what you suggested as C:\openrefine2.8\

The issue contiunes just like before. Here is the error.

You have 4101M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocat
e more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory

23:27:21.294 [            refine_server] Starting Server bound to '127.0.0.1:333
3' (0ms)
23:27:21.297 [            refine_server] refine.memory size: 1400M JVM Max heap:
 1468006400 (3ms)
23:27:21.306 [            refine_server] Initializing context: '/' from 'C:\open
refine2.8\webapp' (9ms)
23:27:21.805 [            refine_server] Failed to use jdatapath to detect user
data path: resorting to environment variables (499ms)
23:27:21.806 [            refine_server] Failed to use jdatapath to detect user
data path: resorting to environment variables (1ms)
23:27:21.815 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (9ms
)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:100)
        at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
        at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
        at com.google.refine.jython.JythonEvaluable.<clinit>(JythonEvaluable.jav
a:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:24
7)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java
:119)
        at org.mozilla.javascript.gen.c4._c1(file:/C:/openrefine2.8/webapp/exten
sions/jython/module/MOD-INF/controller.js:46)
        at org.mozilla.javascript.gen.c4.call(file:/C:/openrefine2.8/webapp/exte
nsions/jython/module/MOD-INF/controller.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:3
98)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:306
5)
        at org.mozilla.javascript.gen.c4.call(file:/C:/openrefine2.8/webapp/exte
nsions/jython/module/MOD-INF/controller.js)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModu
leImpl.java:636)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl
.java:94)
        at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:47
6)
        at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
        at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
        at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.jav
a:440)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:26
3)
        at com.google.refine.RefineServer.configure(Refine.java:296)
        at com.google.refine.RefineServer.init(Refine.java:208)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)
Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-b
yte value
        at org.python.core.PyString.<init>(PyString.java:57)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.PyString.<init>(PyString.java:74)
        at org.python.core.Py.newString(Py.java:647)
        at org.python.core.PyJavaType.init(PyJavaType.java:585)
        at org.python.core.PyType.createType(PyType.java:1523)
        at org.python.core.PyType.addFromClass(PyType.java:1462)
        at org.python.core.PyType.fromClass(PyType.java:1551)
        at org.python.core.PyObject.<init>(PyObject.java:93)
        at org.python.core.PySingleton.<init>(PySingleton.java:9)
        at org.python.core.PyNotImplemented.<init>(PyNotImplemented.java:10)
        at org.python.core.Py.<clinit>(Py.java:94)
        ... 27 more

**Comment by thadguidry** [comment]
@Stolyassa is it possible you have Python already installed on a weird path ?  Do a cmd.exe and then type

`python -V`

what is the output ?

@ettorerizza any ideas also what might be the issue ?

**Comment by Stolyassa** [comment]
The output is in below.

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Tüm haklari saklidir.

C:\Windows\system32>python -V
Python 3.6.3

C:\Windows\system32>

**Comment by thadguidry** [comment]
@Stolyassa Ah !  can you uninstall that particular Python installation?  or if it is for other uses, then perhaps you can temporarily remove that Python from your Path in System or User environment variables on your Windows system ?  The reason is that I suspect it is getting in the way and Python 3.6.3 is being used as the interpreter instead of the Python 2.7.x already supplied in the Jython JAR file that we ship with OpenRefine.

This should explain a few things how Jython itself locates python.path and python.home
http://www.jython.org/archive/22/userfaq.html#where-s-the-registry-file
and
 http://www.jython.org/archive/22/userfaq.html#my-modules-can-not-be-found-when-imported-from-an-embedded-application

But first let me know if the above temporary remove or temporary path remove works for you.
Then we can see about how we can possibly add detection of this an give users a Warning about it in the future and save others some grief.

**Comment by thadguidry** [comment]
@Stolyassa Just confirming if you still need assistance or have resolved the issue or if you are now using a new Windows system and a later version of OpenRefine and no longer have this issue you reported?

Can we close this issue for you now?

**Comment by Stolyassa** [comment]
Hello, actually I'm unable to solve the issue, instead I am using an older version which seems not producing fatal errors. Yet, I'm unable to use any newer version ever.

**Comment by tfmorris** [comment]
@Stolyassa What is the most recent OpenRefine version that works for you?

As a guess, I'd check for Unicode values in either the path pointed to by the `python.path` environment variable or the path where OpenRefine is being run from.
----
A quick search indicates that this is probably related to Jython 2.7 and Unicode characters:
- https://stackoverflow.com/questions/30545083/jython-test-to-prevent-exception-cannot-create-pystring-with-non-byte-value#37555952
- https://github.com/jython/frozen-mirror/issues/90

Possible fix - use `Py.newStringOrUnicode()` in place of `Py.newString()`, although the interesting portion of the stack trace is missing (in the "... 27 more"), so it's hard to tell where the offending code is.

However, it's suspicious that this problem apparently started happening right after a very similar problem (#1236) was "fixed," so perhaps it's a side effect or consequence of that.

**Comment by Stolyassa** [comment]
I'm stuck with 2.7 for now. I will check the solution you suggested, when I get to the working environment.

**Comment by wetneb** [comment]
This seems to only affect old versions, we have upgraded to Jython 2.7.2 in the meantime, so I am tentatively closing this.
