### ISSUE TITLE
Manage wikidata account NPE exception

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#1531]
When reporting a bug please provide the following information to help reproduce the bug:

Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
Branch wikidata-extension

Operating Systems and version:
Ubuntu 17

Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Chrome

Steps followed to create the issue:
Click "WikiData"->"Manage wikidata account"

If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):
-----

Current Results:
20:31:03.499 [                   refine] GET /command/wikidata/login (10456ms)
20:31:03.502 [          org.mortbay.log] Error for /command/wikidata/login (3ms)
java.lang.ExceptionInInitializerError
	at org.openrefine.wikidata.editing.ConnectionManager.getInstance(ConnectionManager.java:63)
	at org.openrefine.wikidata.commands.LoginCommand.doPost(LoginCommand.java:47)
	at org.openrefine.wikidata.commands.LoginCommand.doGet(LoginCommand.java:75)
	at com.google.refine.RefineServlet.service(RefineServlet.java:171)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.openrefine.wikidata.editing.ConnectionManager.getStoredCredentials(ConnectionManager.java:111)
	at org.openrefine.wikidata.editing.ConnectionManager.restoreSavedConnection(ConnectionManager.java:96)
	at org.openrefine.wikidata.editing.ConnectionManager.<init>(ConnectionManager.java:69)
	at org.openrefine.wikidata.editing.ConnectionManager.<init>(ConnectionManager.java:50)
	at org.openrefine.wikidata.editing.ConnectionManager$ConnectionManagerHolder.<clinit>(ConnectionManager.java:59)
	... 26 more

Expected Results:
-----

**Comment by wetneb** [comment]
Thanks! I should definitely have tested this on a fresh workspace…

**Comment by wetneb** [comment]
I have added a commit that should solve the issue - let me know if it works for you.
