### ISSUE TITLE
metadata.temp.json does not exist

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1542]
When reporting a bug please provide the following information to help reproduce the bug:

Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
-----
Trunk

Operating Systems and version:
-----
Windows 10

Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
-----
Firefox latest

Steps followed to create the issue:
-----
No idea unfortunately

If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):
-----

Current Results:
-----
```
C:\Users\THAD\OpenRefine>"C:\Program Files\Java\jdk1.8.0_151\bin\java.exe" -cp "server\classes;server\lib\*"   -Xms1400M -Xmx1400M -Drefine.memory=1400M -Drefine.max_form_content_size=1048576 -Drefine.port=3333 -Drefine.host=127.0.0.1 -Drefine.webapp=main\webapp -Djava.library.path=server\lib/native/windows com.google.refine.Refine
08:42:01.065 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
08:42:01.065 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (0ms)
08:42:01.065 [            refine_server] Initializing context: '/' from 'C:\Users\THAD\OpenRefine\main\webapp' (0ms)
08:42:01.361 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (296ms)
08:42:01.361 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (0ms)
08:42:01.377 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (16ms)
08:42:01.377 [                   refine] initializing FileProjectManager with dir (0ms)
08:42:01.377 [                   refine] C:\Users\THAD\AppData\Roaming\OpenRefine (0ms)
08:42:01.486 [         project_metadata] java.io.FileNotFoundException: File 'C:\Users\THAD\AppData\Roaming\OpenRefine\1825969120998.project\metadata.temp.json' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:137)
        at com.google.refine.model.medadata.ProjectMetadata.loadFromFile(ProjectMetadata.java:551)
        at com.google.refine.io.ProjectMetadataUtilities.loadFromFile(ProjectMetadataUtilities.java:153)
        at com.google.refine.io.ProjectMetadataUtilities.load(ProjectMetadataUtilities.java:98)
        at com.google.refine.io.FileProjectManager.loadProjectMetadata(FileProjectManager.java:122)
        at com.google.refine.io.FileProjectManager.recover(FileProjectManager.java:452)
        at com.google.refine.io.FileProjectManager.initialize(FileProjectManager.java:83)
        at com.google.refine.RefineServlet.init(RefineServlet.java:130)
        at javax.servlet.GenericServlet.init(GenericServlet.java:241)
        at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:180)
        at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
        at com.google.refine.RefineServer.configure(Refine.java:296)
        at com.google.refine.RefineServer.init(Refine.java:208)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)
 (109ms)
08:42:01.596 [                  project] Loaded project 1825969120998 from disk in 0 sec(s) (110ms)
08:42:01.611 [..ject_metadata_utilities] Partially recovered missing metadata project in directory C:\Users\THAD\AppData\Roaming\OpenRefine\1825969120998.project - <recovered project> - 8 cols X 6137 rows - Notes|Injury Mechanism & All Other Leading Causes|Injury Mechanism & All Other Leading Causes Code|Cause of death|Cause of death Code|Deaths|Population|Crude Rate (15ms)
08:42:01.658 [                  project] Loaded project 1825969120998 from disk in 0 sec(s) (47ms)
```
Expected Results:
-----
Happyness :)
It looks like it tried to Partially recover however.

**Comment by jackyq2015** [comment]
Caused by different time format for the metadata created by different branches. Syncing the branch will solve the issue. But will refactoring the code on this part to make the error clear and less confusing.

**Comment by thadguidry** [comment]
@jackyq2015 Ah, good detective work.  Yes, when I am testing PR's I am always merging to master.  For checking the state of master, I always reset to head and then perform my testing.  The state of the branch on my work laptop right now is unclear until I get back to office, but if you were able to reproduce and see the issue then great !

Were you able to reproduce it with our current master state ?

**Comment by thadguidry** [comment]
CLOSING ISSUE: After chatting with Jacky, this is a non-issue and just a fact that I had 2 older projects that were created from a bug in previous master version around the metadata.  The bug has been fixed in master according to Jacky and so I'll just delete those 2 previous projects and create new one's.
