### ISSUE TITLE
Weird Servlet State exception when I click Refresh in Firefox latest

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1543]
When reporting a bug please provide the following information to help reproduce the bug:

Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
-----
Trunk

Operating Systems and version:
-----
Windows 10

Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
-----
Firefox latest

Steps followed to create the issue:
-----
Checkout master
start OpenRefine
Open Firefox
Ensure you don't open Project, just stay on home page of OpenRefine
Click Refresh button on Firefox
Click Refresh button on Firefox again

If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):
-----

Current Results:
-----
```
08:50:15.749 [                   refine] GET /command/database/saved-connection (8ms)
08:50:15.769 [                   refine] GET /command/core/get-all-project-tags (20ms)
08:50:15.779 [                   refine] GET /command/core/get-all-project-metadata (10ms)
08:50:15.883 [                   refine] GET /command/core/get-languages (104ms)
08:50:15.902 [                   refine] GET /command/core/get-version (19ms)
08:50:50.915 [          org.mortbay.log] /favicon.ico (35013ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFilter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilter.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:201)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
08:50:51.009 [       database-extension] receiving request for styles/jquery.contextMenu.css (94ms)
08:50:51.015 [       database-extension] receiving request for styles/bootstrap.css (6ms)
08:50:51.015 [       database-extension] receiving method for GET (0ms)
08:50:51.015 [       database-extension] receiving method for GET (0ms)
08:50:51.023 [       database-extension] receiving request for styles/database-import.less (8ms)
08:50:51.024 [       database-extension] receiving request for styles/pure.css (1ms)
08:50:51.025 [       database-extension] receiving method for GET (1ms)
08:50:51.026 [       database-extension] receiving method for GET (1ms)
08:50:51.216 [                   refine] POST /command/core/load-language (190ms)
08:50:51.224 [                   refine] GET /command/core/get-preference (8ms)
08:50:51.232 [                   refine] POST /command/core/load-language (8ms)
08:50:51.236 [                   refine] POST /command/core/load-language (4ms)
08:50:51.283 [                   refine] POST /command/core/get-importing-configuration (47ms)
08:50:51.328 [       database-extension] receiving request for scripts/index/database-import-form.html (45ms)
08:50:51.328 [       database-extension] receiving method for GET (0ms)
08:50:51.335 [                   refine] GET /command/database/saved-connection (7ms)
08:50:51.350 [                   refine] GET /command/core/get-all-project-tags (15ms)
08:50:51.358 [                   refine] GET /command/core/get-all-project-metadata (8ms)
08:50:51.435 [                   refine] GET /command/core/get-languages (77ms)
08:50:51.446 [                   refine] GET /command/core/get-version (11ms)
08:50:55.228 [          org.mortbay.log] /favicon.ico (3782ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFilter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilter.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:201)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
08:50:55.340 [       database-extension] receiving request for styles/jquery.contextMenu.css (112ms)
08:50:55.342 [       database-extension] receiving request for styles/bootstrap.css (2ms)
08:50:55.343 [       database-extension] receiving request for styles/pure.css (1ms)
08:50:55.343 [       database-extension] receiving request for styles/database-import.less (0ms)
08:50:55.345 [       database-extension] receiving method for GET (2ms)
08:50:55.346 [       database-extension] receiving method for GET (1ms)
08:50:55.348 [       database-extension] receiving method for GET (2ms)
08:50:55.349 [       database-extension] receiving method for GET (1ms)
08:50:55.518 [                   refine] POST /command/core/load-language (169ms)
08:50:55.526 [                   refine] GET /command/core/get-preference (8ms)
08:50:55.533 [                   refine] POST /command/core/load-language (7ms)
08:50:55.549 [                   refine] POST /command/core/load-language (16ms)
08:50:55.602 [                   refine] POST /command/core/get-importing-configuration (53ms)
08:50:55.655 [       database-extension] receiving request for scripts/index/database-import-form.html (53ms)
08:50:55.655 [       database-extension] receiving method for GET (0ms)
08:50:55.662 [                   refine] GET /command/database/saved-connection (7ms)
08:50:55.678 [                   refine] GET /command/core/get-all-project-tags (16ms)
08:50:55.687 [                   refine] GET /command/core/get-all-project-metadata (9ms)
08:50:55.768 [                   refine] GET /command/core/get-languages (81ms)
08:50:55.779 [                   refine] GET /command/core/get-version (11ms)
```
Expected Results:
-----
Happyness :)

**Comment by ettorerizza** [comment]
@thadguidry can I suggest a "report issue" template a little less invasive, such as : 

```
When reporting a bug please provide the following information to help reproduce the bug:

##### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
2.8


##### Operating Systems and version:


##### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:


##### Steps followed to create the issue:


##### If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):


##### Current Results:


##### Expected Results:
```

**Comment by jackyq2015** [comment]
what's your version of FF exactly?

**Comment by thadguidry** [comment]
59

**Comment by jackyq2015** [comment]
close it since it's dup of #1549
