### ISSUE TITLE
Show out of memory errors on UI for get-project-metadata, instead of silent spinner

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1549]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
OpenRefine 2.8

#### Operating Systems and version:
Windows 7

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Firefox 59

#### Steps followed to create the issue:
Open a large project in OpenRefine that has thousands of rows and about 10 columns.

#### Current Results:
Forever Spinner on UI

```
10:04:09.293 [            refine_server] Starting Server bound to '127.0.0.1:333
3' (0ms)
10:04:09.371 [            refine_server] Initializing context: '/' from 'C:\User
s\eguitha\Downloads\openrefine-2.8\webapp' (78ms)
10:04:13.458 [            refine_server] Failed to use jdatapath to detect user
data path: resorting to environment variables (4087ms)
10:04:13.458 [            refine_server] Failed to use jdatapath to detect user
data path: resorting to environment variables (0ms)
10:04:13.489 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (31m
s)
10:04:20.860 [                   refine] POST /command/core/load-language (7371m
s)
10:04:20.906 [                   refine] GET /command/core/get-preference (46ms)

10:04:20.918 [                   refine] POST /command/core/load-language (12ms)

10:04:21.057 [                   refine] POST /command/core/get-importing-config
uration (139ms)
10:04:21.166 [                   refine] GET /command/core/get-all-project-metad
ata (109ms)
10:04:21.358 [                   refine] GET /command/core/get-languages (192ms)

10:04:21.400 [                   refine] GET /command/core/get-version (42ms)
10:04:34.966 [          org.mortbay.log] /favicon.ico (13566ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapp
er.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFi
lter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilt
er.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:200)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)

        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
88)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)

        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpCo
nnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.
java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
10:04:36.422 [                   refine] POST /command/core/load-language (1456m
s)
10:04:36.456 [                   refine] GET /command/core/get-preference (34ms)

10:04:36.473 [                   refine] POST /command/core/load-language (17ms)

10:04:36.551 [                   refine] GET /command/core/get-project-metadata
(78ms)
10:08:37.262 [          org.mortbay.log] Error for /command/core/get-project-met
adata (240711ms)
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java
:1351)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:
906)
        at com.fasterxml.jackson.core.JsonFactory.createJsonParser(JsonFactory.j
ava:1108)
        at com.google.refine.model.Row.loadStreaming(Row.java:223)
        at com.google.refine.model.Row.load(Row.java:218)
        at com.google.refine.model.Project.loadFromReader(Project.java:224)
        at com.google.refine.model.Project.loadFromInputStream(Project.java:187)

        at com.google.refine.io.ProjectUtilities.loadFromFile(ProjectUtilities.j
ava:157)
        at com.google.refine.io.ProjectUtilities.load(ProjectUtilities.java:118)

        at com.google.refine.io.FileProjectManager.loadProject(FileProjectManage
r.java:231)
        at com.google.refine.ProjectManager.getProject(ProjectManager.java:482)
        at com.google.refine.commands.Command.getProject(Command.java:181)
        at com.google.refine.commands.project.GetProjectMetadataCommand.doGet(Ge
tProjectMetadataCommand.java:56)
        at com.google.refine.RefineServlet.service(RefineServlet.java:170)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)

        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
88)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)

        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpCo
nnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
10:12:49.460 [          org.mortbay.log] /favicon.ico (252198ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapp
er.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFi
lter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilt
er.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:200)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)

        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
88)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)

        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpCo
nnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.
java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

#### Expected Results:
An Error Message popup or banner on the UI saying "Project could not be loaded (possible out of memory)" at this stage 
```
10:08:37.262 [          org.mortbay.log] Error for /command/core/get-project-met
adata (240711ms)
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java
:1351)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:
906)
        at com.fasterxml.jackson.core.JsonFactory.createJsonParser(JsonFactory.j
ava:1108)
        at com.google.refine.model.Row.loadStreaming(Row.java:223)
```

**Comment by jackyq2015** [comment]
Only happens on Firefox 59.0.1 (64bit)? Do you mind upload your project dump(Not just data)?

**Comment by thadguidry** [comment]
@jackyq2015 on my work laptop...will get for you on Monday.

**Comment by thadguidry** [comment]
@jackyq2015 emailed you the 60MB zipped project file.  Was too big to attach here at 10MB limit.

**Comment by jackyq2015** [comment]
@thadguidry I cannot reproduce this issue using the zipped project. It was loaded without any issue. could you please do a clean build on 2.8 and try again? If the problem still there, I guess the culprit might be other project. you can try to load the project only to verify this.

**Comment by thadguidry** [comment]
@jackyq2015 How much memory did you give it ?

**Comment by jackyq2015** [comment]
I use default one 1400M

$ ./refine
You have 15904M of free memory.
Your current configuration is set to use **1400M** of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
Starting OpenRefine at 'http://127.0.0.1:3333/'

21:52:31.646 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
21:52:31.647 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (1ms)
21:52:31.658 [            refine_server] Initializing context: '/' from '/media/cui/software/openrefine-2.8/webapp' (11ms)
21:52:32.405 [                   refine] Starting **OpenRefine 2.8** [TRUNK]... (747ms)
21:52:39.252 [                   refine] POST /command/core/load-language (6847ms)
21:52:39.291 [                   refine] GET /command/core/get-preference (39ms)
21:52:39.302 [                   refine] POST /command/core/load-language (11ms)
21:52:39.398 [                   refine] POST /command/core/get-importing-configuration (96ms)
21:52:39.419 [                   refine] GET /command/core/get-all-project-metadata (21ms)
21:52:39.455 [                   refine] GET /command/core/get-languages (36ms)
21:52:39.511 [                   refine] GET /command/core/get-version (56ms)
21:52:43.588 [                   refine] POST /command/core/load-language (4077ms)
21:52:43.608 [                   refine] GET /command/core/get-preference (20ms)
21:52:43.625 [                   refine] POST /command/core/load-language (17ms)
21:52:43.642 [                   refine] GET /command/core/get-project-metadata (17ms)
21:53:05.684 [                  project] Loaded project 1999903990309 from disk in 22 sec(s) (22042ms)
21:53:09.158 [                   refine] GET /command/core/get-models (3474ms)
21:53:09.222 [                   refine] POST /command/core/get-rows (64ms)
21:53:09.230 [                   refine] GET /command/core/get-history (8ms)
21:53:09.281 [                   refine] GET /command/core/get-history (51ms)
21:57:32.454 [           ProjectManager] Saving some modified projects ... (263173ms)
21:59:43.389 [        project_utilities] Saved project '**1999903990309**' (130935ms)
22:04:43.392 [           ProjectManager] Saving some modified projects ... (300003ms)
22:07:23.019 [        project_utilities] Saved project '1999903990309' (159627ms)

**Comment by thadguidry** [comment]
@jackyq2015 its the release version of 2.8  (there's no Ant tasks to perform) :)

**Comment by jackyq2015** [comment]
@thadguidry You can post you whole log. There might be other error which leads to this exception.

**Comment by thadguidry** [comment]
So this happens right when I started OpenRefine 2.8 on my work laptop...

```
10:18:17.831 [            refine_server] Starting Server bound to '127.0.0.1:333
3' (0ms)
10:18:17.862 [            refine_server] Initializing context: '/' from 'C:\User
s\eguitha\Downloads\openrefine-2.8\webapp' (31ms)
10:18:22.011 [            refine_server] Failed to use jdatapath to detect user
data path: resorting to environment variables (4149ms)
10:18:22.011 [            refine_server] Failed to use jdatapath to detect user
data path: resorting to environment variables (0ms)
10:18:22.121 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (110
ms)
10:18:36.939 [                   refine] POST /command/core/load-language (14818
ms)
10:18:36.990 [                   refine] GET /command/core/get-preference (51ms)

10:18:37.019 [                   refine] POST /command/core/load-language (29ms)

10:18:37.242 [                   refine] POST /command/core/get-importing-config
uration (223ms)
10:18:37.413 [                   refine] GET /command/core/get-all-project-metad
ata (171ms)
10:18:37.594 [                   refine] GET /command/core/get-languages (181ms)

10:18:37.648 [                   refine] GET /command/core/get-version (54ms)
10:18:37.748 [          org.mortbay.log] /images/favicon.png (100ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapp
er.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFi
lter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilt
er.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:200)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)

        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
88)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)

        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpCo
nnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.
java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by jackyq2015** [comment]
The root cause seems still the Firefox 59  issue. I closed the #1543 since it's dup

**Comment by jackyq2015** [comment]
@thadguidry I installed the 59.0.1 on windows 10, 64 bit, but still cannot reproduce issue. But I got something weird though:
18:00:06.431 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (62ms)
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr
OpenGL Warning: crPixelCopy3D:  simply crMemcpy'ing from srcPtr to dstPtr

Did you tune your FF about:config setting somehow?

**Comment by thadguidry** [comment]
@jackyq2015 nope

**Comment by jackyq2015** [comment]
can someone help to reproduce this bug with OpenRefine 2.8 under FF 59.0.1, Windows 10 64 bit?

**Comment by ettorerizza** [comment]
I'll try to work with Firefox today, but my version is 59.0.2.

**Comment by jackyq2015** [comment]
@ettorerizza any result with 59.0.2?

**Comment by ettorerizza** [comment]
@jackyq2015 No problem yesterday working with this version of Firefox and OR 2.8 on Windows 10, but I have allocated a lot of memory to Refine and my datastets are relatively small.

**Comment by jackyq2015** [comment]
@ettorerizza Thanks! If you use the default memory setting, can you reproduce it?
