### ISSUE TITLE
Ubuntu Linux 16.04, OpenJDK 1.9.0: java.lang.Error: class java.lang.IllegalAccessException

### ISSUE THREAD

**Issue by richiebful** [OpenRefine/OpenRefine#1620]
#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
- OpenRefine 2.8
- **OpenJDK 1.9.0 (Java 9)**

#### Operating Systems and version:
Ubuntu Linux 16.04
OpenJDK

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:
Firefox 60.0.1, but this error isn't browser-related

#### Steps followed to create the issue:
1. Run ./refine from the command line
2. Browser window will open with only the OpenRefine logo
3. Crashes with results below

#### Current Results:
```
11:27:44.374 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (6107ms)
11:28:06.756 [          org.mortbay.log] Error for /index-bundle.js (22382ms)
java.lang.Error: class java.lang.IllegalAccessException: java.lang.IllegalAccessException: class org.mozilla.javascript.MemberBox cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @4543a47b
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1777)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:169)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
	at org.mozilla.javascript.gen.c2._c5(file:/home/rfulop/workspace/scratch/openrefine/OpenRefine-2.8/main/webapp/modules/core/MOD-INF/controller.js:567)
	at org.mozilla.javascript.gen.c2.call(file:/home/rfulop/workspace/scratch/openrefine/OpenRefine-2.8/main/webapp/modules/core/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.gen.c2.call(file:/home/rfulop/workspace/scratch/openrefine/OpenRefine-2.8/main/webapp/modules/core/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.process(ButterflyModuleImpl.java:399)
	at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.run(ButterflyModuleImpl.java:377)
	at org.mozilla.javascript.Context.call(Context.java:515)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:507)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.processScript(ButterflyModuleImpl.java:650)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.process(ButterflyModuleImpl.java:427)
	at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:516)
	at com.google.refine.RefineServlet.service(RefineServlet.java:200)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
```

#### Expected Results:

Browser window will contain the OpenRefine UI

**Comment by thadguidry** [comment]
@jackyq2015 is this reproducible with what we have in master now ?
