### ISSUE TITLE
Export data package doesn't work

### ISSUE THREAD

**Issue by ettorerizza** [OpenRefine/OpenRefine#1648]
When reporting a bug please provide the following information to help reproduce the bug:

#### Version of OpenRefine used (Google Refine 2.6, OpenRefine2.8, an other distribution?):
Version 3 beta

#### Operating Systems and version:
Windows 10

#### Browser + version used - Please note that OpenRefine doesn't support Internet Explorer but works OK in most cases:

Chrome, Firefox and Edge

#### Steps followed to create the issue:
Click on "Export" then "Project data package"

#### If you are allowed and are OK with making your data public, it would be awesome if you can include the data causing the issue or a URL pointing to where the data is (if your concerned about keeping your data private, ping us on our mailing list):

Any dataset

#### Current Results:

![screenshot-127 0 0 1-3333-2018 06 14-00-00-20](https://user-images.githubusercontent.com/6286410/41380850-58d57524-6f66-11e8-9cb7-78332799556c.png)

```
00:11:36.067 [          org.mortbay.log] /command/core/get-imetaData (192ms)
java.lang.NullPointerException
        at com.google.refine.model.medadata.MetadataFactory.buildDataPackageMetadata(MetadataFactory.java:57)
        at com.google.refine.commands.project.GetMetadataCommand.doGet(GetMetadataCommand.java:40)
        at com.google.refine.RefineServlet.service(RefineServlet.java:171)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

```
#### Expected Results:

A data package menu editor or a Json

**Comment by jackyq2015** [comment]
it is a typo. :)
