### ISSUE TITLE
3.0 Beta not responding, "butterfly is still initializing..."

### ISSUE THREAD

**Issue by whanley** [OpenRefine/OpenRefine#1671]
**Describe the bug**
OpenRefine 3.0 Beta does not open, stops responding. In browser, http://127.0.0.1:3333/ reads "Butterfly is still initializing..."

**To Reproduce**
1. Open beta from https://github.com/OpenRefine/OpenRefine/releases/download/3.0-beta/openrefine-mac-3.0-beta.dmg
2. Drag to applications
3. Open the program

**Current Results**
Icon bounces in tray for 30 seconds, then stops bouncing. No error message, except in browser.

**Expected behavior**
The program should open

**Desktop (please complete the following information):**
 - OS: OS High Sierra
 - Browser: Firefox
 - Version: 61.0

**OpenRefine (please complete the following information):**
OpenRefine 3.0 Beta

**Comment by thadguidry** [comment]
@whanley 
Are you able to use the Mac terminal/command line?

If you are confident with this, you can do the following:

Open a terminal
Change directory to
`/path/to/OpenRefine.app/Contents/MacOS/`

for example - if you installed in Applications, the command will be:

`cd /Applications/OpenRefine.app/Contents/MacOS/`

Run OpenRefine by using the command:

`/JavaAppLauncher`

This should start OpenRefine and in the terminal Window you should see the console/log
Copy Paste the error in the log that you see into a reply on this issue.

**Comment by whanley** [comment]
Here's the error:

```
whanley$ ./JavaAppLauncher
11:11:02.568 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
11:11:02.577 [            refine_server] Initializing context: '/' from '/Applications/OpenRefine.app/Contents/Resource/webapp' (9ms)
11:11:02.937 [          org.mortbay.log] failed SocketConnector@127.0.0.1:3333: java.net.BindException: Address already in use (360ms)
11:11:02.937 [          org.mortbay.log] failed RefineServer@5ae63ade: java.net.BindException: Address already in use (0ms)
11:11:02.937 [            refine_server] Failed to start server - is there another copy running already on this port/address? (0ms)
Exception in thread "main" java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:80)
	at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:73)
	at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:283)
	at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:147)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.Server.doStart(Server.java:235)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.refine.RefineServer.init(Refine.java:202)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)
```

Address already in use? It looks like OpenRefine is in fact running, but is not responding. When I force quit the non-responsive OpenRefine, this is the result:

```
wg-dhcp174d163d131:MacOS whanley$ ./JavaAppLauncher
11:13:49.666 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
11:13:49.675 [            refine_server] Initializing context: '/' from '/Applications/OpenRefine.app/Contents/Resource/webapp' (9ms)
11:13:50.016 [                   refine] Starting OpenRefine 3.0-beta [TRUNK]... (341ms)
11:13:50.016 [                   refine] initializing FileProjectManager with dir (0ms)
11:13:50.016 [                   refine] /Users/whanley/Library/Application Support/OpenRefine (0ms)
11:13:50.649 [       database-extension] Initializing OpenRefine Database... (633ms)
11:13:50.651 [       database-extension] Database Extension Mount point /extension/database/ [*] (2ms)
11:13:50.652 [       database-extension] Registering Database Extension Commands...... (1ms)
11:13:50.657 [       database-extension] Database Extension Command Registeration done!! (5ms)
11:13:50.657 [       database-extension] Database Operations Registered successfully... (0ms)
11:13:50.657 [       database-extension] Database Functions Registered successfully... (0ms)
Exception in thread "main" java.lang.LinkageError: loader constraint violation: loader (instance of edu/mit/simile/butterfly/ButterflyClassLoader) previously initiated loading for a different type with name "org/slf4j/Logger"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.refine.extension.database.DatabaseModuleImpl.readModuleProperty(DatabaseModuleImpl.java:93)
	at com.google.refine.extension.database.DatabaseModuleImpl.init(DatabaseModuleImpl.java:68)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:296)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)
```

Browser still shows "Butterfly is still initializing...", and the app itself won't open.

Thanks for your help.

**Comment by thadguidry** [comment]
@whanley by chance do you have any other external extensions installed for OpenRefine ?

**Comment by whanley** [comment]
Yes. RDF Refine--and maybe others though I can't remember...

**Comment by whanley** [comment]
I checked 2.8, and the RDF extension is the only one I have installed.

**Comment by thadguidry** [comment]
Ah, that might be because of the older RDF extension that is not 3.0 compatible ?

Check out @fmaali 's newer one: https://github.com/fadmaa/grefine-rdf-extension/tree/nimble-rdf-extension

**Comment by jackyq2015** [comment]
The same error with this issue:
https://github.com/OpenRefine/OpenRefine/issues/1636

**Comment by whanley** [comment]
Thank you @jackyq2015 and @thadguidry and @ettorerizza. You've solved my problem, which appears indeed to have been a problem with the extension.

As @janruehling suggested in #1636:
> 
> In your workspace directory (for me ~/Library/Application Support/OpenRefine):
> 
>     Rename "extensions" to "_extensions"
>     Create a new folder "extensions"
>     Copy one extension folder after the other from "_extensions" to "extensions" and restart OpenRefine
> 

I put this compiled [3.0 version](https://github.com/stkenny/grefine-rdf-extension/releases/tag/v1.0.0-rc2) of the RDF extension in my extensions folder, and everything works well now.

**Comment by anchardo** [comment]
Hello, 
I'm having the same bug as described by whanley in his first message. I hope someone can help me.

Desktop (please complete the following information):
OS: OS X El Capitan
Browser: Chrome
Version: 70.0

OpenRefine (please complete the following information):
OpenRefine 3.0

I have deleted the former rdf-extension, modified the extension folder as suggested by janruehling, nothing changed.

If I run Openrefine by launching a command in the Terminal, here is what I got in the console (I don't know which specific part is relevant...):

```
Raphaels-MBP:MacOS researcher$ ./JavaAppLauncher
21:32:58.454 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
21:32:58.466 [            refine_server] Initializing context: '/' from '/Applications/OpenRefine.app/Contents/Resource/webapp' (12ms)
21:32:58.922 [                   refine] Starting OpenRefine 3.0 [TRUNK]... (456ms)
21:32:58.922 [                   refine] initializing FileProjectManager with dir (0ms)
21:32:58.922 [                   refine] /Users/researcher/Library/Application Support/OpenRefine (0ms)
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/refine/ProjectMetadata
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:380)
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:335)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:450)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:76)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:838)
	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:84)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:78)
	at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:164)
	at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:114)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:1617)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1437)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1423)
	at org.mozilla.javascript.gen.c8._c1(file:/Users/researcher/Library/Application%20Support/OpenRefine/extensions/pc-axis/module/MOD-INF/controller.js:39)
	at org.mozilla.javascript.gen.c8.call(file:/Users/researcher/Library/Application%20Support/OpenRefine/extensions/pc-axis/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.gen.c8.call(file:/Users/researcher/Library/Application%20Support/OpenRefine/extensions/pc-axis/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:296)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)
Caused by: java.lang.ClassNotFoundException: com.google.refine.ProjectMetadata
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

```
