### ISSUE TITLE
Startup error: Assistive Technology not found [solved with workaround]

### ISSUE THREAD

**Issue by answerquest** [OpenRefine/OpenRefine#1714]
**Describe the bug**
On trying to start OpenRefine from Terminal, getting this error : `java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper` and the terminal freezes there, doesn't exit and doesn't proceed. See full log below.

**To Reproduce**
1. Open terminal at the OpenRefine folder.
2. Run `./refine`
3. After other initialization messages, terminal will display error messages, and freeze there.
4. Ctrl+C to return back to terminal

**Current Results**  
On trying to start from command line:  
```
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/java.awt.Window.getToolkit(Window.java:1375)
	at java.desktop/java.awt.Window.init(Window.java:518)
	at java.desktop/java.awt.Window.<init>(Window.java:549)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/java.awt.Frame.<init>(Frame.java:388)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
	at com.google.refine.RefineClient.<init>(Refine.java:461)
	at com.google.refine.Refine.init(Refine.java:122)
	at com.google.refine.Refine.main(Refine.java:108)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 20 more
```

**Expected behavior**
OpenRefine ought to start properly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Lubuntu 18.04 LTS 32-bit
 - Browser: N/A (stuck before browser stage)

**OpenRefine (please complete the following information):**
 - Version 3.0-rc1

**Datasets**
Not applicable

**Additional context**
Workaround found here: https://askubuntu.com/a/723503/730518  
Commented out the assistive technologies line in `/etc/java-11-openjdk/accessibility.properties`  
Now OpenRefine is running at my end, but as this is a workaround I'll update back here if it causes any problems further along.

**Comment by wetneb** [comment]
Thanks for the report! It looks like this is specific to your environment and not really OpenRefine. I am not sure what these assistive technologies would normally do - if this is not relevant for OpenRefine maybe we could add `-Djavax.accessibility.assistive_technologies=" "` to the `refine` script.

**Comment by answerquest** [comment]
@wetneb yes, even I have the same suspicions, that it's specific to this environment. And the tool ran just fine on my end with the workaround. For now I'm closing this as it's solved at my end, and hope when others having this problem search in the issues they find it.
