### ISSUE TITLE
Windows version : java.lang.NullPointerException at com.google.refine.io.FileProjectManager.saveToFile(FileProjectManager.java:316)

### ISSUE THREAD

**Issue by lapoisse** [OpenRefine/OpenRefine#1723]
**Describe the bug**
At the creation of a new project on CSV file, after the preview, there is no more than a running logo on the navigator. 

**To Reproduce**
1. create a new flat file project. (I tried a small file to control if it could be a memory problem but that is not the case).
2. pass the preview.
4. See nothing more on the navigator and the regular message into the console running the web server :
java.lang.NullPointerException
        at com.google.refine.io.FileProjectManager.saveToFile(FileProjectManager.java:316)
        at com.google.refine.io.FileProjectManager.saveWorkspace(FileProjectManager.java:272)
        at com.google.refine.ProjectManager.save(ProjectManager.java:232)
        at com.google.refine.RefineServlet$AutoSaveTimerTask.run(RefineServlet.java:92)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
17:03:58.808 [       FileProjectManager] Failed to save workspace (15ms)

**Desktop (please complete the following information):**
 - OS: Windows server 2016

**OpenRefine (please complete the following information):**
 -  OR 3.0-rc1

**Additional context**
It does not come from the data. with a simpler text file, it is not working too.

**Comment by lapoisse** [comment]
Some complementary informations  : 
- Jre 1.8.0_181

It is working fine on a windows 10 machine with the same VM.

**Comment by jackyq2015** [comment]
can you run refine.bat from the command line under the same folder has the exe file and paste the whole output from the beginning?

**Comment by lapoisse** [comment]
You will find the content from the server under the windows server 2016 OS. 
[test.txt](https://github.com/OpenRefine/OpenRefine/files/2358237/test.txt)

**Comment by lapoisse** [comment]
Same problem. Though the saving error is not here now. The new result is attached. 
[test.txt](https://github.com/OpenRefine/OpenRefine/files/2361795/test.txt)
