### ISSUE TITLE
More robust fetching of Wikidata entities during editing

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1746]
**Describe the bug**
Sometimes Wikibase returns HTTP 503 errors when fetching entities:
```
10:37:09.089 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 410 milliseconds. (1248ms)
10:37:10.612 [..ting.EditBatchProcessor] Requesting documents (1523ms)
10:39:15.685 [..kibaseapi.ApiConnection] Error: API request returned response code 503 (125073ms)
10:39:15.686 [..api.WbGetEntitiesAction] Could not retrive data: java.io.IOException: Server returned HTTP response code: 503 for URL: https://www.wikidata.org/w/api.php (1ms)
Exception in thread "Thread-8" java.lang.NullPointerException
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.markStatementsForInsertion(StatementUpdate.java:369)
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.markStatementsForUpdate(StatementUpdate.java:294)
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.<init>(StatementUpdate.java:179)
	at org.wikidata.wdtk.wikibaseapi.TermStatementUpdate.<init>(TermStatementUpdate.java:140)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.updateTermsStatements(WikibaseDataEditor.java:589)
	at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:145)
	at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:211)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. upload a large edit batch
2. wait for Wikibase to fail

**Comment by wetneb** [comment]
This is actually a bug in the upstream library:
https://github.com/Wikidata/Wikidata-Toolkit/issues/402
