### ISSUE TITLE
XML importer seems to be missing elements

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1800]
**Describe the bug**
When importing http://www.isuresults.com/results/season1819/gpfin2018/CAT003RS.HTM with the XML importer, only parts of the HTML tree are displayed.

**To Reproduce**
1. Import `http://www.isuresults.com/results/season1819/gpfin2018/CAT003RS.HTM`
2. Choose the XML importer
3. See that elements are missing

**Current Results**
![image](https://user-images.githubusercontent.com/309908/47953459-fa66aa00-df75-11e8-9c67-1514899868b5.png)

**Expected behavior**
the source of the webpage contains much more:
![image](https://user-images.githubusercontent.com/309908/47953478-18340f00-df76-11e8-915e-f49b2380fe09.png)

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Browser Version: Firefox and Chromium
 - JRE or JDK Version: 8

**OpenRefine (please complete the following information):**
 - Version 3.0

**Comment by wetneb** [comment]
it seems to be due to a hard limit on the number of tokens parsed:

https://github.com/OpenRefine/OpenRefine/blob/3b3e319e0bda368eaeccb471ca5130e0cc8777e2/main/src/com/google/refine/importers/XmlImporter.java#L75

**Comment by wetneb** [comment]
In fact it's just because that HTML is not valid as XML… so this should just be solved by implementing an HTML importer - that's not in the scope of this issue.

```
18:48:30.866 [..e.importers.XmlImporter] Error generating parser UI initialization data for XML file (1ms)
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[16,35]
Message: Le nom de l'identité doit immédiatement suivre le caractère "&" dans la référence d'entité.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.google.refine.importers.XmlImporter.descendElement(XmlImporter.java:181)
	at com.google.refine.importers.XmlImporter.descendElement(XmlImporter.java:186)
	at com.google.refine.importers.XmlImporter.extractDomSample(XmlImporter.java:118)
	at com.google.refine.importers.XmlImporter.createParserUIInitializationData(XmlImporter.java:87)
	at com.google.refine.importing.DefaultImportingController.doInitializeParserUI(DefaultImportingController.java:215)
	at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:90)
	at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:62)
	at com.google.refine.RefineServlet.service(RefineServlet.java:190)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
