### ISSUE TITLE
3.0 Not responding (MAC)

### ISSUE THREAD

**Issue by anchardo** [OpenRefine/OpenRefine#1823]
**Describe the bug**
I have the same bug as described by @whanley in https://github.com/OpenRefine/OpenRefine/issues/1671 so I'll just copy paste the first paragraphs: 

**To Reproduce**

1. Open v 3.0 from https://github.com/OpenRefine/OpenRefine/releases/download/3.0/openrefine-mac-3.0.dmg
2. Drag to applications
3. Open the program

**Current Results**
Icon bounces in tray for some seconds, then stops bouncing. No error message, except in browser.

**Expected behavior**
The program should open.

**To Reproduce**

**Desktop :**
OS: OS X El Capitan
Browser: Chrome
Version: 70.0

**OpenRefine :**
OpenRefine 3.0

After reading related issues, I have clicked on 'replace' (the version 2.8) during the installation process, deleted the former rdf-extension, modified the extension folder as suggested by @janruehling, nothing changed.

If I run Openrefine by launching a command in the Terminal, here is what I got in the console (I don't know which specific part is relevant...):

```
Raphaels-MBP:MacOS researcher$ ./JavaAppLauncher
21:32:58.454 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
21:32:58.466 [            refine_server] Initializing context: '/' from '/Applications/OpenRefine.app/Contents/Resource/webapp' (12ms)
21:32:58.922 [                   refine] Starting OpenRefine 3.0 [TRUNK]... (456ms)
21:32:58.922 [                   refine] initializing FileProjectManager with dir (0ms)
21:32:58.922 [                   refine] /Users/researcher/Library/Application Support/OpenRefine (0ms)
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/refine/ProjectMetadata
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:380)
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:335)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:450)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:76)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:838)
	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:84)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:78)
	at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:164)
	at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:114)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:1617)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1437)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1423)
	at org.mozilla.javascript.gen.c8._c1(file:/Users/researcher/Library/Application%20Support/OpenRefine/extensions/pc-axis/module/MOD-INF/controller.js:39)
	at org.mozilla.javascript.gen.c8.call(file:/Users/researcher/Library/Application%20Support/OpenRefine/extensions/pc-axis/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.gen.c8.call(file:/Users/researcher/Library/Application%20Support/OpenRefine/extensions/pc-axis/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:296)
	at com.google.refine.RefineServer.init(Refine.java:208)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)
Caused by: java.lang.ClassNotFoundException: com.google.refine.ProjectMetadata
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

```

**Comment by ettorerizza** [comment]
Any idea what the problem is, everyone?

**Comment by wetneb** [comment]
That seems to be caused by an extension that was compiled for a previous version - the `com.google.refine.ProjectMetadata` class has been renamed to `com.google.refine.model.metadata.ProjectMetadata` in the data package PR.

**Comment by anchardo** [comment]
Thank you for your help @ettorerizza and @wetneb. I have completely removed my extension folder (I'll reinstall only the last version of the ones I actually use) and the 3rd version is finally working on my computer, thank you very much!
