### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'sdfasdfas'

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1879]
**Describe the bug**

**To Reproduce**
1. 'refine clean'
2. 'refine test'

**Current Results**
```
<snip>
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ main ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 236 source files to C:\Users\THAD\OpenRefine\main\target\test-classes
[WARNING] /C:/Users/THAD/OpenRefine/main/tests/server/src/com/google/refine/tests/util/ParsingUtilitiesTests.java: C:\Users\THAD\OpenRefine\main\tests\server\src\com\google\refine\tests\util\ParsingUtilitiesTests.java uses or overrides a deprecated API.
[WARNING] /C:/Users/THAD/OpenRefine/main/tests/server/src/com/google/refine/tests/util/ParsingUtilitiesTests.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ main ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
21:30:01.514 [       FileProjectManager] Using workspace directory: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir846773483004469207 (0ms)
21:30:01.516 [       FileProjectManager] Loading workspace: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir846773483004469207\workspace.json (2ms)
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'sdfasdfas': was expecting ('true', 'false' or 'null')
 at [Source: (String)"sdfasdfas"; line: 1, column: 19]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:679)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2839)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1891)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
        at com.google.refine.browsing.EngineConfig.reconstruct(EngineConfig.java:44)
        at com.google.refine.commands.Command.getEngineConfig(Command.java:124)
        at com.google.refine.tests.commands.CommandStub.wrapGetEngineConfig(CommandStub.java:56)
        at com.google.refine.tests.commands.CommandTests.getEngineConfigReturnsNullWithEmptyOrBadParameterValue(CommandTests.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at org.testng.TestRunner.privateRun(TestRunner.java:782)
        at org.testng.TestRunner.run(TestRunner.java:632)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
        at org.testng.SuiteRunner.run(SuiteRunner.java:268)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
        at org.testng.TestNG.run(TestNG.java:1064)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
21:30:01.761 [       FileProjectManager] Overwriting singleton already set: com.google.refine.tests.ProjectManagerStub@5f462e3b (245ms)
21:30:01.761 [       FileProjectManager] Using workspace directory: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir4080386103041503738 (0ms)
21:30:01.761 [       FileProjectManager] Loading workspace: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir4080386103041503738\workspace.json (0ms)
21:30:02.046 [..XmlImportUtilitiesTests] hello; world; foo; bar;  (285ms)
21:30:02.065 [..XmlImportUtilitiesTests] 1; Author 1, The; Book title 1; 2010-05-26;  (19ms)
21:30:02.065 [..XmlImportUtilitiesTests] 2; Author 2, The; Book title 2; 2010-05-26;  (0ms)
21:30:02.065 [..XmlImportUtilitiesTests] 3; Author 3, The; Book title 3; 2010-05-26;  (0ms)
21:30:02.065 [..XmlImportUtilitiesTests] 4; Author 4, The; Book title 4; 2010-05-26;  (0ms)
21:30:02.065 [..XmlImportUtilitiesTests] 5; Author 5, The; Book title 5; 2010-05-26;  (0ms)
21:30:02.065 [..XmlImportUtilitiesTests] 6; Author 6, The; Book title 6; 2010-05-26;  (0ms)
21:30:02.069 [..XmlImportUtilitiesTests] 1; Author 1, The; Book title 1; 2010-05-26;  (4ms)
21:30:02.069 [..XmlImportUtilitiesTests] 2; Author 2, The; Book title 2; 2010-05-26;  (0ms)
21:30:02.069 [..XmlImportUtilitiesTests] 3; Author 3, The; Book title 3; 2010-05-26;  (0ms)
21:30:02.069 [..XmlImportUtilitiesTests] 4; Author 4, The; Book title 4; 2010-05-26;  (0ms)
21:30:02.069 [..XmlImportUtilitiesTests] 5; Author 5, The; Book title 5; 2010-05-26;  (0ms)
21:30:02.069 [..XmlImportUtilitiesTests] 6; Author 6, The; Book title 6; 2010-05-26;  (0ms)
21:30:02.072 [..XmlImportUtilitiesTests] 1; Author 1, The; Book title 1; 2010-05-26;  (3ms)
21:30:02.072 [..XmlImportUtilitiesTests] 2; Author 2, The; Book title 2; 2010-05-26;  (0ms)
21:30:02.072 [..XmlImportUtilitiesTests] 3; Author 3, The; Book title 3; 2010-05-26;  (0ms)
21:30:02.072 [..XmlImportUtilitiesTests] 4; Author 4, The; Book title 4; 2010-05-26;  (0ms)
21:30:02.072 [..XmlImportUtilitiesTests] 5; Author 5, The; Book title 5; 2010-05-26;  (0ms)
21:30:02.072 [..XmlImportUtilitiesTests] 6; Author 6, The; Book title 6; 2010-05-26; New element not seen in other records;  (0ms)
21:30:02.074 [..XmlImportUtilitiesTests] 1; author1; genre1;  (2ms)
21:30:02.074 [..XmlImportUtilitiesTests] null; author2;  (0ms)
21:30:02.078 [..XmlImportUtilitiesTests] 1; author1; a date; genre1;  (4ms)
21:30:02.079 [..XmlImportUtilitiesTests] 1; author1; genre1;  (1ms)
21:30:02.082 [       FileProjectManager] Loading workspace: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir332767041773336447\workspace.json (3ms)
21:30:02.083 [       FileProjectManager] java.io.FileNotFoundException: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir332767041773336447\workspace.json (The system cannot find the file specified) (1ms)
21:30:02.083 [       FileProjectManager] Loading workspace: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir332767041773336447\workspace.temp.json (0ms)
21:30:02.083 [       FileProjectManager] java.io.FileNotFoundException: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir332767041773336447\workspace.temp.json (The system cannot find the file specified) (0ms)
21:30:02.083 [       FileProjectManager] Loading workspace: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir332767041773336447\workspace.old.json (0ms)
21:30:02.083 [       FileProjectManager] java.io.FileNotFoundException: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir332767041773336447\workspace.old.json (The system cannot find the file specified) (0ms)
21:30:02.084 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (1ms)
[class com.google.refine.model.recon.StandardReconConfig, class com.google.refine.model.recon.StandardReconConfig, class com.google.refine.model.recon.StandardReconConfig]
[class com.google.refine.model.recon.StandardReconConfig, class com.google.refine.model.recon.StandardReconConfig, class com.google.refine.model.recon.StandardReconConfig, class com.google.refine.model.recon.StandardReconConfig]
21:30:42.321 [           ProjectManager] Saving all modified projects ... (40237ms)
21:30:42.323 [           ProjectManager] Saving some modified projects ... (2ms)
21:30:42.359 [       FileProjectManager] Overwriting singleton already set: com.google.refine.tests.ProjectManagerStub@4d266391 (36ms)
21:30:42.359 [       FileProjectManager] Using workspace directory: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir7418908784611276322 (0ms)
21:30:42.359 [       FileProjectManager] Loading workspace: C:\Users\THAD\AppData\Local\Temp\openrefine-test-workspace-dir7418908784611276322\workspace.json (0ms)
21:30:42.391 [..rters.JsonImporterTests] _ - id; _ - title; _ - author; _ - publish_date;  (32ms)
21:30:42.391 [..rters.JsonImporterTests] 1; Author 1, The; Book title 1; 2010-05-26;  (0ms)
21:30:42.391 [..rters.JsonImporterTests] 2; Author 2, The; Book title 2; 2010-05-26;  (0ms)
21:30:42.391 [..rters.JsonImporterTests] 3; Author 3, The; Book title 3; 2010-05-26;  (0ms)
</snip>
```

**Expected behavior**
Passing all tests.
But seems like a Json parse error during EngineConfig ?
https://github.com/OpenRefine/OpenRefine/blame/master/main/tests/server/src/com/google/refine/tests/commands/CommandTests.java#L138

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - JRE or JDK Version: JDK 1.8.0_181

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.1 [Trunk]

**Comment by wetneb** [comment]
@thadguidry yes, this test does just that: checking the behaviour of this method when the engine config is not a valid JSON object. So the test passes as expected, and the exception is printed. There are various other tests that check the behavior of methods with invalid inputs and they also log errors so I think this is fine.
