### ISSUE TITLE
Exception when performing edits on Wikidata: "Multiple terms provided for the same language"

### ISSUE THREAD

**Issue by davidabian** [OpenRefine/OpenRefine#1917]
**Describe the bug**
After some successfully performed edits on Wikidata, the following exception raises and breaks the editing process.
```
Exception in thread "Thread-11" java.lang.IllegalArgumentException: Multiple terms provided for the same language.
	at org.wikidata.wdtk.datamodel.implementation.TermedStatementDocumentImpl.constructTermMap(TermedStatementDocumentImpl.java:389)
	at org.wikidata.wdtk.datamodel.implementation.TermedStatementDocumentImpl.<init>(TermedStatementDocumentImpl.java:157)
	at org.wikidata.wdtk.datamodel.implementation.ItemDocumentImpl.<init>(ItemDocumentImpl.java:96)
	at org.wikidata.wdtk.datamodel.implementation.DataObjectFactoryImpl.getItemDocument(DataObjectFactoryImpl.java:277)
	at org.wikidata.wdtk.datamodel.helpers.Datamodel.makeItemDocument(Datamodel.java:629)
	at org.wikidata.wdtk.datamodel.helpers.Datamodel.makeItemDocument(Datamodel.java:595)
	at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:134)
	at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:211)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. 

**Current Results**
On the web interface the message "Peform [sic] edits on Wikidata // 51% complete" remains, as if the process continued, but the process has actually stopped and no more changes are uploaded to Wikidata.

**Expected behavior**
The problem ("Multiple terms provided for the same language") should be detected and handled **before the editing process starts**.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows 10, Linux, Ubuntu 18.04]
 - Browser Version: [e.g. Chrome 19, Firefox 61, Safari, NOTE: OpenRefine does not support IE but works OK in most cases]
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - OpenRefine 3.1

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by wetneb** [comment]
Oops! That is annoying. Thanks a lot for the report, I will investigate.

**Comment by davidabian** [comment]
Thanks! :D
