### ISSUE TITLE
Version 3.1 not starting due to Exception

### ISSUE THREAD

**Issue by rogargon** [OpenRefine/OpenRefine#1939]
**Describe the bug**
Not starting due to Exception java.lang.LinkageError

**To Reproduce**
- Cloned source
- Checked out tag 3.1
- Built and executed using ./refine

**Current Results**
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -cp server/classes:server/target/lib/*   -Xms1400M -Xmx1400M -Drefine.memory=1400M -Drefine.max_form_content_size=1048576 -Drefine.verbosity=info -Dpython.path=main/webapp/WEB-INF/lib/jython -Dpython.cachedir=/Users/roberto/.local/share/google/refine/cachedir -Drefine.autoreload=true -Dbutterfly.autoreload=true -Xdock:icon=graphics/icon/openrefine.icns -Drefine.webapp=main/webapp -Drefine.port=3333 -Drefine.host=127.0.0.1 com.google.refine.Refine
Starting OpenRefine at 'http://127.0.0.1:3333/'

17:28:04.685 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
17:28:04.687 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (2ms)
17:28:04.696 [            refine_server] Initializing context: '/' from '/Users/roberto/Downloads/OpenRefine/main/webapp' (9ms)
17:28:04.750 [            refine_server] Starting autoreloading scanner...  (54ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/roberto/Downloads/OpenRefine/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/roberto/Downloads/OpenRefine/main/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
17:28:05.315 [                   refine] Starting OpenRefine 3.1 [b90e413]... (565ms)
17:28:05.315 [                   refine] initializing FileProjectManager with dir (0ms)
17:28:05.315 [                   refine] /Users/roberto/Library/Application Support/OpenRefine (0ms)
17:28:06.343 [       database-extension] Initializing OpenRefine Database... (1028ms)
17:28:06.347 [       database-extension] Database Extension Mount point /extension/database/ [*] (4ms)
17:28:06.347 [       database-extension] Registering Database Extension Commands...... (0ms)
17:28:06.359 [       database-extension] Database Extension Command Registeration done!! (12ms)
17:28:06.359 [       database-extension] Database Operations Registered successfully... (0ms)
17:28:06.359 [       database-extension] Database Functions Registered successfully... (0ms)
Exception in thread "main" java.lang.LinkageError: loader constraint violation: loader (instance of edu/mit/simile/butterfly/ButterflyClassLoader) previously initiated loading for a different type with name "org/slf4j/Logger"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.refine.extension.database.DatabaseModuleImpl.readModuleProperty(DatabaseModuleImpl.java:93)
	at com.google.refine.extension.database.DatabaseModuleImpl.init(DatabaseModuleImpl.java:68)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - JRE or JDK Version: java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.1

**Comment by wetneb** [comment]
@rogargon interesting! And does the released `.dmg` work for you?

**Comment by rogargon** [comment]
No, I tried first with the `.dmg` but it does not start property and if I go to localhost:3333 the only message is something like "Butterfly still starting..."

**Comment by rogargon** [comment]
Solved for version 3.1 by renaming the user folder that was kept from a previous install some time ago. For Mac the folder renamed so 3.1 can recreate it is: `~/Library/Application Support/OpenRefine`
So no way to reuse old projects

**Comment by ostephens** [comment]
@rogargon if you copy an old project file across from the renamed folder, does that project show up OK in your new install, or does that break the installation again?

Also - which version were you upgrading from?

**Comment by rogargon** [comment]
It works. It seems the problem was with a previous version of the RDF Extensions that was messing it all. Now I'm able to load the old projects with the latest versions of Open Refine and the RDF Extension

**Comment by keski** [comment]
Although this issue is already closed, I thought I'd add a comment. I couldn't start `OpenRefine` but simply removed the old `~/Library/Application Support/OpenRefine` and had `OpenRefine` recreate it. Simple approach for those who simply want to start from a clean slate.
