### ISSUE TITLE
Cannot open Excel file in Openrefine 3.2-beta

### ISSUE THREAD

**Issue by fpompermaier** [OpenRefine/OpenRefine#1981]
The following file cannot be opened in Openrefine 3.2-beta (on Windows 10 and Java 1.8).

The error I get is the following:

```
java.lang.NoSuchMethodError: org.apache.poi.util.POILogger.log(ILjava/lang/Object;)V
        at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.parseRelationshipsPart(PackageRelationshipCollection.java:304)
        at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:156)
        at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:124)
        at org.apache.poi.openxml4j.opc.PackagePart.loadRelationships(PackagePart.java:559)
        at org.apache.poi.openxml4j.opc.PackagePart.<init>(PackagePart.java:112)
        at org.apache.poi.openxml4j.opc.PackagePart.<init>(PackagePart.java:83)
        at org.apache.poi.openxml4j.opc.PackagePart.<init>(PackagePart.java:128)
        at org.apache.poi.openxml4j.opc.ZipPackagePart.<init>(ZipPackagePart.java:78)
        at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:188)
        at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:623)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:230)
        at org.apache.poi.util.PackageHelper.open(PackageHelper.java:39)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:187)
        at com.google.refine.importers.ExcelImporter.createParserUIInitializationData(ExcelImporter.java:98)
        at com.google.refine.importing.DefaultImportingController.doInitializeParserUI(DefaultImportingController.java:215)
        at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:90)
        at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:62)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

```
[ordine.xlsx](https://github.com/OpenRefine/OpenRefine/files/2954388/ordine.xlsx)

**Comment by fpompermaier** [comment]
Yes it is

**Comment by wetneb** [comment]
Yes I checked and it is new.

**Comment by orr721** [comment]
can confirm, works in 3.1, doesn't work in 3.2 beta
