### ISSUE TITLE
Windows version only works with Java 8 installed

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2069]
It is reported by users that running OpenRefine 3.1 on Windows only works if Java 8 is installed.

This is probably related to the way Launch4J searches for the Java Runtime Environment: it relies on registry keys, which are no longer used by recent releases of Java:
https://sourceforge.net/p/launch4j/feature-requests/127/?page=0

The maintainer of Launch4J encourages to ship a bundled JRE in the releases. We already do that for Mac OS, we could consider doing that for Windows too.

**Comment by akuckartz** [comment]
> ... to ship a bundled JRE in the release

:-1:

**Comment by wetneb** [comment]
@akuckartz, if you have any other solution to propose, feel free to chime in!

The problem will hopefully be solved by the upcoming release of launch4j, but in the meantime I am not aware of any other solution.

**Comment by thadguidry** [comment]
It is also because of the Jython extenstion failing during load as I documented here: https://github.com/OpenRefine/OpenRefine/wiki/FAQ#warning-about-pythonjython-illegal-reflective-access-operation-has-occurred

and #1741 

after going back to Java 1.8 correctly...where the build was compiling and OpenRefine ran successfully... instead I now get the following error when starting OpenRefine from command line after a clean build:

```
HTTP ERROR 500
Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module wikidata [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.EvaluatorException: Can't find method com.google.refine.RefineServlet.cacheClass(object). (file:/C:/Users/THAD/OpenRefine/main/webapp/../../extensions/wikidata/module/MOD-INF/controller.js#16)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:998)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1053)
	at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:1016)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:144)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_THAD_OpenRefine_main_webapp_______extensions_wikidata_module_MOD_INF_controller_js_16._c_init_1(file:/C:/Users/THAD/OpenRefine/main/webapp/../../extensions/wikidata/module/MOD-INF/controller.js:16)
	at org.mozilla.javascript.gen.file__C__Users_THAD_OpenRefine_main_webapp_______extensions_wikidata_module_MOD_INF_controller_js_16.call(file:/C:/Users/THAD/OpenRefine/main/webapp/../../extensions/wikidata/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_THAD_OpenRefine_main_webapp_______extensions_wikidata_module_MOD_INF_controller_js_16.call(file:/C:/Users/THAD/OpenRefine/main/webapp/../../extensions/wikidata/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
```

**Comment by wetneb** [comment]
@akuckartz @thadguidry , could you please check if this packaged version works with various versions of Java on Windows?
http://pintoch.ulminfo.fr/aaa8156eae/openrefine-win-3.2-SNAPSHOT.zip
