### ISSUE TITLE
Exception when logging expressions

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2086]
**Describe the bug**

```
17:33:49.314 [                   refine] POST /command/core/preview-expression (1280ms)
17:33:53.149 [                   refine] POST /command/core/log-expression (3835ms)
17:33:53.149 [                  command] Exception caught (0ms)
java.lang.NullPointerException
	at com.google.refine.commands.expr.LogExpressionCommand.doPost(LogExpressionCommand.java:56)
	at com.google.refine.RefineServlet.service(RefineServlet.java:189)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

This happens when creating a new column or new facet from an expression.

**OpenRefine (please complete the following information):**
 - master branch

**Comment by wetneb** [comment]
That seems to be caused by a `"scripting.expressions": null` in my `workspace.json`, probably due to some fiddling with serialization earlier. Just in case this happens in real usage scenarios, this is worth fixing.

**Comment by thadguidry** [comment]
would like to be clear here.. is this a pre 3.1 beta issue ?  what versions of OpenRefine does this possibly affect...just so we get that noted here.

**Comment by wetneb** [comment]
As mentioned above this is happening on the master branch at the moment, so post 3.1 beta.
