### ISSUE TITLE
Broken startup on Windows on master branch

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2091]
**Describe the bug**
clean clone from master branch and starting OpenRefine's refine .bat file on Windows 10 causes Butterfly error.

**To Reproduce**
1. git clone
2. refine build
3. refine.bat
4. See the error

**Current Results**

**On browser:**

HTTP ERROR 500
Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module wikidata [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.EvaluatorException: Can't find method com.google.refine.RefineServlet.cacheClass(object). (file:/C:/Users/THAD/OpenRefine/main/webapp/../../extensions/wikidata/module/MOD-INF/controller.js#16)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:998)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1053)
	at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:1016)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:144)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_THAD_OpenRefine_main_webapp_______extensions_wikidata_module_MOD_INF_controller_js_16._c_init_1(file:/C:/Users/THAD/OpenRefine/main/webapp/../../extensions/wikidata/module/MOD-INF/controller.js:16)
	at org.mozilla.javascript.gen.file__C__Users_THAD_OpenRefine_main_webapp_______extensions_wikidata_module_MOD_INF_controller_js_16.call(file:/C:/Users/THAD/OpenRefine/main/webapp/../../extensions/wikidata/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_THAD_OpenRefine_main_webapp_______extensions_wikidata_module_MOD_INF_controller_js_16.call(file:/C:/Users/THAD/OpenRefine/main/webapp/../../extensions/wikidata/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more

**on console:**

```shell
C:\Users\THAD\OpenRefine>"C:\Program Files\Java\jdk1.8.0_191\bin\java.exe" -cp "server\classes;server\target\lib\*"   -Xms1400M -Xmx1400M -Drefine.memory=1400M -Drefine.max_form_content_size=1048576 -Drefine.port=3333 -Drefine.host=127.0.0.1 -Drefine.webapp=main\webapp -Djava.library.path=server\target\lib\native\windows com.google.refine.Refine
09:03:56.466 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
09:03:56.466 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (0ms)
09:03:56.473 [            refine_server] Initializing context: '/' from 'C:\Users\THAD\OpenRefine\main\webapp' (7ms)
09:03:56.836 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (363ms)
09:03:56.837 [            refine_server] Creating new workspace directory C:\Users\THAD\AppData\Roaming\OpenRefine (1ms)
09:03:56.838 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (1ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/THAD/OpenRefine/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/THAD/OpenRefine/main/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
09:03:56.955 [                   refine] Starting OpenRefine 3.2-beta [6616d01]... (117ms)
09:03:56.955 [                   refine] initializing FileProjectManager with dir (0ms)
09:03:56.956 [                   refine] C:\Users\THAD\AppData\Roaming\OpenRefine (1ms)
09:03:56.960 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (4ms)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: jdk1.8.0_191

**OpenRefine (please complete the following information):**
 - Version:  OpenRefine 3.2-Beta from master

**Comment by wetneb** [comment]
Can you double-check the clone is really clean with `refine.bat clean` and compile again?

Can you try checking out the 3.2-beta tag (`git checkout 3.2-beta`), `refine.bat clean` and `refine.bat build` and `refine.bat`?

Is the 3.2-beta compiled version (available at https://github.com/OpenRefine/OpenRefine/releases/download/3.2-beta/openrefine-win-3.2-beta.zip) working for you?

**Comment by thadguidry** [comment]
​A brand new fresh clone into a different directory fixed it.  Stupid git indexing , when will they ever fix that !
I even did a `git reset --hard @{u}` and it still didn't update all the necessary files that it should have.  This might be a Windows Git bug lurking I'm sure.  That `git reset` command has always worked for me in the past, and even helped @ostephens get unstuck once before as well when I told him to do that same thing.  For some reason, its not working out so well in my case.  Oh well, the fresh new clone did the trick however!

Thanks @wetneb !​
