### ISSUE TITLE
Null pointer exception when deleting Preferences row

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2093]
**Describe the bug**
java.lang.NullPointerException is thrown when adding a key/value pair in Preferences and then clicking the Delete button.

**To Reproduce**
1. Clink on 'Preferences'
2. Click Add
3. Enter key/value pair such as "aaa" :  "bbb"
4. Notice the key/value is now added as a new row in Preferences.
5. Click on Delete button on key/value row added.
6. Notice java stack trace is thrown in console/terminal.

**Current Results**

```
C:\Users\THAD\OpenRefine>"C:\Program Files\Java\jdk1.8.0_191\bin\java.exe" -cp "server\classes;server\target\lib\*"  -Drefine.data_dir=E:\Downloads\OpenRefine_Workspace\OpenRefine -Xms1400M -Xmx1400M -Drefine.memory=1400M -Drefine.max_form_content_size=1048576 -Drefine.port=3333 -Drefine.host=127.0.0.1 -Drefine.webapp=main\webapp -Djava.library.path=server\target\lib/native/windows com.google.refine.Refine
13:23:18.901 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
13:23:18.902 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (1ms)
13:23:18.909 [            refine_server] Initializing context: '/' from 'C:\Users\THAD\OpenRefine\main\webapp' (7ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/THAD/OpenRefine/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/THAD/OpenRefine/main/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
13:23:19.389 [                   refine] Starting OpenRefine 3.2-beta [6616d01]... (480ms)
13:23:19.389 [                   refine] initializing FileProjectManager with dir (0ms)
13:23:19.390 [                   refine] E:\Downloads\OpenRefine_Workspace\OpenRefine (1ms)
13:23:19.693 [       FileProjectManager] com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0x97
 at [Source: (File); line: 1, column: 3171] (through reference chain: com.google.refine.io.FileProjectManager["preferences"]->com.google.refine.preference.PreferenceStore["entries"]) (303ms)
13:23:19.693 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (0ms)
13:23:24.699 [                   refine] POST /command/core/load-language (5006ms)
13:23:24.716 [                   refine] GET /command/core/get-preference (17ms)
13:23:24.727 [                   refine] POST /command/core/load-language (11ms)
13:23:24.732 [                   refine] POST /command/core/load-language (5ms)
13:23:24.789 [                   refine] POST /command/core/get-importing-configuration (57ms)
13:23:24.804 [                   refine] GET /command/core/get-all-project-tags (15ms)
13:23:24.833 [                   refine] GET /command/core/get-all-project-metadata (29ms)
13:23:24.978 [                   refine] GET /command/core/get-languages (145ms)
13:23:25.003 [                   refine] GET /command/core/get-version (25ms)
13:23:25.102 [                   refine] GET /command/database/saved-connection (99ms)
13:23:25.177 [                   refine] POST /command/core/set-preference (75ms)
13:23:25.182 [                   refine] POST /command/core/set-preference (5ms)
13:23:34.012 [                   refine] POST /command/core/load-language (8830ms)
13:23:34.027 [                   refine] POST /command/core/get-all-preferences (15ms)
13:23:53.993 [                   refine] POST /command/core/set-preference (19966ms)
13:23:59.243 [                   refine] POST /command/core/set-preference (5250ms)
java.lang.NullPointerException
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2750)
        at com.google.refine.preference.PreferenceStore.loadObject(PreferenceStore.java:123)
        at com.google.refine.commands.SetPreferenceCommand.doPost(SetPreferenceCommand.java:64)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
Ability to delete a Preferences row without a NullPointerException thrown.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK 1.8.0_181

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.2-Beta from master branch

**Additional context**
Not applicable to this issue, but notice also Invalid UTF-8 start byte from Jackson, which might need tidying up at some point.
```
13:23:19.693 [       FileProjectManager] com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0x97
 at [Source: (File); line: 1, column: 3171] (through reference chain: com.google.refine.io.FileProjectManager["preferences"]->com.google.refine.preference.PreferenceStore["entries"]) (303ms)
```

**Comment by wetneb** [comment]
Marking as a good first issue, although I have not reproduced it myself. The first step would therefore be to try to reproduce it, and if that fails, we can close it.

**Comment by elroykanye** [comment]
I tried to reproduce this issue, but did not get any NullPointerException or related Exceptions/Errors in the process.
I tried this with FireFox, Chrome and Edge and Chrome on Kali Linux 2021 1b and preferences get deleted perfectly with various samples.

**Comment by thadguidry** [comment]
I also tried and cannot reproduce any longer.  I think this issue was created before I knew what was really happening later on and when we later had various serialization issues opened such as issue #2543 but we still might have a few lurking such as #4083 on our 4.0 branch, which we'll eventually resolve.

We can close this specific issue now since I also just verified with 3.5.2 with Java, so closing.
One issue that I would love to see put to rest and maybe @elroykanye you can see if you can reproduce or not would be #3432
