### ISSUE TITLE
HTTP 500 error on QuickStatements export

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2143]
QuickStatement export can fails for an unclear reason:
```
HTTP ERROR 500

Problem accessing /command/core/export-rows/statements.txt. Reason:

    INTERNAL_SERVER_ERROR

Caused by:

java.lang.UnsupportedOperationException
        at com.google.refine.commands.Command.doGet(Command.java:85)
        at com.google.refine.RefineServlet.service(RefineServlet.java:182)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Powered by Jetty://
```

**Comment by thadguidry** [comment]
I get something similar when performing Recon with identifiers as described in #2609

**Comment by tfmorris** [comment]
This was also reported by a user on Gitter:

>  I installed openrefine on Arch from AUR. I choose jre11. I get an internal server error 500 for every kind of export.

who said in a followup that the stack trace matched the one in this bug report.

Note that  `com.google.refine.commands.Command` is an abstract class with a default implementation for the `doGet()` method of:

```
public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {

        throw new UnsupportedOperationException();
    };
```

This may be some kind of classpath / class loader weirdness
