### ISSUE TITLE
NoSuchMethodError: com.google.refine.operations.cell.TextTransformOperation

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2145]
**Describe the bug**
Java error while performing Text Transform on a column

**To Reproduce**
1. Import Project attached to this issue Dataset.
2. On column "year", apply text transform  `value.partition(">")[2]`
4. See error in Current Results.

**Current Results**
```
C:\Users\THAD\OpenRefine>(
echo -----------------------
 echo PROCESSOR_ARCHITECTURE = AMD64
 echo JAVA_HOME = C:\Program Files\Java\jdk-12.0.1
 echo java -version = java version "1.8.0_221"
 echo freeRam = 10183M
 echo REFINE_MEMORY = 1400M
 echo -----------------------
) 1>support.log

C:\Users\THAD\OpenRefine>set CLASSPATH="server\classes;server\target\lib\*"

C:\Users\THAD\OpenRefine>"C:\Program Files\Java\jdk-12.0.1\bin\java.exe" -cp "server\classes;server\target\lib\*"   -Xms1400M -Xmx1400M -Drefine.memory=1400M -Drefine.max_form_content_size=1048576 -Drefine.port=3333 -Drefine.host=127.0.0.1 -Drefine.webapp=main\webapp -Djava.library.path=server\target\lib/native/windows com.google.refine.Refine
10:13:18.496 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
10:13:18.497 [            refine_server] refine.memory size: 1400M JVM Max heap: 1468006400 (1ms)
10:13:18.512 [            refine_server] Initializing context: '/' from 'C:\Users\THAD\OpenRefine\main\webapp' (15ms)
10:13:24.854 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (6342ms)
10:13:24.857 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (3ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/THAD/OpenRefine/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/THAD/OpenRefine/main/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
10:13:24.992 [                   refine] Starting OpenRefine 3.3 [9d72de1]... (135ms)
10:13:24.992 [                   refine] initializing FileProjectManager with dir (0ms)
10:13:24.993 [                   refine] C:\Users\THAD\AppData\Roaming\OpenRefine (1ms)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/C:/Users/THAD/OpenRefine/main/webapp/../../extensions/jython/module/MOD-INF/lib/jython-standalone-2.7.1.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:13:35.702 [                   refine] POST /command/core/load-language (10709ms)
10:13:35.722 [                   refine] GET /command/core/get-preference (20ms)

[snip]

12:46:41.524 [                   refine] POST /command/core/preview-expression (485ms)
12:46:52.925 [                   refine] POST /command/core/log-expression (11401ms)
12:46:52.926 [                   refine] POST /command/core/text-transform (1ms)
12:46:52.932 [          org.mortbay.log] Error for /command/core/text-transform (6ms)
java.lang.NoSuchMethodError: com.google.refine.operations.cell.TextTransformOperation.access$0(Lcom/google/refine/operations/cell/TextTransformOperation;)Ljava/lang/String;
        at com.google.refine.operations.cell.TextTransformOperation$1.visit(TextTransformOperation.java:158)
        at com.google.refine.browsing.util.ConjunctiveFilteredRows.visitRow(ConjunctiveFilteredRows.java:76)
        at com.google.refine.browsing.util.ConjunctiveFilteredRows.accept(ConjunctiveFilteredRows.java:65)
        at com.google.refine.operations.EngineDependentMassCellOperation.createHistoryEntry(EngineDependentMassCellOperation.java:78)
        at com.google.refine.model.AbstractOperation$1.createHistoryEntry(AbstractOperation.java:63)
        at com.google.refine.process.QuickHistoryEntryProcess.performImmediate(QuickHistoryEntryProcess.java:70)
        at com.google.refine.process.ProcessManager.queueProcess(ProcessManager.java:80)
        at com.google.refine.commands.Command.performProcessAndRespond(Command.java:236)
        at com.google.refine.commands.EngineDependentCommand.doPost(EngineDependentCommand.java:80)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

**Expected behavior**
Transform should have completed without an error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: jdk-12.0.1
**OpenRefine (please complete the following information):**
 - Version:  Trunk (clean build)

**Datasets**
[Batchelder-Award-Winners.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/3562694/Batchelder-Award-Winners.openrefine.tar.gz)

**Additional context**
hmm ... Java 12 confusion perhaps ?

**Comment by thadguidry** [comment]
@wetneb confirmed... this was a issue using JDK 12... I tried with Open JDK 9 and it works fine.

**Comment by wetneb** [comment]
I cannot reproduce this, neither with OpenJDK 12 nor OpenJDK 8… Can anyone reproduce this?

**Comment by thadguidry** [comment]
I can no longer reproduce as well.  Closing.
(hopefully it was just a short-lived bug on master around that time...or just my environment code not fully reset to pure trunk)
