### ISSUE TITLE
Wikidata edit batch scheduling error

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2205]
**Describe the bug**
When uploading edits to Wikidata:

```
15:08:57.879 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 12 milliseconds. (33328ms)
Exception in thread "Thread-15" java.lang.IllegalArgumentException: Trying to rewrite an update where a new item was not created yet.
        at org.openrefine.wikidata.editing.ReconEntityRewriter.copy(ReconEntityRewriter.java:82)
        at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.visit(DatamodelConverter.java:570)
        at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.visit(DatamodelConverter.java:47)
        at org.openrefine.wikidata.schema.entityvalues.ReconEntityIdValue.accept(ReconEntityIdValue.java:151)
        at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.copyValue(DatamodelConverter.java:564)
        at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.copy(DatamodelConverter.java:381)
        at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.copy(DatamodelConverter.java:362)
        at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.copy(DatamodelConverter.java:456)
        at org.openrefine.wikidata.editing.ReconEntityRewriter.lambda$rewrite$5(ReconEntityRewriter.java:99)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.openrefine.wikidata.editing.ReconEntityRewriter.rewrite(ReconEntityRewriter.java:100)
        at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:131)
        at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:192)
        at java.lang.Thread.run(Thread.java:748)
```

That means there must be a problem with the scheduler. Dammit!

**Comment by nemobis** [comment]
The project was
[Society-Publishers-with-Open-Access-Journals-csv.openrefine(2).tar.gz](https://github.com/OpenRefine/OpenRefine/files/3801820/Society-Publishers-with-Open-Access-Journals-csv.openrefine.2.tar.gz)

**Comment by nemobis** [comment]
I've tried master and now if it fails and I try to re-run I get into an infinite loop of 
```
13:26:00.993 [..ting.EditBatchProcessor] Failed to rewrite update on entity new item (reconciled from 1573136306606095545). Missing entity: new item (reconciled from 1573470578006906140). Skipping update. (0ms)
```

Did I do something wrong?

**Comment by wetneb** [comment]
Argh! No it's my "fix" which is obviously flawed. Could you export and share your project again?

**Comment by nemobis** [comment]
Antonin Delpeuch, 11/11/19 13:34:
> Argh! No it's my "fix" which is obviously flawed. Could you export and share your project again?

Yes but I made some more edits in the meanwhile.
