### ISSUE TITLE
Error exporting a project in XLSX

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2213]
**Describe the bug**
In OR 3.3 beta, I got a java error message when I tried to export a project into XLSX

**To Reproduce**

**Current Results**

Here is the error message

HTTP ERROR 500

Problem accessing /command/core/export-rows/get_q_any_contains.xlsx. Reason:

    Address of hyperlink must be a valid URI

Caused by:

```
java.lang.IllegalArgumentException: Address of hyperlink must be a valid URI
	at org.apache.poi.xssf.usermodel.XSSFHyperlink.validate(XSSFHyperlink.java:264)
	at org.apache.poi.xssf.usermodel.XSSFHyperlink.setAddress(XSSFHyperlink.java:245)
	at com.google.refine.exporters.XlsExporter$1.addRow(XlsExporter.java:132)
	at com.google.refine.exporters.CustomizableTabularExporterUtilities$1.visit(CustomizableTabularExporterUtilities.java:168)
	at com.google.refine.browsing.util.RowVisitorAsRecordVisitor.visit(RowVisitorAsRecordVisitor.java:61)
	at com.google.refine.browsing.util.ConjunctiveFilteredRecords.accept(ConjunctiveFilteredRecords.java:64)
	at com.google.refine.browsing.util.FilteredRecordsAsFilteredRows.accept(FilteredRecordsAsFilteredRows.java:50)
	at com.google.refine.exporters.CustomizableTabularExporterUtilities.exportRows(CustomizableTabularExporterUtilities.java:182)
	at com.google.refine.exporters.XlsExporter.export(XlsExporter.java:140)
	at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:119)
	at com.google.refine.RefineServlet.service(RefineServlet.java:189)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in query at index 81: http://catalogue.unice.fr/primo-explore/fulldisplay?docid=sc_aleph_uns01000411732 any,contains,comptabilité générale zoom
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.poi.xssf.usermodel.XSSFHyperlink.validate(XSSFHyperlink.java:262)
	... 32 more

Caused by:

java.net.URISyntaxException: Illegal character in query at index 81: http://catalogue.unice.fr/primo-explore/fulldisplay?docid=sc_aleph_uns01000411732 any,contains,comptabilité générale zoom
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.poi.xssf.usermodel.XSSFHyperlink.validate(XSSFHyperlink.java:262)
	at org.apache.poi.xssf.usermodel.XSSFHyperlink.setAddress(XSSFHyperlink.java:245)
	at com.google.refine.exporters.XlsExporter$1.addRow(XlsExporter.java:132)
	at com.google.refine.exporters.CustomizableTabularExporterUtilities$1.visit(CustomizableTabularExporterUtilities.java:168)
	at com.google.refine.browsing.util.RowVisitorAsRecordVisitor.visit(RowVisitorAsRecordVisitor.java:61)
	at com.google.refine.browsing.util.ConjunctiveFilteredRecords.accept(ConjunctiveFilteredRecords.java:64)
	at com.google.refine.browsing.util.FilteredRecordsAsFilteredRows.accept(FilteredRecordsAsFilteredRows.java:50)
	at com.google.refine.exporters.CustomizableTabularExporterUtilities.exportRows(CustomizableTabularExporterUtilities.java:182)
	at com.google.refine.exporters.XlsExporter.export(XlsExporter.java:140)
	at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:119)
	at com.google.refine.RefineServlet.service(RefineServlet.java:189)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Powered by Jetty://


Here are the logs in Win10 console :

1:27:40.390 [        ExportRowsCommand] error:Address of hyperlink must be a valid URI (8860ms)
11:27:40.397 [          org.mortbay.log] /command/core/export-rows/get_q_any_contains.xlsx (7ms)
java.lang.IllegalArgumentException: Address of hyperlink must be a valid URI
        at org.apache.poi.xssf.usermodel.XSSFHyperlink.validate(XSSFHyperlink.java:264)
        at org.apache.poi.xssf.usermodel.XSSFHyperlink.setAddress(XSSFHyperlink.java:245)
        at com.google.refine.exporters.XlsExporter$1.addRow(XlsExporter.java:132)
        at com.google.refine.exporters.CustomizableTabularExporterUtilities$1.visit(CustomizableTabularExporterUtilities.java:168)
        at com.google.refine.browsing.util.RowVisitorAsRecordVisitor.visit(RowVisitorAsRecordVisitor.java:61)
        at com.google.refine.browsing.util.ConjunctiveFilteredRecords.accept(ConjunctiveFilteredRecords.java:64)
        at com.google.refine.browsing.util.FilteredRecordsAsFilteredRows.accept(FilteredRecordsAsFilteredRows.java:50)
        at com.google.refine.exporters.CustomizableTabularExporterUtilities.exportRows(CustomizableTabularExporterUtilities.java:182)
        at com.google.refine.exporters.XlsExporter.export(XlsExporter.java:140)
        at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:119)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in query at index 81: http://catalogue.unice.fr/primo-explore/fulldisplay?docid=sc_aleph_uns01000411732 any,contains,comptabilitÚ gÚnÚrale zoom
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3111)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at org.apache.poi.xssf.usermodel.XSSFHyperlink.validate(XSSFHyperlink.java:262)
        ... 32 more

```

**Expected behavior**
A clear and concise description of what you expected to happen or to show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Version: Firefox
 - JRE or JDK Version: JRE 1.8.0_201

**OpenRefine (please complete the following information):**
 - Version 3.3 beta

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by msaby** [comment]
My datasets contains server logs. It seems that the export in XSLS is broken by an attempt to handle the links... 
In OR, the column is of type "string", so I want the Excel file to contain plain strings, not parsed URL

**Comment by msaby** [comment]
Maybe linked to that ? https://github.com/OpenRefine/OpenRefine/issues/1696

**Comment by wetneb** [comment]
Seems to be due to a case where UrlValidator thinks the URL is correct, but `new URI(str)` disagrees. It's hard to figure out an example value where this happens without access to the full dataset (but I understand server logs might come with privacy issues).

**Comment by msaby** [comment]
Hi
I tried to reproduce the error with a simpler example but I did not succeed : 

These Excel data

![image](https://user-images.githubusercontent.com/932804/71443797-4db53200-270d-11ea-9241-a442602e5380.png)

were correctly imported in OR

![image](https://user-images.githubusercontent.com/932804/71443821-72110e80-270d-11ea-9aea-45a01aea7eae.png)

So I cannot tell what broke the import in the 1st place but if you think your patch fixes the issue I'm fine with it.

But I don't understand why we need to check or convert anything when we import the data : I believe in Excel URL are strings, and in OR URL are strings too, but only "displayed" in a special way, as  clickable URL. So cannot we import them as plain strings?

**Comment by wetneb** [comment]
For export formats which support URLs, such as HTML or XLS(X), I would say it makes sense to use that support if available, no? Typically, #2213 is legitimate.

Perhaps you can argue that XLS(X) support for URLs is bad and we don't want to use it.

But URL detection is done independently of each particular exporter so we do need to have a logic that checks whether strings are valid URLs, and that logic may disagree with any validation logic in the exporters themselves, the libraries they rely on, or even other software that consumes the exported files…

**Comment by msaby** [comment]
(oups, my new comment https://github.com/OpenRefine/OpenRefine/issues/2213#issuecomment-568885661 is wrong, I try to import the file, while the issue was linked to exporting...)

For Excel file format, are you sure that we can say that the data model is really "supporting" URL? If I unzip my file, all the values ("google", "http://google.com"...) are store in xl/sharedStrings.xml. So for me they are just strings (type = 2 in Excel), and not an other kind of object. And in Excel documentation you don't find an "URL" type either : https://docs.microsoft.com/fr-fr/office/vba/language/reference/user-interface-help/data-type-summary

**Comment by msaby** [comment]
Sorry it seems I'm wrong : in \xl\worksheets\_rels\sheet1.xml.rels, I found  

`<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="http://google/" TargetMode="External"/>`

So, anyway, what I want is beeing able to save my data in XLSX format, maybe with an checkbox to choose to try to create hyperlinks in the resultinhg file.

**Comment by wetneb** [comment]
Thanks for the investigation!

It looks like at the moment we have not got any options for XLSX export, so it is probably a bit overkill to add one just for this case. But we can add some more error handling in the XLSX exporter to make sure we fall back on strings when URL export fails.

**Comment by wetneb** [comment]
That being said I suspect the hyperlinks created by the exporter are not actually linked to the cells where they are supposed to appear… so they can be found in the XML files but not from the UI. Let me fix that in #2263 too.

**Comment by msaby** [comment]
Well, I won't be able to test it (I suppose it is necessary to rebuild OR from source?) , so if you need testing of your code, you can ask someone else.

For Excel and ODS : I finally understood that hyperlinks are not a "type" of data, but something that can be added to any value - string, number, date, boolean - or object visible in the sheet.

If the content of a cell in OR IS a string which is a VALID URL, I suppose we can export it as a string with a link to the corresponding URL.

But if the content of a cell only is a string which only contains an URL (like "URL : http://google.com", or the log which broke my export in https://github.com/OpenRefine/OpenRefine/issues/2213#issuecomment-552838022 ), we should export it as a plain string, without any link.

Do you agree with that?

**Comment by wetneb** [comment]
Yes, if the URL is only a part of the string contained in the cell, we should not add any link in the exporter: that is what the current code does.
