### ISSUE TITLE
No Class Def exception - Windows

### ISSUE THREAD

**Issue by BennyRoesler** [OpenRefine/OpenRefine#2218]
**Describe the bug**
When my domain user runs the program, she gets a NoClassDefError exception. I've tried moving the program to root of C, elevating her privileges and running as administrator all which has not solved the issue. When ran under local admin the program runs fine.

**To Reproduce**
1. Unzip clean copy of OpenRefine 3.2
2. Run openrefine.exee

**Current Results**
What results occured or were shown.

`C:\openrefine-3.2>openrefine.exe
12:25:59.979 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
12:25:59.985 [            refine_server] Initializing context: '/' from 'C:\openrefine-3.2\webapp' (6ms)
12:26:00.380 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (395ms)
12:26:00.382 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (2ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/openrefine-3.2/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/openrefine-3.2/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
12:26:00.564 [                   refine] Starting OpenRefine 3.2 [55c921b]... (182ms)
12:26:00.564 [                   refine] initializing FileProjectManager with dir (0ms)
12:26:00.565 [                   refine] C:\Users\hbaer\AppData\Roaming\OpenRefine (1ms)
12:26:01.235 [       FileProjectManager] Failed to recover project in directory 2448776960533.project (670ms)
Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetPublicMethods(Unknown Source)
        at java.lang.Class.getMethods(Unknown Source)
        at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:351)
        at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:302)
        at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:424)
        at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:43)
        at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:812)
        at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:49)
        at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44)
        at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:43)
        at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:39)
        at org.mozilla.javascript.WrapFactory.wrapJavaClass(WrapFactory.java:139)
        at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:135)
        at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:84)
        at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2313)
        at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1579)
        at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1572)
        at org.mozilla.javascript.gen.file__C__Users_hbaer_AppData_Roaming_OpenRefine_extensions_module_MOD_INF_controller_js_10._c_script_0(file:/C:/Users/hbaer/AppData/Roaming/OpenRefine/extensions/module/MOD-INF/controller.js:4)
        at org.mozilla.javascript.gen.file__C__Users_hbaer_AppData_Roaming_OpenRefine_extensions_module_MOD_INF_controller_js_10.call(file:/C:/Users/hbaer/AppData/Roaming/OpenRefine/extensions/module/MOD-INF/controller.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
        at org.mozilla.javascript.gen.file__C__Users_hbaer_AppData_Roaming_OpenRefine_extensions_module_MOD_INF_controller_js_10.call(file:/C:/Users/hbaer/AppData/Roaming/OpenRefine/extensions/module/MOD-INF/controller.js)
        at org.mozilla.javascript.gen.file__C__Users_hbaer_AppData_Roaming_OpenRefine_extensions_module_MOD_INF_controller_js_10.exec(file:/C:/Users/hbaer/AppData/Roaming/OpenRefine/extensions/module/MOD-INF/controller.js)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.initScope(ButterflyModuleImpl.java:619)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:629)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
        at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
        at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
        at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
        at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
        at com.google.refine.RefineServer.configure(Refine.java:291)
        at com.google.refine.RefineServer.init(Refine.java:203)
        at com.google.refine.Refine.init(Refine.java:109)
        at com.google.refine.Refine.main(Refine.java:103)
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 37 more`

**Expected behavior**
The program runs normally.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Version: Chrome 78.0.3904.97 
 -  Java(TM) SE Runtime Environment (build 1.8.0_191-b12)

**OpenRefine (please complete the following information):**
 - Version OpenRefine 3.2

**Datasets**
None

**Additional context**
None

**Comment by wetneb** [comment]
That seems to be because she has installed some extensions which were written for a previous version of OpenRefine. She should check in her local folders where extensions are stored
(C:/Documents and Settings//Application Data/OpenRefine OR C:/Documents and Settings//Local Settings/Application Data/OpenRefine normally, I don't know what this translates to in your environment). Remove all extensions there and try again.

**Comment by BennyRoesler** [comment]
Awesome! That fixed it. Thanks @wetneb

**Comment by tfmorris** [comment]
Just adding fault analysis to make it easier to find...

The missing class was org/json/JSONException (ie the legacy org.json library)
and the extension is unknown because it was called `module`

There are a number of other reports with the same signature, including #2917, which was hopefully fixed by  Butterfly 1.0.4.
