### ISSUE TITLE
Error in Facet  non blank values per column > by choice counts

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2219]
**Describe the bug**

In the All menu > Facet  non blank values per column, the display by choice counts is not working. The message "null" is displayed in an error box.

![image](https://user-images.githubusercontent.com/932804/69136018-669d4880-0aba-11ea-87bf-7ce19f99c0f7.png)

**To Reproduce**

**Current Results**

**Expected behavior**

I don't know if the choice counts is relevant for this new kind of facets

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Version: Chrome
 - JRE or JDK Version 
**OpenRefine (please complete the following information):**
 - Version : 3.3 beta

**Datasets**

**Additional context**

**Comment by thadguidry** [comment]
Happens also for All -> Facet -> Facet by star

![image](https://user-images.githubusercontent.com/986438/88992075-fc26e400-d2a7-11ea-8c5f-36a824d9830f.png)

**Comment by wetneb** [comment]
Just looking at the discussion, this sounds pretty important indeed.

**Comment by tfmorris** [comment]
Has this ever worked? The code that is being called is expecting a column/cell index, so I'd expect it to fail with all facets which aren't column-based (e.g. row-based facets). `_cellIndex` is -1 here:

https://github.com/OpenRefine/OpenRefine/blob/5639f1b2f17303b03026629d763dcb6fef98550b/main/src/com/google/refine/browsing/facets/RangeFacet.java#L318-L324

**Comment by wetneb** [comment]
@msaby do you know if this feature used to work in some older OpenRefine release?

**Comment by thadguidry** [comment]
@wetneb It did NOT work for Star/Flag in OpenRefine 2.7
I just tested starring some rows and clicking Facet by choice counts...
The spinner comes up saying WORKING...
![image](https://user-images.githubusercontent.com/986438/89186918-1986d700-d562-11ea-80f3-ef28a2a6911d.png)

.... and then this stack trace:
```
08:16:54.836 [                  command] Exception caught (0ms)
java.lang.NullPointerException
        at com.google.refine.browsing.facets.RangeFacet.computeChoices(RangeFacet.java:252)
        at com.google.refine.browsing.Engine.computeFacets(Engine.java:229)
        at com.google.refine.commands.browsing.ComputeFacetsCommand.doPost(ComputeFacetsCommand.java:55)
        at com.google.refine.RefineServlet.service(RefineServlet.java:177)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
```

**Comment by tfmorris** [comment]
> So I don't think it ever worked for Facets on the All menu.

I suspected that might be the case. It's not particularly useful for binary row facets like star/flag, so we could just remove that link. It might be slightly more valuable for the multi-column non-blank facet, particularly for very wide tables, and it certainly shouldn't error, but I'm not sure implementing support is super high priority.

**Comment by msaby** [comment]
I can not give you more information about this issue, but I am glad you are investigating it
