### ISSUE TITLE
500 error when clustering (Can't find CSRF token: missing or bad URL parameter)

### ISSUE THREAD

**Issue by eroux** [OpenRefine/OpenRefine#2235]
**Describe the bug**
 
When I select about 4000 cluster proposals in the cluster tool (by using "select all"), the UI freezes on a spinner and the server returns a 500 error, displaying the following log:

```
javax.servlet.ServletException: Can't find CSRF token: missing or bad URL parameter
	at com.google.refine.commands.Command.hasValidCSRFToken(Command.java:240)
	at com.google.refine.commands.EngineDependentCommand.doPost(EngineDependentCommand.java:73)
	at com.google.refine.RefineServlet.service(RefineServlet.java:189)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Which unfortunately is correct, it seems the request gets truncated somehow and doesn't arrive at the server fully... see [the HAR](http://eroux.fr/request.har.zip) exported by Firefox.

A solution could be to call the API several times, each 1000 clusters or something...

**To Reproduce**
Use the dataset linked to below to create a new project, click on the second column, Edit Cells, Cluster and Edit..., select all, Merge Selected and Recluster.

**Current Results**
Error 500 and frozen UI

**Expected behavior**
Clustered column 2.

**Desktop (please complete the following information):**
 - OS: Debian stable
 - Browser Version: Tried with Firefox 70.0.1 and Chrome 77.0.3865.90
 - JRE or JDK Version: openjdk version "11.0.4" 2019-07-16

**OpenRefine (please complete the following information):**
 - OpenRefine 3.3 Beta

**Datasets**

The dataset is [this csv file](http://eroux.fr/dataset.zip), I'm just clustering the second column.

**Comment by wetneb** [comment]
Thank you very much for this report!

**Comment by darecoder1999** [comment]
@eroux @wetneb I'm not able to reproduce the error with the same dataset and following the above-mentioned steps to reproduce the error. Any help would be highly appreciated. Thank you.

**Comment by wetneb** [comment]
You could try decreasing the maximum size of POST requests, by changing the system property `refine.max_form_content_size` to something small.

**Comment by darecoder1999** [comment]
Okay, @wetneb sir. Thanks for the suggestion. I'll try this.

**Comment by LanLi2017** [comment]
Hi, I meet with the same issue. And I've tried to increase the memory as well as the max form content size, but it's still not working. What else could I do? I am using version 3.1 and 3.3.  Thanks!

**Comment by wetneb** [comment]
Hi Lan, have you tried changing the system property `refine.max_form_content_size` (from the command line) to something bigger?
Something ilke `./refine -Drefine.max_form_content_size=10000000`

**Comment by tfmorris** [comment]
I think this has the same root cause as #638.
