### ISSUE TITLE
Allow importing of flat file ODS, and not only ZIPPED (PK) representation

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2242]
**Describe the bug**
Importing a flat file OpenDocument representation results in a Java Exception.

**To Reproduce**
1. Import example `1996-2000.ods` file attached.
2. See error popup dialog
![Annotation 2019-12-12 092614](https://user-images.githubusercontent.com/986438/70725171-82fb6200-1cc1-11ea-8663-dfeceaf4b7a5.png)

**Current Results**
```
09:28:10.739 [                   refine] POST /command/core/importing-controller (5ms)
09:28:10.740 [              open office] Error reading ODF spreadsheet (1ms)
java.lang.IllegalArgumentException: org.odftoolkit.odfdom.pkg.OdfValidationException; The ODF package shall be a ZIP file!
        at org.odftoolkit.odfdom.pkg.OdfPackage.readZip(OdfPackage.java:360)
        at org.odftoolkit.odfdom.pkg.OdfPackage.initializeZip(OdfPackage.java:349)
        at org.odftoolkit.odfdom.pkg.OdfPackage.<init>(OdfPackage.java:245)
        at org.odftoolkit.odfdom.pkg.OdfPackage.loadPackage(OdfPackage.java:300)
        at org.odftoolkit.odfdom.doc.OdfDocument.loadDocument(OdfDocument.java:221)
        at com.google.refine.importers.OdsImporter.createParserUIInitializationData(OdsImporter.java:89)
        at com.google.refine.importing.DefaultImportingController.doInitializeParserUI(DefaultImportingController.java:216)
```

**Expected behavior**
OpenRefine should allow importing both OpenDocument format representations.
Ref: https://en.wikipedia.org/wiki/OpenDocument_technical_specification
1. ZIP
2. flat files
 
We state that we support .ods format on the import ui, this leads users to conclude both representations could be imported, but actually only ZIP representation is supported currently it seems in OpenRefine.
We should support flat file ODS as well, because some tools/libraries still use/create both 2 representations of ODS files.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: openjdk-13.0.1_windows-x64_bin\jdk-13.0.1

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.3-beta [c8eaaee]

**Datasets**
Extract the zip file (had to zip in order to attach to this Github issue)
[1996-2000.zip](https://github.com/OpenRefine/OpenRefine/files/3956472/1996-2000.zip)

**Additional context**
Does OdfToolkit have any classes to allow flat file ODS to be loaded?

https://github.com/tdf/odftoolkit/blob/master/odfdom/src/main/java/org/odftoolkit/odfdom/pkg/OdfPackage.java

https://odftoolkit.org/api/odfdom/org/odftoolkit/odfdom/pkg/OdfPackage.html#loadPackage-java.io.File-java.lang.String-org.xml.sax.ErrorHandler-

**Comment by thadguidry** [comment]
OOps!  Jumped to conclusions to quickly... the problem is different.  Deleting this issue and creating new one.
