### ISSUE TITLE
ODS file cannot be imported, causes ODF Toolkit exceptions

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2243]
**Describe the bug**
Some ODS files cannot be imported, but open just fine in LibreOffice.

**To Reproduce**
1. Try to Import one of the test files provided such as `test.ods` file.
2. Spinner is shown with "Updating Preview...".
2. Error is shown in console about NOT_FOUND_ERR.

**Current Results**

```
12:59:10.360 [          org.mortbay.log] /command/core/importing-controller (17ms)
org.w3c.dom.DOMException: NOT_FOUND_ERR: An attempt is made to reference a node in a context where it does not exist.
        at org.apache.xerces.dom.ParentNode.internalInsertBefore(Unknown Source)
        at org.apache.xerces.dom.ParentNode.insertBefore(Unknown Source)
        at org.odftoolkit.odfdom.pkg.OdfElement.insertBefore(OdfElement.java:491)
        at org.odftoolkit.odfdom.doc.table.OdfTable.appendColumn(OdfTable.java:1092)
        at org.odftoolkit.odfdom.doc.table.OdfTable.appendColumns(OdfTable.java:1123)
        at org.odftoolkit.odfdom.doc.table.OdfTableRow.getCellByIndex(OdfTableRow.java:254)
        at com.google.refine.importers.OdsImporter$1.getNextRowOfCells(OdsImporter.java:174)
        at com.google.refine.importers.TabularImportingParserBase.readTable(TabularImportingParserBase.java:120)
        at com.google.refine.importers.OdsImporter.parseOneFile(OdsImporter.java:185)
        at com.google.refine.importers.ImportingParserBase.parseOneFile(ImportingParserBase.java:118)
        at com.google.refine.importers.ImportingParserBase.parse(ImportingParserBase.java:89)
        at com.google.refine.importing.ImportingUtilities.previewParse(ImportingUtilities.java:961)
        at com.google.refine.importing.DefaultImportingController.doUpdateFormatAndOptions(DefaultImportingController.java:174)
        at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:93)
        at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:68)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
```

**Expected behavior**
Preview and import should work for this test.ods file and perhaps others as well.

**Screenshots**
![Annotation 2019-12-12 130246_1](https://user-images.githubusercontent.com/986438/70740939-e6948800-1cdf-11ea-8103-6ee6a6422dd6.png)
![Annotation 2019-12-12 130246](https://user-images.githubusercontent.com/986438/70740946-eb593c00-1cdf-11ea-9898-5a1622c0222a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: \openjdk-13.0.1_windows-x64_bin\jdk-13.0.1

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.3-beta

**Datasets**
These test files were used in: https://github.com/chainsawriot/readODS/tree/master/tests/testdata

Here is the zip of all of the ODS test files from that readODS project:
[ODS_TEST_FILES.zip](https://github.com/OpenRefine/OpenRefine/files/3957406/ODS_TEST_FILES.zip)

**Additional context**

**Comment by wetneb** [comment]
This needs to be fixed upstream, in the odftoolkit library.

**Comment by thadguidry** [comment]
Yeap, I know.  But we always create our own good issue(s) to track the areas of OpenRefine that break. :-)

**Comment by runnwerth** [comment]
Same problem here! Any updates on this particular problem?

**Comment by wetneb** [comment]
We might be able to improve user experience here by catching relevant exceptions in the right places. If this only happens when computing the value of some cell, it would be nice if we could be able to import the rest of the table. Perhaps some of these exceptions can be meaningfully converted to our own `EvalError`.

**Comment by tfmorris** [comment]
> This needs to be fixed upstream, in the odftoolkit library.

It would be useful to have a link to the upstream bug, so that we can track it.
