### ISSUE TITLE
Problems starting OpenRefine

### ISSUE THREAD

**Issue by hmmlmetadata** [OpenRefine/OpenRefine#2321]
**Describe the bug**
I cannot launch OpenRefine and work with any projects.

**Current Results**
When I run openrefine.exe, the cmd window opens, pauses, then displays an error message.  I have tried deleting it and redownloading it, checking my Java version with the IT department, and checking the JRE/JDK version.

Here is the error message:
```
10:19:05.232 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
10:19:05.248 [            refine_server] Initializing context: '/' from '\\AD.CSBSJU.EDU\HOMEDIR$\STAFF\C\CWALSH001\My Documents\openrefine-3.3\webapp' (16ms)
10:19:08.262 [          org.mortbay.log] EXCEPTION  (3014ms)
java.lang.ClassNotFoundException: com.google.refine.RefineServlet
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:401)
        at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:363)
        at org.mortbay.util.Loader.loadClass(Loader.java:91)
        at org.mortbay.util.Loader.loadClass(Loader.java:71)
        at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:73)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
        at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
        at org.mortbay.jetty.Server.doStart(Server.java:224)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at com.google.refine.RefineServer.init(Refine.java:197)
        at com.google.refine.Refine.init(Refine.java:109)
        at com.google.refine.Refine.main(Refine.java:103)
10:19:08.262 [                        /] unavailable (0ms)
javax.servlet.UnavailableException: com.google.refine.RefineServlet
        at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:79)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
        at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
        at org.mortbay.jetty.Server.doStart(Server.java:224)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at com.google.refine.RefineServer.init(Refine.java:197)
        at com.google.refine.Refine.init(Refine.java:109)
        at com.google.refine.Refine.main(Refine.java:103)
10:19:08.262 [          org.mortbay.log] failed refine: java.lang.NullPointerException (0ms)
10:19:08.278 [          org.mortbay.log] Failed startup of context org.mortbay.jetty.webapp.WebAppContext@6737fd8f{/,\\AD.CSBSJU.EDU\HOMEDIR$\STAFF\C\CWALSH001\My Documents\openrefine-3.3\webapp} (16ms)
java.lang.NullPointerException
        at java.lang.Class.isAssignableFrom(Native Method)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
        at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
        at org.mortbay.jetty.Server.doStart(Server.java:224)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at com.google.refine.RefineServer.init(Refine.java:197)
        at com.google.refine.Refine.init(Refine.java:109)
        at com.google.refine.Refine.main(Refine.java:103)
10:19:08.325 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (47ms)
10:19:08.340 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (15ms)
10:19:08.340 [          org.mortbay.log] EXCEPTION  (0ms)
java.lang.ClassNotFoundException: com.google.refine.RefineServlet
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.mortbay.util.Loader.loadClass(Loader.java:91)
        at org.mortbay.util.Loader.loadClass(Loader.java:71)
        at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:73)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
        at com.google.refine.RefineServer.configure(Refine.java:291)
        at com.google.refine.RefineServer.init(Refine.java:203)
        at com.google.refine.Refine.init(Refine.java:109)
        at com.google.refine.Refine.main(Refine.java:103)
10:19:08.340 [                        /] unavailable (0ms)
javax.servlet.UnavailableException: com.google.refine.RefineServlet
        at org.mortbay.jetty.servlet.Holder.doStart(Holder.java:79)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:242)
        at com.google.refine.RefineServer.configure(Refine.java:291)
        at com.google.refine.RefineServer.init(Refine.java:203)
        at com.google.refine.Refine.init(Refine.java:109)
        at com.google.refine.Refine.main(Refine.java:103)
Exception in thread "main" java.lang.NullPointerException
        at java.lang.Class.isAssignableFrom(Native Method)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
        at com.google.refine.RefineServer.configure(Refine.java:291)
        at com.google.refine.RefineServer.init(Refine.java:203)
        at com.google.refine.Refine.init(Refine.java:109)
        at com.google.refine.Refine.main(Refine.java:103)
```

**Expected behavior**
I expected OpenRefine's web app to open.

**Screenshots**
![image](https://user-images.githubusercontent.com/61286060/74955804-cad9ec00-53ca-11ea-9674-98a3964ada7c.png)
![image](https://user-images.githubusercontent.com/61286060/74955844-da593500-53ca-11ea-8aa1-ec966173ed56.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox 73.0.1 64-bit
 - JRE or JDK Version: JRE 1.8.0_211-b12

**OpenRefine (please complete the following information):**
 - Version: 3.3

**Additional context**

**Comment by ostephens** [comment]
It looks like you are running OpenRefine from a network location - I have seen issues with this before although not been able to work out what the underlying problem is. Are you able to download to a location local to the computer you are using?

**Comment by hmmlmetadata** [comment]
You are my hero.  Issue resolved.
