### ISSUE TITLE
First time Export to Google Drive/Sheets is called, it does nothing

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2452]
**Describe the bug**
When you call, the FIRST TIME, the function « Export to gDrive », it does nothing. You have to call it a second time.

**To Reproduce**
1. Go to 'Export project'
2. Click on 'Export to Google Drive' and 'Export'
4. See nothing happening

**Expected behavior**
It should present the dialog box that ask for the gDrive file name.

**OpenRefine (please complete the following information):**
 - Version 3.3

**Comment by antoine2711** [comment]
Just to be more precise, the first time the command is called, the mechanism for the authentification of gData seams to open a window that gets closed after. But it should also ask for the name of the file to create in gDrive, which it only does if you call the command a second time.

**Comment by AghaSaad04** [comment]
@antoine2711 I tried but could not reproduce the issue in Google Chrome. After authorizing dialog it presents the dialog box that asks for the Google Drive file name.

but gets an error when I tried in Firefox (unfortunately could not take the Screenshot).


Now I have removed the OpenRefine app from Google Drive but now OpenRefine is not asking for authorization

![image](https://user-images.githubusercontent.com/36513474/77249520-63ca8400-6c63-11ea-96e3-e5a1b418fcff.png)
The above dialog appears but is not asking to authorize again.


**OpenRefine Version 3.3**

**Comment by khyati-agarwalss** [comment]
I tested it using Google Chrome.
OpenRefine version: 3.3
As soon as I selected the "Google Drive" option, this window showed up:
![image](https://user-images.githubusercontent.com/30500382/77257626-8d070680-6c9b-11ea-9dc7-c95933df8223.png)

**Comment by antoine2711** [comment]
> I tested it using Google Chrome.
> OpenRefine version: 3.3
> As soon as I selected the "Google Drive" option, this window showed up:
> 
> ![image](https://user-images.githubusercontent.com/30500382/77258888-985e3000-6ca3-11ea-86f5-236ef9610de3.png)

Hi @khyati-agarwalss, I suspect you are having this problem because you didn't create your private GOOGLE KEY & SECRET.

Go here to check this out! [/OpenRefine/OpenRefine/wiki/Google-Extension](https://github.com/OpenRefine/OpenRefine/wiki/Google-Extension)

Regards, Antoine

**Comment by wetneb** [comment]
@antoine2711, you don't need to quote the entire message when you are replying to it immediately after - it just needlessly duplicates content. Thanks!

**Comment by antoine2711** [comment]
Hi @AghaSaad04 

> @antoine2711 I tried but could not reproduce the issue in Google Chrome. After authorizing dialog it presents the dialog box that asks for the Google Drive file name.

I suggest that you do this sequence:
1. do an export of the project in gDrive;
2. quit OR;
3. launch again;
4. try to Export to gDrive;
Then, you will see a window opening and closing, one just the size of the gData authentification. But wait, and nothing else will happen.

> but gets an error when I tried in Firefox (unfortunately could not take the Screenshot but it was some 400 bad request error).
> After closing that bad request dialog I was still able to upload the file after **exporting again**.

I didn't even try Firefox. All my problems are with Chrome.

> Now I have removed the OpenRefine app from Google Drive but now OpenRefine is not asking for authorization
> The above dialog appears but is not asking to authorize again.

I haven't tried removing gData auth. But the authentification process could be involved in the problem.

Regards, Antoine

**Comment by allanaaa** [comment]
I experienced this today with Firefox 77.0.1 and on OpenRefine 3.3. I had never connected with Google before, for either import or export.

It asked me to authorize, which I did, then it gave me an error and did nothing. The export worked the second time (without reauthorization).

**Comment by allanaaa** [comment]
Just a followup in case this helps:

Using 3.4, Create Project > Google Data did not show me as authorized. When I tried to authorize I got 

> HTTP ERROR 500
> Problem accessing /extension/gdata/authorized. Reason:
>    Butterfly Error
>Butterfly caught the following error while processing the request:
>org.mozilla.javascript.WrappedException: Wrapped com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
>{
>  "error" : "invalid_grant",
>  "error_description" : "Bad Request"
>} (openrefine-3.4-beta/webapp/extensions/gdata/module/MOD-INF/controller.js#108)
> ....
etc. 

I tried a few times; no change. 

When I opened an existing project and went to "export as Google Sheets" it worked fine. 
Then, when I navigated back to Create Project > Google Data, it showed me as authorized. 

So, I suspect there are multiple issues with authorization.

**Comment by tfmorris** [comment]
This is true for Google Sheets export as well. Something is messed up with the OAuth2 flow for handling the final callback.

**Comment by allanaaa** [comment]
Just in case it's helpful: I experienced this also in Ubuntu and Firefox - this time I tried to authorize on the "Create project > Google data" screen and it gave me the same error: HTP Error 500, Butterfly Error, 400 Bad Request, etc. But it authorized properly according to the email I received. I refreshed the OpenRefine tab and it loaded my documents.

**Comment by thadguidry** [comment]
So testing on my clean Windows installation with OpenRefine 3.5 beta1 to see where this issue is at now with Firefox specifically...
1. I create a small clipboard project
2. Export to Google Drive
3. I am prompted with a popup browser window for Oauth login showing standard Google authorization for accounts, where I choose my account.
4. A send browser window appears where I much review 2 checkbox items to allow writing which I do, and then at the bottom click ACCEPT.
5. The Oauth dance continues but then get the following Butterfly error while doing so inside that last auth browser window...
```html
<tbody><tr><th>URI:</th><td>/extension/gdata/authorized</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>Butterfly Error
Butterfly caught the following error while processing the request:
org.mozilla.javascript.WrappedException: Wrapped com.google.api.client.auth.oauth2.TokenResponseException: 401 Unauthorized
POST https://oauth2.googleapis.com/token (file:/E:/Downloads/openrefine-win-with-java-3.5-beta1/openrefine-3.5-beta1/webapp/extensions/gdata/module/MOD-INF/controller.js#108)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1773)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:183)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
	at org.mozilla.javascript.gen.c12._c3(file:/E:/Downloads/openrefine-win-with-java-3.5-beta1/openrefine-3.5-beta1/webapp/extensions/gdata/module/MOD-INF/controller.js:108)
	at org.mozilla.javascript.gen.c12.call(file:/E:/Downloads/openrefine-win-with-java-3.5-beta1/openrefine-3.5-beta1/webapp/extensions/gdata/module/MOD-INF/controller.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
	at org.mozilla.javascript.gen.c12._c2(file:/E:/Downloads/openrefine-win-with-java-3.5-beta1/openrefine-3.5-beta1/webapp/extensions/gdata/module/MOD-INF/controller.js:107)
	at org.mozilla.javascript.gen.c12.call(file:/E:/Downloads/openrefine-win-with-java-3.5-beta1/openrefine-3.5-beta1/webapp/extensions/gdata/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.gen.c12.call(file:/E:/Downloads/openrefine-win-with-java-3.5-beta1/openrefine-3.5-beta1/webapp/extensions/gdata/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.process(ButterflyModuleImpl.java:399)
	at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.run(ButterflyModuleImpl.java:377)
	at org.mozilla.javascript.Context.call(Context.java:515)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:507)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.processScript(ButterflyModuleImpl.java:650)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.process(ButterflyModuleImpl.java:427)
	at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:518)
	at com.google.refine.RefineServlet.service(RefineServlet.java:210)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1395)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.google.refine.ValidateHostHandler.handle(ValidateHostHandler.java:96)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.google.api.client.auth.oauth2.TokenResponseException: 401 Unauthorized
POST https://oauth2.googleapis.com/token
	at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:326)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:166)
	at com.google.refine.extension.gdata.GoogleAPIExtension.getTokenFromCode(GoogleAPIExtension.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
	... 52 more
</td></tr>
<tr><th>SERVLET:</th><td>refine</td></tr>
</tbody>

```

**Comment by antoine2711** [comment]
@wetneb : from my tests, this is resolved with v3.5. I think we can close this.

Regards, Antoine

**Comment by wetneb** [comment]
Thanks a lot!

**Comment by antoine2711** [comment]
I'd like to thanks @tfmorris for all the great work he has done in regards with the Google Data extension in the last 2 year.
It’s impressive. The reliability has vastly improved with his contributions. Nice work.

Best Regards, Antoine
