### ISSUE TITLE
OpenRefine 3.3 throws Number Format Exception on Windows 10 when trying to preview query

### ISSUE THREAD

**Issue by gigincg** [OpenRefine/OpenRefine#2509]
When I connect to my MySQL DB, I'm asked to enter a query and when I keep a simple query "SELECT * FROM mytable", It displays "Updating Preview" Forever and throws an exception in Command Line. Sharing the logs:

Logs:07:49:14.972 [                   refine] GET /command/core/get-csrf-token (253429ms)
07:49:14.979 [                   refine] POST /command/core/cancel-importing-job (7ms)
07:49:19.654 [                   refine] GET /command/database/saved-connection (4675ms)
07:49:19.664 [                   refine] GET /command/core/get-csrf-token (10ms)
07:49:19.673 [                   refine] POST /command/database/connect (9ms)
07:49:25.019 [                   refine] GET /command/core/get-csrf-token (5346ms)
07:49:25.025 [                   refine] POST /command/database/test-query (6ms)
07:49:25.047 [                   refine] GET /command/core/get-csrf-token (22ms)
07:49:25.052 [                   refine] POST /command/core/create-importing-job (5ms)
07:49:25.104 [                   refine] GET /command/core/get-csrf-token (52ms)
07:49:25.111 [                   refine] POST /command/core/importing-controller (7ms)
07:49:25.130 [                   refine] GET /command/core/get-csrf-token (19ms)
07:49:25.137 [                   refine] POST /command/core/importing-controller (7ms)
07:49:25.137 [          org.mortbay.log] /command/core/importing-controller (0ms)
java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:614)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.google.refine.extension.database.DatabaseImportController.getQueryInfo(DatabaseImportController.java:453)
        at com.google.refine.extension.database.DatabaseImportController.doParsePreview(DatabaseImportController.java:184)
        at com.google.refine.extension.database.DatabaseImportController.doPost(DatabaseImportController.java:100)
        at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:68)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

Desktop:
Windows 10 
Chrome Latest
Java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)

**OpenRefine (please complete the following information):**
OpenRefine 3.3

**Comment by antoine2711** [comment]
@gigincg: The database import was not working in v3.3 in a lot of situations. Either go back to version v3.2, or download the current GitHub snapshot of OpenRefine.

* Can't load data from Postgres-Database using in-build database-connectors #2281
* [https://github.com/OpenRefine/OpenRefine/wiki/Changes-for-3.4](Changes-for-3.4)

If it fixes your problem, please let us know so that we can close this issue.

Regards, Antoine

**Comment by wetneb** [comment]
I would not close this issue without checking using the stack trace provided where the error was coming from.

**Comment by tfmorris** [comment]
This is almost certainly due to a non-numeric port number in the configuration. This code:
https://github.com/OpenRefine/OpenRefine/blob/6e66cb5144e1a621cfe1843a86b06f6bad9dcedd/extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java#L455
needs to be protected with a `try/except` block.
