### ISSUE TITLE
Loss of Starring an Expression in History

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2544]
What breaks:
* Star an expression in history

**Details:**
* OpenRefine win 3.3 release
* Windows 10
* JDK 8
* Firefox, Chrome, Edge
* The last part of `workspace.json` is formed as such:
```json
            ],
            "ui.browsing.listFacet.limit": 22000,
            "scripting.starred-expressions": null,
            "userLang": "en",
            "scripting.expressions": {
                "top": 100,
                "list": ["grel:value.startsWith(\"http\")", "grel:value.replace(\"/wiki/Property:\",\"/entity/\")", "grel:value.contains(\"Property\")"],
                "class": "com.google.refine.preference.TopList"
            },
            "ui.show-control-characters": "true"
        }
    }
```

**Error:** 
* Clicking on a Star next to a GREL in the Expression History **does not work** and throws an NPE here:
```
10:06:28.438 [          org.mortbay.log] /command/core/toggle-starred-expression (0ms)
java.lang.NullPointerException
        at com.google.refine.commands.expr.ToggleStarredExpressionCommand.doPost(ToggleStarredExpressionCommand.java:53)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
<snip>
```

**Additional context:**

Wondering if any leftover TODO's from this issue #2086 ?

**Comment by tfmorris** [comment]
I can reproduce this with my corrupted workspace. The problem occurs here: https://github.com/OpenRefine/OpenRefine/blob/83a4fb4b2524517582956e67a0ec6c03d20431a0/main/src/com/google/refine/commands/expr/ToggleStarredExpressionCommand.java#L50-L53

but the root cause is: a) workspace.json being corrupted with  "scripting.starred-expressions": null and b) the deserialization code not recovering from it.
