### ISSUE TITLE
Version 3.3 not starting on Ubuntu 18.04 due to Exception

### ISSUE THREAD

**Issue by AlyxTaj** [OpenRefine/OpenRefine#2554]
**Describe the bug**
OpenRefine 3.3 not starting due to JSON Exception?

**To Reproduce**
1. Download Release 3.3. Linux Kit
2. Extract .tar to /Applications
3. Enter ./refine in Terminal

**Current Results**

```
You have 7865M of free memory.`
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
> https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
> Starting OpenRefine at 'http://127.0.0.1:3333/'
> 
> 14:14:23.900 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
> 14:14:23.901 [            refine_server] refine.memory size: 1400M JVM Max heap: 1468006400 (1ms)
> 14:14:23.914 [            refine_server] Initializing context: '/' from '/home/alyx/Applications/openrefine-3.3/webapp' (13ms)
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/home/alyx/Applications/openrefine-3.3/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/home/alyx/Applications/openrefine-3.3/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
> 14:14:24.812 [                   refine] Starting OpenRefine 3.3 [58b839b]... (898ms)
> 14:14:24.812 [                   refine] initializing FileProjectManager with dir (0ms)
> 14:14:24.812 [                   refine] /home/alyx/.local/share/openrefine (0ms)
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.python.core.PySystemState (file:/home/alyx/Applications/openrefine-3.3/webapp/extensions/jython/module/MOD-INF/lib/jython-standalone-2.7.1.jar) to method java.io.Console.encoding()
> WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONException
> 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
> 	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
> 	at java.base/java.lang.Class.getMethods(Class.java:1904)
> 	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:351)
> 	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:302)
> 	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:424)
> 	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:43)
> 	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:812)
> 	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:49)
> 	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44)
> 	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:43)
> 	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:39)
> 	at org.mozilla.javascript.WrapFactory.wrapJavaClass(WrapFactory.java:139)
> 	at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:135)
> 	at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:84)
> 	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2313)
> 	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1579)
> 	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1572)
> 	at org.mozilla.javascript.gen.file__home_alyx__local_share_openrefine_extensions_orefine_rdf_extension_0_9_MOD_INF_controller_js_10._c_script_0(file:/home/alyx/.local/share/openrefine/extensions/orefine-rdf-extension-0.9/MOD-INF/controller.js:4)
> 	at org.mozilla.javascript.gen.file__home_alyx__local_share_openrefine_extensions_orefine_rdf_extension_0_9_MOD_INF_controller_js_10.call(file:/home/alyx/.local/share/openrefine/extensions/orefine-rdf-extension-0.9/MOD-INF/controller.js)
> 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
> 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
> 	at org.mozilla.javascript.gen.file__home_alyx__local_share_openrefine_extensions_orefine_rdf_extension_0_9_MOD_INF_controller_js_10.call(file:/home/alyx/.local/share/openrefine/extensions/orefine-rdf-extension-0.9/MOD-INF/controller.js)
> 	at org.mozilla.javascript.gen.file__home_alyx__local_share_openrefine_extensions_orefine_rdf_extension_0_9_MOD_INF_controller_js_10.exec(file:/home/alyx/.local/share/openrefine/extensions/orefine-rdf-extension-0.9/MOD-INF/controller.js)
> 	at edu.mit.simile.butterfly.ButterflyModuleImpl.initScope(ButterflyModuleImpl.java:619)
> 	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:629)
> 	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
> 	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
> 	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
> 	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
> 	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
> 	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
> 	at com.google.refine.RefineServer.configure(Refine.java:291)
> 	at com.google.refine.RefineServer.init(Refine.java:203)
> 	at com.google.refine.Refine.init(Refine.java:109)
> 	at com.google.refine.Refine.main(Refine.java:103)
> Caused by: java.lang.ClassNotFoundException: org.json.JSONException
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	... 37 more
> 
```
```

```
**Expected behavior**

OpenRefine should launch on Firefox

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Version: Firefox 75
 - JRE or JDK Version: openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

**OpenRefine (please complete the following information):**
 - Version 3.3

**Additional context**
I have seen Issues #1939, #2125, #2150 and #2154 and I too have had previous versions of OpenRefine on my computer (2.7) if I remember correctly as well as LODRefine. However, I cannot find anything relating to these (and the directories are named differently than on Windows or Mac), I thought I had a clean install but I guess I left something out, unless I don't have the right java?
Tried extracting into a new directory (Apps instead of Applications both under /home/alyx) as well as changing openrefine-3.3 folder name to OpenRefine but it didn't do anything.

Tried version 3.2 and got a similar issue.

Tried reinstalling LODRefine and it gave me this:
`OpenRefine requires Java version 6 or later. If you have multiple versions of Java installed, please set the environment variable JAVA_HOME to the correct version.`

Tried with the Windows Kit and Wine and it gave me this
`This application requires a Java Runtime Environment 1.8.0`

I hope these precisions are useful and that this issue is not too redundant with the previous ones. I've been pulling my hair for several days.
Thank you in advance for everything you can tell me.
```

**Comment by wetneb** [comment]
This is most likely due to an extension designed for a previous version of OpenRefine. If you go to `/home/alyx/.local/share/openrefine`, you should find an `extensions` folder: try deleting this extensions folder and start OpenRefine 3.3 again.
You can also try upgrading the extensions instead (for instance, the rdf extension has been updated to work with OpenRefine 3.3).

**Comment by AlyxTaj** [comment]
> This is most likely due to an extension designed for a previous version of OpenRefine. If you go to `/home/alyx/.local/share/openrefine`, you should find an `extensions` folder: try deleting this extensions folder and start OpenRefine 3.3 again.
> You can also try upgrading the extensions instead (for instance, the rdf extension has been updated to work with OpenRefine 3.3).

Thank you very much. I found the folder and deleted it.
OpenRefine launched without any problem (Still had to reroute the JAVA_HOME first though).

Thank you again.
