### ISSUE TITLE
Sort as date fails with no error message on misformed data

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#257]
_Original author: tfmorris (November 26, 2010 17:57:12)_

I'll need to try and figure out what the bad data was, but logging this now just so it doesn't get lost.  I sorted on a column and clicked the &quot;Date&quot; option in the sort dialog.  The browser page went into it's &quot;spin forever&quot; mode since the server request died.

07:30:13.173 [                  command] Exception caught (53ms)
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Date
    at com.google.refine.sorting.DateCriterion$1.compareKeys(DateCriterion.java:64)
    at com.google.refine.sorting.BaseSorter$ComparatorWrapper.compare(BaseSorter.java:101)
    at com.google.refine.sorting.BaseSorter.compare(BaseSorter.java:169)
    at com.google.refine.sorting.SortingRowVisitor$1.compare(SortingRowVisitor.java:85)
    at com.google.refine.sorting.SortingRowVisitor$1.compare(SortingRowVisitor.java:75)
    at java.util.Arrays.mergeSort(Arrays.java:1293)
    at java.util.Arrays.mergeSort(Arrays.java:1282)
    at java.util.Arrays.mergeSort(Arrays.java:1281)
    at java.util.Arrays.mergeSort(Arrays.java:1281)
    at java.util.Arrays.mergeSort(Arrays.java:1281)
    at java.util.Arrays.mergeSort(Arrays.java:1281)
    at java.util.Arrays.mergeSort(Arrays.java:1281)
    at java.util.Arrays.mergeSort(Arrays.java:1281)
    at java.util.Arrays.mergeSort(Arrays.java:1281)
    at java.util.Arrays.mergeSort(Arrays.java:1281)
    at java.util.Arrays.mergeSort(Arrays.java:1281)
    at java.util.Arrays.sort(Arrays.java:1210)
    at java.util.Collections.sort(Collections.java:159)
    at com.google.refine.sorting.SortingRowVisitor.end(SortingRowVisitor.java:75)
    at com.google.refine.browsing.util.ConjunctiveFilteredRows.accept(ConjunctiveFilteredRows.java:68)
    at com.google.refine.commands.row.GetRowsCommand.internalRespond(GetRowsCommand.java:130)
    at com.google.refine.commands.row.GetRowsCommand.doPost(GetRowsCommand.java:68)
    at com.google.refine.RefineServlet.service(RefineServlet.java:170)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=257_

**Comment by thadguidry** [comment]
This seems to be a muted Error now, after Thad and Jacky have looked into it.  We no longer have the forever spinner, but we probably should be throwing an Error, since it seems as if the Sort worked, but in fact, it does nothing with mixed text/number/date values and asking to Sort by Date.

**Comment by wetneb** [comment]
I do not see any error being thrown, it just works as I would expect, I would say. Values which are not of the expected datatype end up in the section for evaluation errors in the sorted grid, which is fine I guess? Giving the user an overview of the datatypes in a column would also be helpful, but it seems independent from sorting.
