### ISSUE TITLE
CSV importer with auto-detect datatype feature fails to parse table

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2584]
**Describe the bug**

Import the following CSV table:

```
a,b
1,2
2018-09-01T01:02:03Z,f
true,23.2
```
and enable "Parse cell text into numbers, dates, …"

**Current Results**

```
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
	at com.google.refine.importers.TabularImportingParserBase.readTable(TabularImportingParserBase.java:173)
	at com.google.refine.importers.SeparatorBasedImporter.parseOneFile(SeparatorBasedImporter.java:160)
	at com.google.refine.importers.ImportingParserBase.parseOneFile(ImportingParserBase.java:128)
	at com.google.refine.importers.ImportingParserBase.parse(ImportingParserBase.java:89)
	at com.google.refine.importing.ImportingUtilities.previewParse(ImportingUtilities.java:961)
	at com.google.refine.importing.DefaultImportingController.doUpdateFormatAndOptions(DefaultImportingController.java:175)
	at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:94)
	at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:68)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**
No exception thrown, table parsed correctly.

**OpenRefine (please complete the following information):**
 - master branch

**Comment by joanneong** [comment]
@wetneb I just tested this on the latest `master` branch locally and I could not replicate the error:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/24493463/80223346-bfc96380-867a-11ea-8062-9232814cf480.png">

I saved your example as a csv file and imported it into OpenRefine as a new project.

**Comment by wetneb** [comment]
Interesting, I'll have to investigate more on my side then. Thanks for looking into this!

**Comment by thadguidry** [comment]
@wetneb Did you perform a Clipboard load or CSV file load?

**Comment by wetneb** [comment]
Clipboard

**Comment by joanneong** [comment]
I just tested with both Clipboard and CSV file loads, and I did not experience the problem with either method

**Comment by wetneb** [comment]
This bug shows up when both trimming whitespace in cell values and auto-detecting cell datatypes. Perhaps you tried to reproduce it on an outdated copy of the master branch? Whitespace trimming is enabled by default now.
