### ISSUE TITLE
HTTP 500 error when using Recon values as identifiers

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2609]
**Describe the bug**
Whenever I perform recon using identifiers, I get an error message

Location:
```
http://127.0.0.1:3333/command/core/recon-use-values-as-identifiers?columnName=wd&service=https%3A%2F%2Ftools.wmflabs.org%2Fopenrefine-wikidata%2Fen%2Fapi&identifierSpace=http%3A%2F%2Fwww.wikidata.org%2Fentity%2F&schemaSpace=http%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F&project=1805600112719
```

Message:
```
XML Parsing Error: not well-formed
Location: http://127.0.0.1:3333/command/core/recon-use-values-as-ident…%2Fwww.wikidata.org%2Fprop%2Fdirect%2F&project=1805600112719
Line Number 1, Column 1: recon-use-values-as-identifiers:1:1
```

Trace:
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 INTERNAL_SERVER_ERROR</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /command/core/recon-use-values-as-identifiers. Reason:
<pre>    INTERNAL_SERVER_ERROR</pre></p><h3>Caused by:</h3><pre>java.lang.UnsupportedOperationException
	at com.google.refine.commands.Command.doGet(Command.java:89)
	at com.google.refine.RefineServlet.service(RefineServlet.java:180)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
</pre>
<hr /><i><small>Powered by Jetty://</small></i><br/>   
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/986438/80972552-e22e5000-8de3-11ea-8a84-05e31124cd46.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8

**OpenRefine (please complete the following information):**
 - Version:  Trunk (master)

**Comment by tfmorris** [comment]
My simple attempt to reproduce this against Wikidata (en) with the current development head worked without problem. Is it still happening?

**Comment by tfmorris** [comment]
@thadguidry ping. I'm going to close this on the assumption that it's no longer happening, but feel free to reopen if you can reproduce it.
