### ISSUE TITLE
NPE in edit generation in the Wikidata extension

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2880]
**Describe the bug**
Generating edits for string values can fail in the presence of null cells.

**To Reproduce**
1. Create a schema that adds a label from a row with a null cell
2. Observe the error

(I cannot believe I have not run into this bug earlier!)

**Current Results**
```
java.lang.NullPointerException
	at org.openrefine.wikidata.schema.WbStringVariable.fromCell(WbStringVariable.java:59)
	at org.openrefine.wikidata.schema.WbStringVariable.fromCell(WbStringVariable.java:39)
	at org.openrefine.wikidata.schema.WbVariableExpr.evaluate(WbVariableExpr.java:82)
	at org.openrefine.wikidata.schema.WbStatementExpr.evaluate(WbStatementExpr.java:95)
	at org.openrefine.wikidata.schema.WbStatementGroupExpr.evaluate(WbStatementGroupExpr.java:63)
	at org.openrefine.wikidata.schema.WbItemDocumentExpr.evaluate(WbItemDocumentExpr.java:79)
	at org.openrefine.wikidata.schema.WikibaseSchema.evaluateItemDocuments(WikibaseSchema.java:114)
	at org.openrefine.wikidata.schema.WikibaseSchema$EvaluatingRowVisitor.visit(WikibaseSchema.java:171)
	at com.google.refine.browsing.util.RowVisitorAsRecordVisitor.visit(RowVisitorAsRecordVisitor.java:61)
	at com.google.refine.browsing.util.ConjunctiveFilteredRecords.accept(ConjunctiveFilteredRecords.java:64)
	at com.google.refine.browsing.util.FilteredRecordsAsFilteredRows.accept(FilteredRecordsAsFilteredRows.java:50)
	at org.openrefine.wikidata.schema.WikibaseSchema.evaluate(WikibaseSchema.java:142)
	at org.openrefine.wikidata.commands.PreviewWikibaseSchemaCommand.doPost(PreviewWikibaseSchemaCommand.java:88)
```

**Expected behavior**
The value should be skipped.

**OpenRefine :**
 - Version 3.4 beta2

**Comment by wetneb** [comment]
After more investigation this seems to be due to the presence of non-null cells with null values, generated by the data extension operation. We need to fix both the edit generation so that it does not choke on this, and the data extension operation so that it creates properly null cells.
