### ISSUE TITLE
During reconcile its stuck

### ISSUE THREAD

**Issue by Atudu** [OpenRefine/OpenRefine#2903]
**Describe the bug**

During reconcile the data, the page is stuck and its shows ''working'' from yesterday
**To Reproduce**
1. 

**Current Results**

its shows WORKING only, but its not working actually
**Expected behavior**

**Screenshots**

**Desktop:**
 - OS: 
 - Browser Version: 
 - JRE or JDK Version: 

**OpenRefine :**
 - Version 

**Datasets**

**Additional context**

**Comment by tfmorris** [comment]
- What reconciliation service are you using?
- What type within the reconciliation service are you reconciling against? 
- How many rows/items are in the batch that you are reconciling?
- How many hours has it been running? 
- Are there any errors displayed on either the Javascript console for your web browser or the OpenRefine server console?

**Comment by Atudu** [comment]
I was checking whether the items are present in wikidata or not, then I
will upload the data set to wikidata.

I tried multiple times from yesterday and it shows 'working' ... Indicater
is loading more than 1 hour and nothing happened.

My data set has 3 column and 730 rows

**Comment by wetneb** [comment]
Looking at the screenshot this must be a failure during the "guess types" operation, which sends the first 10 rows to the reconciliation service.

**Comment by addshore** [comment]
I'm also getting this (while trying to re run steps I have already run to grab screenshots for a blog post).

If this is talking to the openrefine reconciliation service is this to do with the domain name changes there?

Stacktrace included below.

```
09:48:17.560 [                   refine] POST /command/core/guess-types-of-column (66ms)
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<html>
<head><title>308 Permanent Redirect</title></head>
<body bgcolor="white">
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
"; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1902)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4043)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2552)
        at com.google.refine.util.ParsingUtilities.evaluateJsonStringToObjectNode(ParsingUtilities.java:256)
        at com.google.refine.commands.recon.GuessTypesOfColumnCommand.guessTypes(GuessTypesOfColumnCommand.java:202)
        at com.google.refine.commands.recon.GuessTypesOfColumnCommand.doPost(GuessTypesOfColumnCommand.java:110)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
09:48:17.921 [                  command] Exception caught (361ms)
java.lang.NullPointerException
        at com.google.refine.commands.recon.GuessTypesOfColumnCommand.guessTypes(GuessTypesOfColumnCommand.java:204)
        at com.google.refine.commands.recon.GuessTypesOfColumnCommand.doPost(GuessTypesOfColumnCommand.java:110)
        at com.google.refine.RefineServlet.service(RefineServlet.java:189)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wetneb** [comment]
Dammit! I checked that reconciliation worked with redirects, but the type guessing command apparently does not. Weird.

You should be able to fix this by removing the Wikidata reconciliation service from the list, and adding it manually, with this endpoint:
`https://wdreconcile.toolforge.org/en/api`

**Comment by wetneb** [comment]
Postmorted: somehow, HttpURLConnection follows temporary redirects but not permanent ones: only HTTP codes from 300 to 307 are followed, and now the redirection uses HTTP 308.

When I tested whether the code followed redirects, I simulated the new environment by deploying the reconciliation service with the `--canonical` option, which set up temporary redirects, not permanent ones.
Now that the redirection from `tools.wmflabs.org` to `*.toolforge.org` is permanent, we get this limbo.

There are times when I would rather disappear under a rock…

**Comment by addshore** [comment]
> You should be able to fix this by removing the Wikidata reconciliation service from the list, and adding it manually, with this endpoint: `https://wdreconcile.toolforge.org/en/api`.

I can confirm this works

> 
> Upgrading to 3.4-beta2 should also fix the issue.

I can confirm this does not work

**Comment by wetneb** [comment]
> > Upgrading to 3.4-beta2 should also fix the issue.
> 
> I can confirm this does not work

Right, because the new service will only be registered if there is no existing reconciliation service, so 3.4-beta2 only "fixes" the issue if you remove all your reconciliation services after migrating…

**Comment by susannaanas** [comment]
I have had this issue for at least a week. I installed a new beta version, tried different datasets. Also "Add column from reconciled values gives an error". Maybe I am late to report, hope you will find the cause!

**Comment by wetneb** [comment]
@susannaanas you should be able to fix this by removing the Wikidata reconciliation service from the list, and adding it manually, with this endpoint: `https://wdreconcile.toolforge.org/en/api`.
Columns that have been reconciled before the change need to be reconciled again with the new service to use "Add column from reconciled values".

**Comment by susannaanas** [comment]
OK thanks! I see you mentioned that before already!

**Comment by tfmorris** [comment]
In addition to handling the redirect, the code should also handle a non-JSON response which is the immediate cause of the error (similar to #1128). The changes that I made in #2590 might be able to be adapted. Widening the exception handler to include JsonParseException might do the trick.
