### ISSUE TITLE
NPE during creation of new items referencing each other

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3106]
While testing #2810 I tried creating multiple items which reference each other :  [countries.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/5112051/countries.openrefine.tar.gz)

I got this stack trace:
```
08:51:15.001 [..mWikibaseEditsOperation] Performing edits (28ms)
08:51:15.003 [..ting.EditBatchProcessor] Requesting documents (2ms)
08:51:15.004 [..ting.EditBatchProcessor] Retrying in 10000 ms (1ms)
08:51:25.004 [..ting.EditBatchProcessor] Retrying in 20000 ms (10000ms)
08:51:44.443 [           ProjectManager] Saving some modified projects ... (19439ms)
08:51:44.453 [        project_utilities] Saved project '2563820830151' (10ms)
08:51:45.004 [..ting.EditBatchProcessor] Retrying in 40000 ms (551ms)
08:52:25.004 [..ting.EditBatchProcessor] Retrying in 80000 ms (40000ms)
08:53:46.427 [..kibaseapi.ApiConnection] API warning [main]: Unrecognized parameter: tags. (81423ms)
08:53:47.978 [..kibaseapi.ApiConnection] API warning [main]: Unrecognized parameter: tags. (1551ms)
08:53:48.822 [..kibaseapi.ApiConnection] API warning [main]: Unrecognized parameter: tags. (844ms)
08:53:49.326 [..kibaseapi.ApiConnection] API warning [main]: Unrecognized parameter: tags. (504ms)
08:53:49.825 [..kibaseapi.ApiConnection] API warning [main]: Unrecognized parameter: tags. (499ms)
Exception in thread "Thread-7" java.lang.NullPointerException
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.markStatementsForInsertion(StatementUpdate.java:381)
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.markStatementsForUpdate(StatementUpdate.java:307)
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.<init>(StatementUpdate.java:180)
	at org.wikidata.wdtk.wikibaseapi.TermStatementUpdate.<init>(TermStatementUpdate.java:127)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.updateTermsStatements(WikibaseDataEditor.java:732)
	at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:170)
	at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:221)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

There are a few problems here:
* We try requesting documents in the beginning of the batch whereas all items are new, so there should not be any items to fetch. The API action is likely failing because we are requesting an empty list of documents. In any case, we should only retry fetching documents when the API error we get is a temporary one - in this case it is likely to be a persistent error;
* If we fail with an exception after having created items (or if the user cancels the operation), we should still perform the operation (skipping further edits) such that the newly created items are updated in the project grid;
* The NPE is worth solving on its own obviously.

### To Reproduce
1. Import the project supplied above
2. Make sure the corresponding items have been deleted on OR Wikibase test first https://or-wikibase-test.wiki.opencura.com/wiki/Main_Page
3. Upload the edits to OR Wikibase test

### Versions
- testing from #2810 but I believe the bug is independent from @afkbrb 's refactoring

**Comment by wetneb** [comment]
The structure of this code has changed a lot since that time (both in WDTK and in OpenRefine), so this is surely not reproducible in this form.
