### ISSUE TITLE
Unable to load starred expressions (and history) on Refine server reload

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3148]
I see this a lot in my development environment, but don't know if it represents a potential race / issue in customer systems:

    Could not resolve type id 'com.google.refine.preference.TopList' as a subtype of `com.google.refine.preference.PreferenceValue`: Not a subtype

### To Reproduce
1. Start Refine from Eclipse
2. Modify some code and save the new file
3. After Refine notices the modified code and reloads the affected classes, look at the console log and notice the errors below

### Current Results

com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'com.google.refine.preference.TopList' as a subtype of `com.google.refine.preference.PreferenceValue`: Not a subtype
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1784)
	at com.fasterxml.jackson.databind.DatabindContext._throwNotASubtype(DatabindContext.java:276)
	at com.fasterxml.jackson.databind.DatabindContext.resolveAndValidateSubType(DatabindContext.java:237)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:72)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:66)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:154)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:115)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4495)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2728)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3181)
	at com.google.refine.preference.PreferenceStore.loadObject(PreferenceStore.java:125)
	at com.google.refine.preference.PreferenceStore.setEntries(PreferenceStore.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:257)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2081)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1625)
	at com.google.refine.io.FileProjectManager.loadFromFile(FileProjectManager.java:374)
	at com.google.refine.io.FileProjectManager.load(FileProjectManager.java:353)
	at com.google.refine.io.FileProjectManager.<init>(FileProjectManager.java:92)
	at com.google.refine.io.FileProjectManager.initialize(FileProjectManager.java:79)
	at com.google.refine.RefineServlet.init(RefineServlet.java:139)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:180)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.access$000(Refine.java:135)
	at com.google.refine.RefineServer$1.filesChanged(Refine.java:256)
	at org.mortbay.util.Scanner.reportBulkChanges(Scanner.java:486)
	at org.mortbay.util.Scanner.reportDifferences(Scanner.java:352)
	at org.mortbay.util.Scanner.scan(Scanner.java:280)
	at org.mortbay.util.Scanner$1.run(Scanner.java:232)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

### Expected Behavior

Expression history and starred expression are correctly loaded from the workspace.json file.

**Comment by thadguidry** [comment]
@tfmorris That same error has shown in other issues reported: https://github.com/OpenRefine/OpenRefine/search?q=%27com.google.refine.preference.TopList&type=Issues

**Comment by wetneb** [comment]
I'd be in favor of disabling hot code reloading entirely to avoid such issues.
At least we should disable it in the Linux release.
