### ISSUE TITLE
"Manage Wikidata account" > "Log out" button doesn't work

### ISSUE THREAD

**Issue by allanaaa** [OpenRefine/OpenRefine#3202]
Nothing happens when you try to log out of Wikidata in OpenRefine. Pressing the button has no visible effect in the interface, and if you refresh, you are still logged in. 
Restarting OpenRefine does the trick, though. 

Tried in Firefox (where I was logged in on Wikidata) and Chrome (where I was not logged in). I mention this because I wanted to see if it was related to #2873.

### Versions
 OpenRefine 3.4, Windows 10

**Comment by Nikerabbit** [comment]
The fix in https://github.com/OpenRefine/OpenRefine/commit/7c670344cac21b4d400c8905ed157f4c8c8d9ea8#diff-127cbaaa32a095e437a6df61a190f768a27b9819e18335c61c552b012529ebd0 is not working because it is trying to catch `MediaWikiApiErrorException` but it is getting `IOException` because the former is converted to the latter in https://github.com/Wikidata/Wikidata-Toolkit/blob/6cb761dfd355b1a4e4bc93722990ff3f638e47e7/wdtk-wikibaseapi/src/main/java/org/wikidata/wdtk/wikibaseapi/BasicApiConnection.java#L353

You can see this from the trace:
```
openrefine_1        | 12:16:40.013 [       connection_manager] [assertuserfailed] You are no longer logged in, so the action could not be completed. (67ms)
openrefine_1        | java.io.IOException: [assertuserfailed] You are no longer logged in, so the action could not be completed.
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.BasicApiConnection.logout(BasicApiConnection.java:353)
openrefine_1        |   at org.openrefine.wikidata.commands.ConnectionManager.logout(ConnectionManager.java:179)
openrefine_1        |   at org.openrefine.wikidata.commands.LoginCommand.doPost(LoginCommand.java:89)
openrefine_1        |   at com.google.refine.RefineServlet.service(RefineServlet.java:187)
openrefine_1        |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
openrefine_1        |   at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
openrefine_1        |   at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
openrefine_1        |   at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
openrefine_1        |   at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
openrefine_1        |   at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
openrefine_1        |   at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
openrefine_1        |   at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
openrefine_1        |   at org.mortbay.jetty.Server.handle(Server.java:326)
openrefine_1        |   at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
openrefine_1        |   at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
openrefine_1        |   at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
openrefine_1        |   at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
openrefine_1        |   at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
openrefine_1        |   at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
openrefine_1        |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
openrefine_1        |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
openrefine_1        |   at java.lang.Thread.run(Thread.java:748)
openrefine_1        | Caused by: org.wikidata.wdtk.wikibaseapi.apierrors.AssertUserFailedException: [assertuserfailed] You are no longer logged in, so the action could not be completed.
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:64)
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:417)
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:353)
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.BasicApiConnection.logout(BasicApiConnection.java:351)
openrefine_1        |   ... 25 more
```

**Comment by wetneb** [comment]
Opened an issue in WDTK about that: https://github.com/Wikidata/Wikidata-Toolkit/issues/561.
That being said I cannot reproduce the issue as is - I suspect we must wait for the cookies to expire by themselves while keeping OpenRefine open? Based on @Nikerabbit's comment above we could still ensure we catch IOExceptions there, until the bug is fixed upstream.

**Comment by wetneb** [comment]
I have requested a release of WDTK that we could upgrade to before releasing 3.5-beta: https://github.com/Wikidata/Wikidata-Toolkit/issues/576.
