### ISSUE TITLE
OpenRefine is starting after the installation, but a few errors extend the starting process drastic

### ISSUE THREAD

**Issue by squeezer44** [OpenRefine/OpenRefine#3339]
OpenRefine is starting after the installation, but a few errors extend the starting process drastic:
1. refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (983ms)
2. java.lang.IllegalStateException: Committed

- Local Environments
Open Refine Version 3.4.1 [437dc4d]
OS: Windows 10
JAVA:
	java version "1.8.0_171"
	Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
	Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

- Expected result
OpenRefine is starting without any errors in the console.

- Given result
OpenRefine i starting but with a few error during starting process.

```
19:23:04.907 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
19:23:04.939 [            refine_server] Initializing context: '/' from 'E:\openrefine-3.4.1\webapp' (32ms)
19:23:05.922 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment vari
ables (983ms)
19:23:05.925 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment vari
ables (3ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/E:/openrefine-3.4.1/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/Static
LoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/openrefine-3.4.1/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/Stati
cLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
19:23:06.126 [                   refine] Starting OpenRefine 3.4.1 [437dc4d]... (201ms)
19:23:06.131 [                   refine] initializing FileProjectManager with dir (5ms)
19:23:06.131 [                   refine] C:\Users\person\AppData\Roaming\OpenRefine (0ms)
19:23:14.567 [                   refine] POST /command/core/load-language (8436ms)
19:23:14.611 [                   refine] GET /command/core/get-preference (44ms)
19:23:14.646 [                   refine] POST /command/core/load-language (35ms)
19:23:14.661 [                   refine] POST /command/core/load-language (15ms)
19:23:14.700 [          org.mortbay.log] /images/favicon.png (39ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFilter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilter.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:210)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
19:23:15.050 [                   refine] POST /command/core/get-importing-configuration (350ms)
19:23:15.122 [                   refine] GET /command/core/get-all-project-tags (72ms)
19:23:15.146 [                   refine] GET /command/core/get-all-project-metadata (24ms)
19:23:15.182 [                   refine] GET /command/core/get-csrf-token (36ms)
19:23:15.296 [                   refine] GET /command/database/saved-connection (114ms)
19:23:15.378 [                   refine] GET /command/core/get-languages (82ms)
19:23:15.508 [                   refine] GET /command/core/get-version (130ms)
```

**Comment by wetneb** [comment]
Thanks for reporting! This is a duplicate of https://github.com/OpenRefine/OpenRefine/issues/416.

**Comment by squeezer44** [comment]
@wetneb 
Why do you think it's a duplicate of https://github.com/OpenRefine/OpenRefine/issues/416?
My issue is not related to a favicon.

**Comment by wetneb** [comment]
If I understand correctly, your issue is the fact that the following lines are present in the logs:
```
19:23:14.700 [          org.mortbay.log] /images/favicon.png (39ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFilter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilter.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:210)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

This is the same issue as #416.

**Comment by squeezer44** [comment]
@wetneb 
The problem, which prolonged the startup process massively starts before:
```19:23:05.922 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment vari
ables (983ms)
19:23:05.925 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment vari
ables (3ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/E:/openrefine-3.4.1/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/Static
LoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/openrefine-3.4.1/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/Stati
cLoggerBinder.class]
```

After startup Open Refine I can use it.
I just restarted Open Refine and the java.lang.IllegalStateException didn't occur.

**Comment by thadguidry** [comment]
@squeezer44  Please try to answer the following for us to understand better where the delay in starting OpenRefine is actually happening for you:
1. It looks like your starting OpenRefine via the `.exe` file and not `refine.bat` file?  Yes/No?
2. It looks like you are not changing the workspace directory folder, which is fine, so it is defaulting to `C:\Users\person\AppData\Roaming\OpenRefine` Yes/No?  https://github.com/OpenRefine/OpenRefine/wiki/FAQ#how-do-i-change-the-workspace-directory-that-i-want-refine-to-use-for-its-project-storage-
3. It seems like about an extra 8 secs to start after it found the data directory here and the time your browser started and then began loading our javascript source which called our `load-language`?  
```
19:23:06.131 [                   refine] C:\Users\person\AppData\Roaming\OpenRefine (0ms)
19:23:14.567 [                   refine] POST /command/core/load-language (8436ms)
```
Do you agree with a delay of 8 secs or is the time before OpenRefine shows it's home page in your browser much longer after this line appears on your console? 
```
19:23:15.508 [                   refine] GET /command/core/get-version (130ms)
```

**Comment by squeezer44** [comment]
@thadguidry

Thx for your answer :-)

Ad 1.) Yes - the path from where I start Open Refine is: E:\openrefine-3.4.1\openrefine.exe.

Ad 2.) Correct - I didn't change anything in openrefine.l4j.ini.

Ad 3.) Yes, that's the question I aim to be answered.

Ad 4.) I don't agree with 
`19:23:14.567 [                   refine] POST /command/core/load-language (8436ms)`

And I want to understand why POST /command/core/load-language is executed three times during on boot process.

```
19:23:14.567 [                   refine] POST /command/core/load-language (8436ms)
19:23:14.611 [                   refine] GET /command/core/get-preference (44ms)
19:23:14.646 [                   refine] POST /command/core/load-language (35ms)
19:23:14.661 [                   refine] POST /command/core/load-language (15ms)
```

**Comment by thadguidry** [comment]
@squeezer44 The reason we currently call `load-language` 3 times at startup is because each extension does an ajax call to the url `command/core/load-language` to ensure localization files are loaded.  This probably could be slightly improved where localization is tapped into just once on startup so that extensions didn't have to independently call the master `scripts/load-language.js` again.

Here's where it's all used across our various extensions: https://github.com/OpenRefine/OpenRefine/search?q=load-language

I think the wikidata and database extensions are loaded right upon startup?  But @wetneb could confirm for you or not.

but it's a minor quibble since after the server is indeed running (from Jetty and our Butterfly context) even with an empty cache the true load time is only 2.25 secs as shown:
![image](https://user-images.githubusercontent.com/986438/99886280-de87dc80-2c00-11eb-938e-051f5145b939.png)
