### ISSUE TITLE
Owner only consumer login issue

### ISSUE THREAD

**Issue by Nikerabbit** [OpenRefine/OpenRefine#3358]
### To Reproduce
1. Use the Wikidata extension, select a Wikibase instance
2. Then click Manage Wikibase account
3. Then use the "login with owner-only consumer" method and follow instructions per https://github.com/OpenRefine/OpenRefine/wiki/Wikidata-owner-only-consumer

### Current Results
After filling tokens and credentials, "Invalid credentials" response is shown.

In the logs:
```
openrefine_1        | 16:11:50.096 [                   refine] GET /command/core/get-csrf-token (48514ms)
openrefine_1        | 16:11:50.142 [                   refine] POST /command/wikidata/login (46ms)
openrefine_1        | 16:11:50.300 [       connection_manager] [assertuserfailed] You are no longer logged in, so the action could not be completed. (158ms)
openrefine_1        | org.wikidata.wdtk.wikibaseapi.apierrors.AssertUserFailedException: [assertuserfailed] You are no longer logged in, so the action could not be completed.
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:64)
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:417)
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:353)
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkCredentials(ApiConnection.java:204)
openrefine_1        |   at org.wikidata.wdtk.wikibaseapi.OAuthApiConnection.checkCredentials(OAuthApiConnection.java:161)
openrefine_1        |   at org.openrefine.wikidata.commands.ConnectionManager.login(ConnectionManager.java:124)
openrefine_1        |   at org.openrefine.wikidata.commands.LoginCommand.doPost(LoginCommand.java:160)
openrefine_1        |   at com.google.refine.RefineServlet.service(RefineServlet.java:187)
openrefine_1        |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
openrefine_1        |   at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
openrefine_1        |   at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
openrefine_1        |   at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
openrefine_1        |   at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
openrefine_1        |   at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
openrefine_1        |   at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
openrefine_1        |   at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
openrefine_1        |   at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
openrefine_1        |   at org.mortbay.jetty.Server.handle(Server.java:326)
openrefine_1        |   at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
openrefine_1        |   at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
openrefine_1        |   at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
openrefine_1        |   at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
openrefine_1        |   at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
openrefine_1        |   at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
openrefine_1        |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
openrefine_1        |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
openrefine_1        |   at java.lang.Thread.run(Thread.java:748)
```

In the httpd logs of the wiki I do see:
x.y.z.w - - [25/Nov/2020:17:11:50 +0100] "POST /w/api.php HTTP/1.1" 200 256 "-" "okhttp/4.9.0"

With further debugging I see the parameters are:
```{"assert":"user","format":"json","action":"query"}```

I am not sure how the login process is supposed to work, but I do not see any request which would pass the credentials. This is the only request that happens to the wiki when I press "Log in".

### Expected Behavior
Being able to log in, or a more specific error message.

### Versions
 - Operating System: Debian 10
 - Browser Version: Google Chrome 87.0.4280.66
 - JRE or JDK Version: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
 - OpenRefine: Version 3.5-beta [96789f9]
- MediaWiki: 1.35.0

**Comment by Nikerabbit** [comment]
Ok I think I found the cause: My setup was stripping the `Authorization` HTTP header so obviously it would fail.

**Comment by tfmorris** [comment]
Glad you got it sorted out. When you say "setup" are you talking about in intermediate proxy server or something else?

**Comment by Nikerabbit** [comment]
Just ProxyPassMatch on Apache to forward php requests to php-fpm.

I added `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` found from StackOverflow. Dunno if there is a better way.
