### ISSUE TITLE
NoClassDefFoundError while shutting down OpenRefine on Spark

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3463]
### To Reproduce
1. Start an import with a very large CSV file (500mb) with Create Project (after previewing successfully)
2. Then hit Ctrl-C in terminal while lots of Spark Tasks have started running as shown on Spark UI http://127.0.0.1:4040

### Current Results
```
11:29:09.319 [                   refine] POST /command/core/get-importing-job-status (2ms)
11:29:09.321 [                   refine] POST /command/core/get-importing-job-status (2ms)
11:29:09.322 [                   refine] POST /command/core/get-importing-job-status (1ms)
11:29:09.328 [                   refine] POST /command/core/get-importing-job-status (6ms)
11:29:09.330 [                   refine] POST /command/core/get-importing-job-status (2ms)
11:29:09.331 [                   refine] POST /command/core/get-importing-job-status (1ms)
11:29:09.333 [                   refine] POST /command/core/get-importing-job-status (2ms)
11:29:19.581 [..apache.spark.util.Utils] Suppressing exception in finally: org/spark_project/guava/collect/ImmutableCollection$EmptyImmutableCollection (10248ms)
java.lang.NoClassDefFoundError: org/spark_project/guava/collect/ImmutableCollection$EmptyImmutableCollection
        at org.apache.spark.storage.BlockInfoManager.$anonfun$releaseAllLocksForTask$1(BlockInfoManager.scala:347)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.storage.BlockInfoManager.releaseAllLocksForTask(BlockInfoManager.scala:347)
        at org.apache.spark.storage.BlockManager.releaseAllLocksForTask(BlockManager.scala:858)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:415)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1369)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ClassNotFoundException: org.spark_project.guava.collect.ImmutableCollection$EmptyImmutableCollection
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:543)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 10 more
11:29:19.589 [..spark.executor.Executor] Exception in task 0.0 in stage 64.0 (TID 108): null (8ms)
Terminate batch job (Y/N)? y

E:\GitHubRepos\OpenRefine>
```

### Expected Behavior
Don't know if this is a valid bug yet or not as I have been testing some basic data loading of large files against the `new-architecture` branch.

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8
 - OpenRefine: new-architecture branch

### Additional context
Since I set to specifically use
```
                .set("spark.dynamicAllocation.enabled", "true")
                .set("spark.shuffle.service.enabled", "true")
```
Then there might be additional SparkConf configuration needed for the `spark.cleaner.xxxx` properties and properly setting them.  Don't know for sure until I can test much more, but noting all this in this issue for now.

@wetneb  Hmm, I'm wondering if we need to perhaps make a special label "on Spark" for simplicity or do you want to use a milestone, either way, as I will likely be creating a lot more as I note a few issues with much more testing over the next weeks and as you and others also put more work into changes/fixes on the branch?  But I won't just blinding create new issues, I'm actually helping to develop and tweak and really isolate the issues.  Like one workaround I just needed to do for the `hadoop.tmp.dir` which doesn't get set correctly using  `.set("spark.hadoop.tmp.dir", "F:\\SPARK_TEMP\\hadoop_tmp")` and even though it's documented here: https://spark.apache.org/docs/latest/configuration.html#custom-hadoophive-configuration

**Comment by wetneb** [comment]
@thadguidry thanks! Yes feel free to create a label, it seems appropriate. Thanks a lot for your testing effort!

**Comment by wetneb** [comment]
It seems difficult to avoid such exceptions when closing down Spark, I would say they are normal. Unless there is a particular reason why they are a problem, beyond the noise in the logs, I would close this.

**Comment by thadguidry** [comment]
Ah you are thinking that Carl C is not a graceful shutdown command as we handle it but instead we handle it as a forced shutdown command?  I am ok with that but in the past OpenRefine would wait for long running operations to finish.  So I was expecting the same thing with our signals to Spark.

**Comment by wetneb** [comment]
In 3.x we wait for project saves, but not for long-running operations to finish. (I just checked this by running a URL fetching operation and sending Ctrl-C to the backend: it closes without waiting for the operation to finish). This should still be true in the new architecture.

**Comment by thadguidry** [comment]
Hmm, ok, then we do forced shutdowns. OK, then let's close this.
