### ISSUE TITLE
Not all test projects created during ui_testing are getting scraped

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3479]
We already have an afterEach hook that deletes all the projects created during the test but due to some bug, not all projects are being deleted.
### To Reproduce
1. Open Cypress application
2. Run a Spec
3. See a few outstanding projects remaining

### Current Results

Few projects remains after successful afterEach hook.
### Expected Behavior

All projects should be flushed out

**Comment by kushthedude** [comment]
This is the error being generated when cypress tries to delete some of those projects
```sh
22:43:38.157 [                   refine] POST /command/core/delete-project (93ms)
22:43:38.157 [                  command] Exception caught (0ms)
java.lang.NullPointerException
	at com.google.refine.commands.project.DeleteProjectCommand.doPost(DeleteProjectCommand.java:64)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by tfmorris** [comment]
https://github.com/OpenRefine/OpenRefine/blob/82b1cf0bfaf3c8ab57a12e0f2004bdeb71432383/main/src/com/google/refine/commands/project/DeleteProjectCommand.java#L63-L64

Looks like either the metadata or the metadata tags are `null`.

**Comment by tfmorris** [comment]
This change to the test fixture code in my pending PR might improve things:
https://github.com/OpenRefine/OpenRefine/blob/a2fd272e7a7f5cb349b04047e2ac7008761c360a/main/tests/cypress/cypress/support/commands.js#L369
but we should probably make the project delete code more resilient too
