### ISSUE TITLE
Error 500 STREAM on Excel export

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#351]
_Original author: jma...@gmail.com (March 18, 2011 02:05:21)_

<b>What steps will reproduce the problem?</b>
1. Open my project
2. Export -&gt; Excel

<b>What is the expected output? What do you see instead?</b>

HTTP ERROR 500

Problem accessing /command/core/export-rows/mydata.xls. Reason:

```
STREAM
```

Caused by:

java.lang.IllegalStateException: STREAM
    at org.mortbay.jetty.Response.getWriter(Response.java:616)
    at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.getWriter(GzipFilter.java:358)
    at com.google.refine.commands.Command.respond(Command.java:237)
    at com.google.refine.commands.Command.respondException(Command.java:305)
    at com.google.refine.commands.project.ExportRowsCommand.doPost(ExportRowsCommand.java:103)
    at com.google.refine.RefineServlet.service(RefineServlet.java:171)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Powered by Jetty://

<b>What version of Google Refine are you using?</b>

SVN TRUNK

<b>What operating system and browser are you using?</b>

Windows XP, Chrome 10

<b>Is this problem specific to the type of browser you're using or it happens</b>
<b>in all the browsers you tried?</b>

I can't even get to the Export Excel function on IE8, I get an Error on Page icon in the status bar.  I'm not an IE, don't know what that means.

<b>Please provide any additional information below.</b>

I have 1400 rows, and some large cell fields.  Can't up the data for you, sorry.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=351_

**Comment by tfmorris** [comment]
The fix above was flawed and wasn't correctly implemented until #867 -- although that also unnecessarily limited XLSX export to 256 columns which wasn't fixed until #2602.

**Comment by tfmorris** [comment]
This behavior was changed in #7459 targeted for release in 3.10 to throw an exception rather than (almost) silently dropping columns during the export.

Note that the limits for XLSX are much higher than for XLS, so that's the recommended Excel format where possible.

I'm switching the milestone from the original 2.1 to 3.10 so that we can track it for release noting purposes.
