### ISSUE TITLE
Can't import public Google Sheet without logging in

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3604]
Openrefine should import any publicly available google sheet without the need of g-API credentials
### To Reproduce
1. First, visit https://docs.google.com/spreadsheets/d/1_BY7R4cGZh1kPnwe89tFlMGdJSgEeemSHhyodNQGSBk
2. Then, import the above URL in openrefine through `Google Data` option
3. See an error

### Current Results

```sh
19:29:34.784 [                   refine] POST /command/core/importing-controller (46ms)
19:29:34.789 [          org.mortbay.log] /command/core/importing-controller (5ms)
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:125)
	at com.google.api.client.auth.oauth2.Credential$Builder.<init>(Credential.java:637)
	at com.google.refine.extension.gdata.GoogleAPIExtension.getSheetsService(GoogleAPIExtension.java:160)
	at com.google.refine.extension.gdata.GDataImportingController.getWorksheetEntriesForDoc(GDataImportingController.java:217)
	at com.google.refine.extension.gdata.GDataImportingController.doInitializeParserUI(GDataImportingController.java:197)
	at com.google.refine.extension.gdata.GDataImportingController.doPost(GDataImportingController.java:98)
	at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:68)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### Expected Behavior

Openrefine should be able to import the above sheet

### Datasets

https://docs.google.com/spreadsheets/d/1_BY7R4cGZh1kPnwe89tFlMGdJSgEeemSHhyodNQGSBk

**Comment by tfmorris** [comment]
I'm pretty sure this used to work, so this is a regression.
