### ISSUE TITLE
Openrefine unable to query sqlite3 database

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3605]
While importing data from sqlite3 database, openrefine always errors out on `Invalid or missing Query Info`
### To Reproduce
1. Connect the sqlite3 DB
2. Then, write this query `select NDB_NO from FOOD;`
3. Finally, try previewing and see the error

### Current Results

<img width="997" alt="Screenshot 2021-02-10 at 10 33 07 PM" src="https://user-images.githubusercontent.com/44091822/107544261-0e3af500-6bf0-11eb-816b-737c3e4de00c.png">

**Error Logs**
```sh
 refine] POST /command/core/importing-controller (13ms)
22:32:42.921 [          org.mortbay.log] /command/core/importing-controller (213ms)
java.lang.NullPointerException
	at com.google.refine.extension.database.DatabaseImportController.parsePreview(DatabaseImportController.java:270)
	at com.google.refine.extension.database.DatabaseImportController.doParsePreview(DatabaseImportController.java:200)
	at com.google.refine.extension.database.DatabaseImportController.doPost(DatabaseImportController.java:100)
	at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:68)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Expected Behavior

Openrefine should import the data

### Datasets

Here is the database https://drive.google.com/file/d/1xuGyEfp0MI0ddz8pBQ15f1AwcL_DGsM8/view?usp=sharing , try connecting to db and run the above query to see the output.

**Comment by kushthedude** [comment]
@wetneb Is this a valid issue or I am doing something wrong, as I have not used the DB import much in openrefine?

**Comment by tfmorris** [comment]
It's a bug. It got broken by this commit ded6ca07d1fb1f88f1b7f9bae7e1de6d3c22e311 - because we didn't have test coverage :)

**Comment by Gomaa** [comment]
Would you please assign me to this issue?

**Comment by wetneb** [comment]
Sure, thank you! I have sent you an invite to the organization so that you can assign issues yourself in the future.
