### ISSUE TITLE
XML importer silently fails if file is slightly invalid, it should be more accepting

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3638]
The XML importer rejects HTML files which are accepted by browsers. For instance, consider the example file supplied below, which starts with these lines:
```
<html>
<head><meta http-equiv=Content-Type content="text/html; charset=UTF-8">
<style type="text/css">
...
```

Our importer chokes on the `Content-Type` which is not enclosed in quotes. The following error is thrown in the console, without reporting anything in the UI:
```
20:14:34.965 [..e.importers.XmlImporter] Error generating parser UI initialization data for XML file (61ms)
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2,24]
Message: Des guillemets ouvrants sont attendus pour l'attribut "http-equiv" associé à un type d'élément "meta".
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at com.google.refine.importers.XmlImporter.descendElement(XmlImporter.java:166)
	at com.google.refine.importers.XmlImporter.descendElement(XmlImporter.java:171)
	at com.google.refine.importers.XmlImporter.createParserUIInitializationData(XmlImporter.java:97)
	at com.google.refine.importing.DefaultImportingController.doInitializeParserUI(DefaultImportingController.java:216)
	at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:91)
	at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:68)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Proposed solution

* Such an error should rather be reported to the user in the UI
* Ideally, the parser should be more accepting: in this concrete case I would like it to ignore this meta tag, which obviously does not contain any interesting data, and instead parse the `<body>` of the document, where the good stuff happens.

### Alternatives considered
One workaround is to edit the source file manually, but that's sad.

### Additional context
Example dataset: 
[serials.zip](https://github.com/OpenRefine/OpenRefine/files/5978336/serials.zip)

**Comment by tfmorris** [comment]
We are unlikely to be able to handle arbitrary HTML (which can be pretty messy) with our XML parser. If it's not valid XHTML, we'd need to switch to something like [JSoup](https://jsoup.org/)

**Comment by thadguidry** [comment]
For this use case, it might be possible to just tweak Xerces2 and maybe use XInclude or other optional features to disregard those non-conforming elements when found and continue parsing as `parse=xml`?  I sorta remember some of the Xerces options from back in the day, but I'm sure either one of you can dive into what is possible:
https://xerces.apache.org/xerces2-j/faq-xinclude.html
https://xerces.apache.org/xerces2-j/xni-config.html
