### ISSUE TITLE
OpenRefine stuck on “Working” when trying to reconcile with GBIF

### ISSUE THREAD

**Issue by kingf1sher** [OpenRefine/OpenRefine#3666]
Hello everyone. I am a new user of OpenRefine and I am having problems  (I think) with data reconciliation. I am using the ver. 3.4.1 and I am trying to fix my biodiversity data taxonomically using the GBIF service posted in this link: 

(https://iphylo.blogspot.com/2012/02/using-google-refine-and-taxonomic.html). 

However, it's been almost 10 hours and the display has not changed from "Working". My data set is quite huge at 9000+ rows. 

Any help will be super great. Thanks.

**Comment by wetneb** [comment]
The reconciliation service might be unreachable because of some proxy / firewall issues on your computer. Have you tried accessing the reconciliation service manually, for instance by pasting the endpoint URL in your browser?

**Comment by kingf1sher** [comment]
Hello wetneb. Thanks for responding. However, I decided to ditch the reconciliation feature and settled for a convenient alternative in Species Match (https://www.gbif.org/es/tools/species-lookup) that generates similar taxonomic data available in GBIF itself. 

Again, thank you very much!

**Comment by ostephens** [comment]
It looks like there are errors when you try to add those reconciliation service definitions them into OpenRefine. In the console I see:

```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'CURL': was expecting ('true', 'false' or 'null')
 at [Source: (String)"CURL error: 35 Unknown SSL protocol error in connection to www.gbif.org:443 CURL error: 35 Unknown SSL protocol error in connection to www.gbif.org:443 CURL error: 35 Unknown SSL protocol error in connection to www.gbif.org:443 CURL error: 35 Unknown SSL protocol error in connection to www.gbif.org:443 CURL error: 35 Unknown SSL protocol error in connection to www.gbif.org:443 CURL error: 35 Unknown SSL protocol error in connection to www.gbif.org:443 CURL error: 35 Unknown SSL protocol error in"[truncated 462 chars]; line: 1, column: 5]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4043)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2552)
	at com.google.refine.util.ParsingUtilities.evaluateJsonStringToObjectNode(ParsingUtilities.java:265)
	at com.google.refine.commands.recon.GuessTypesOfColumnCommand.guessTypes(GuessTypesOfColumnCommand.java:208)
	at com.google.refine.commands.recon.GuessTypesOfColumnCommand.doPost(GuessTypesOfColumnCommand.java:123)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
15:19:01.301 [                  command] Exception caught (2984ms)
java.lang.NullPointerException
	at com.google.refine.commands.recon.GuessTypesOfColumnCommand.guessTypes(GuessTypesOfColumnCommand.java:210)
	at com.google.refine.commands.recon.GuessTypesOfColumnCommand.doPost(GuessTypesOfColumnCommand.java:123)
	at com.google.refine.RefineServlet.service(RefineServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ostephens** [comment]
These reconciliation services were initially built in 2012 by Roderic Page and they are provided by having a reconciliation service independently written based on the APIs of the underlying services - and so rely on both the reconciliation service and the underlying APIs continuing to work. Looking at the comments on the blog post at https://iphylo.blogspot.com/2012/02/using-google-refine-and-taxonomic.html it looks like issues with some of the underlying services were reported 2 years ago and at the time Roderic said 

>(sigh) Yes, APIs tend to decay over time. uBio is on life support, not sure if the API still exists, GBIF has changed API, EOL has completely redesigned their web site, not sure about GNI (I don't use it much). Are these reconciliation services something that you use?

and

> Ok, I’ll take a look and see if I can revive some of these services.

But with no updates since then we might assume that they were not revived?

**Comment by tfmorris** [comment]
This sounds the same as #1828.

**Comment by kingf1sher** [comment]
Yes, I have read Roderic's comment and it's safe to assume that it is dead. Even global name resolver's API posted in this website (https://resolver.globalnames.org/api) as I have tried them.

**Comment by ostephens** [comment]
Closing as it seems clear this isn’t an OpenRefine issue but that the reconciliation service isn’t being maintained
