### ISSUE TITLE
Unable to start OpenRefine after updating it with master on MacOS

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3756]
### To Reproduce
1. First, do update your branch with current master
2. Then, do `./refine build`
3. Finally, try running openrefine by `./refine`

### Current Results

OpenRefine fails to start with error
```sh
18:19:45.894 [            refine_server] Starting autoreloading scanner...  (114ms)
18:19:46.043 [..pse.jetty.server.Server] jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_282-b08 (149ms)
18:19:46.538 [..dardDescriptorProcessor] NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet (495ms)
18:19:46.545 [..ty.webapp.WebAppContext] Failed startup of context o.e.j.w.WebAppContext@7ce6a65d{OpenRefine,/,file:///Volumes/T7/code/OpenRefine/main/webapp/,UNAVAILABLE}{/Volumes/T7/code/OpenRefine/main/webapp} (7ms)
java.lang.NoSuchMethodError: javax.servlet.ServletContext.createListener(Ljava/lang/Class;)Ljava/util/EventListener;
	at org.eclipse.jetty.servlet.ListenerHolder.doStart(ListenerHolder.java:92)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:350)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:822)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at com.google.refine.RefineServer.init(Refine.java:216)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)
18:19:46.581 [..erver.AbstractConnector] Started ServerConnector@16b4a017{HTTP/1.1,[http/1.1]}{127.0.0.1:3333} (36ms)
18:19:46.582 [..pse.jetty.server.Server] Started @1409ms (1ms)
java.lang.ClassNotFoundException: com.google.refine.RefineServlet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:64)
	at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:88)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:361)
	at com.google.refine.RefineServer.configure(Refine.java:314)
	at com.google.refine.RefineServer.init(Refine.java:222)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)
Exception in thread "main" javax.servlet.UnavailableException: Class loading error for holder refine@c847b26d==com.google.refine.RefineServlet,jsp=null,order=1,inst=false,async=false
	at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:95)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:361)
	at com.google.refine.RefineServer.configure(Refine.java:314)
	at com.google.refine.RefineServer.init(Refine.java:222)
	at com.google.refine.Refine.init(Refine.java:114)
	at com.google.refine.Refine.main(Refine.java:108)

```
### Expected Behavior

OpenRefine should start

**Comment by kushthedude** [comment]
cc : @wetneb

**Comment by wetneb** [comment]
@kushthedude thanks for reporting! Have you tried `./refine clean` before `./refine`?

**Comment by kushthedude** [comment]
Thanks it worked!
