### ISSUE TITLE
Add columns from reconciled column with SPARQL property not possible with NL API end point

### ISSUE THREAD

**Issue by VDK** [OpenRefine/OpenRefine#3852]
### To Reproduce
1. Reconcile against the Dutch api (https://tools.wmflabs.org/openrefine-wikidata/nl/api )
2. Add column from reconciled values...
3. Add property "Scommonswiki"

### Current Results
Error.
```
Exception caught (114ms)
java.io.IOException: Data extension query failed - code: 403 message: Forbidden
        at com.google.refine.model.recon.ReconciledDataExtensionJob.performQuery(ReconciledDataExtensionJob.java:238)
        at com.google.refine.model.recon.ReconciledDataExtensionJob.extend(ReconciledDataExtensionJob.java:190)
        at com.google.refine.commands.recon.PreviewExtendDataCommand.doPost(PreviewExtendDataCommand.java:140)
        at com.google.refine.RefineServlet.service(RefineServlet.java:187)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

### Expected Behavior
the Scommons link of the Q-item is added as a column

### Versions
 - Operating System:  Windows 10
 - Browser Version: Chrome 90
 - JRE or JDK Version: Java 8.0.29 
 - OpenRefine: 3.4.1

### Additional context
Does work with English API end point

**Comment by wetneb** [comment]
@VDK is this problem solved if you use the new API URL, https://wikidata.reconci.link/nl/api ?

**Comment by VDK** [comment]
Haven't had time to test yet

**Comment by VDK** [comment]
Didn't make a difference
