### ISSUE TITLE
One of my projects is now corrupt and cannot be started

### ISSUE THREAD

**Issue by VojtechDostal** [OpenRefine/OpenRefine#3893]
Sorry to be a trouble again. 
All my projects are OK but one - I cannot open a project with the following notice: "Failed to find project id #2540007166492 - may be corrupt". It appears normal in the project directory but maybe you can spot some problem... you can download the project at https://drive.google.com/file/d/1UmaA02NK75HrCAgvxk9JV2lr5ZqauYPu 

I get the following server logs:

20:28:50.084 [                   refine] POST /command/core/load-language (7863ms)
20:28:50.093 [                   refine] GET /command/core/get-preference (9ms)
20:28:50.093 [                   refine] GET /command/core/get-preference (0ms)
20:28:50.100 [                   refine] POST /command/core/load-language (7ms)
20:28:50.105 [                   refine] POST /command/core/load-language (5ms)
20:28:50.110 [                   refine] POST /command/core/load-language (5ms)
20:28:50.117 [                   refine] POST /command/core/load-language (7ms)
20:28:50.128 [                   refine] GET /command/core/get-project-metadata (11ms)
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at com.google.refine.io.ProjectUtilities.loadFromFile(ProjectUtilities.java:149)
        at com.google.refine.io.ProjectUtilities.load(ProjectUtilities.java:118)
        at com.google.refine.io.FileProjectManager.loadProject(FileProjectManager.java:253)
        at com.google.refine.ProjectManager.getProject(ProjectManager.java:516)
        at com.google.refine.commands.Command.getProject(Command.java:179)
        at com.google.refine.commands.project.GetProjectMetadataCommand.doGet(GetProjectMetadataCommand.java:53)
        at com.google.refine.RefineServlet.service(RefineServlet.java:180)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Any ideas would be very welcome - I did a lot of work on this project already :)

**Comment by VojtechDostal** [comment]
It seems that the data.zip file got corrupted (the data.txt file ends abruptly).

**Comment by thadguidry** [comment]
Closing as not reproducible.
