### ISSUE TITLE
Blank UI (only the logo is visible)

### ISSUE THREAD

**Issue by incansvl** [OpenRefine/OpenRefine#3913]
UI is blank except for the logo

### To Reproduce
1. Install OpenJDK 16.0.1 (Windows)
2. Install OpenRefine 3.4.1
3. Browser UI opens, but is visibly blank other than the OpenRefine logo (I can supply screenshots, but can't see the option to add them?)
4. The first installtion of OpenRefine in `C:\Program Files\OpenRefine\openrefine-3.4.1` creeated an empty folder in `C:\Users\[username]\AppData\Roaming\OpenRefine`.
5. On the posibility that OpenRefine might be one of the apps that chokes on pathnames containing spaces I installed a second copy in `C:\OpenRefine\openrefine-3.4.1`. This produces the same blank UI but did create a `workspace.json` file in the working folder.

### Current Results
1. Visually page is blank except for the logo
2. Looking at the page source the page appears to be valid but the left and right panels have almost no content. There are some links next to the logo, but these are empty elements (no text) so are rendering as 0-width items.

###Rendered Page Body
```
<body>
  <div id="header">
    <img alt="OpenRefine" src="images/logo-openrefine-550.png" height="29" />
    <span id="slogan"></span>
  </div>
  
  <div id="left-panel" class="main-layout-panel"><div id="left-panel-body">
    <ul id="action-area-tabs">
    </ul>
    
    <div id="project-links">
      <div id="logo-container">
        <img alt="OpenRefine" src="images/logo-gem-126.png" height="65" />
        <div id="openrefine-version"></div>
      </div>
      <ul>
        <li><a href="preferences" id="or-index-pref"></a></li>
        <li><a href="https://github.com/OpenRefine/OpenRefine/wiki/Documentation-For-Users" id="or-index-help"></a></li>
        <li><a href="about.html" id="or-index-about"></a></li>
      </ul>
    </div>
  </div></div> <!-- left-panel -->

  <div id="right-panel" class="main-layout-panel"><div id="right-panel-body">
  </div></div> <!-- right-panel -->
  
  <div id="no-project-message" class="message" style="display: none;">
    <span id="or-index-noProj"></span><br/>
    <span id="or-index-try"></span>
    <a href="https://github.com/OpenRefine/OpenRefine/wiki/Sample-Datasets" target="_blank" id="or-index-sample"></a>.
  </div>
</body>
```

### Expected Behavior
A usable web UI per the documentation

### Screenshots
(I'd love to, can't see that option?)

### Versions
OS: Windows 10 Pro 64 bit 19042.985
JDK: OpenJDK 16.0.1+9-24
OpenRefine: 3.4.1
Browser: Firefox 88.0.1 (also tried Edge 90.0.818.62, same result)

### Datasets
Blank (fresh installation)

### Additional context
##Console log
```
12:39:39.088 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
12:39:39.088 [            refine_server] Initializing context: '/' from 'C:\OpenRefine\openrefine-3.4.1\webapp' (0ms)
12:39:39.458 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (370ms)
12:39:39.458 [            refine_server] Failed to use jdatapath to detect user data path: resorting to environment variables (0ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/OpenRefine/openrefine-3.4.1/server/target/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/OpenRefine/openrefine-3.4.1/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
12:39:39.573 [                   refine] Starting OpenRefine 3.4.1 [437dc4d]... (115ms)
12:39:39.573 [                   refine] initializing FileProjectManager with dir (0ms)
12:39:39.573 [                   refine] C:\Users\coev\AppData\Roaming\OpenRefine (0ms)
12:39:39.573 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (0ms)
12:39:43.367 [          org.mortbay.log] /images/favicon.png (3794ms)
java.lang.IllegalStateException: Committed
        at org.mortbay.jetty.Response.resetBuffer(Response.java:1024)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:202)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.resetBuffer(GzipFilter.java:310)
        at org.mortbay.servlet.GzipFilter$GZIPResponseWrapper.sendError(GzipFilter.java:319)
        at edu.mit.simile.butterfly.Butterfly.error(Butterfly.java:1020)
        at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:528)
        at com.google.refine.RefineServlet.service(RefineServlet.java:210)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

The console error traceback for org.mortbay.log repeats slowly as the OpenRefine server is running, possibly linked to UI page refreshes.

**Comment by incansvl** [comment]
Looking through other issues this may be a duplicate of BugID #3869 (Java 16 compatibility).

Other issues mention similar symptoms (corrupted UI) but some of those are related to corrupted workspace folders, whreas this issue relates to a fresh install, and I have tried deleting the workspace folder and then re-running OpenRefine with no change in the behaviour.
