### ISSUE TITLE
Socket timeout too low for reconciliation operations

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3987]
Reconciliation can still fail silently for some batches even with reliable reconciliation services like OpenCorporate's.

## To reproduce

Try to reconcile the file provided in https://groups.google.com/g/openrefine/c/WHuCcfPPJbo

## Current results
https://groups.google.com/g/openrefine/c/WHuCcfPPJbo
You get some errors in the server logs like this:

```
{"q0":{"query":"Phoenix Software","type":"/organization/organization","type_strict":"should"},"q1":{"query":"Box.com (UK) Ltd","type":"/organization/organization","type_strict":"should"},"q2":{"query":"CEMEX UK Operations Ltd","type":"/organization/organization","type_strict":"should"},"q3":{"query":"LEX AUROLEASE LTD","type":"/organization/organization","type_strict":"should"},"q4":{"query":"JEDEX Ltd","type":"/organization/organization","type_strict":"should"},"q5":{"query":"BARTON ENGINEERING AND EXPORT","type":"/organization/organization","type_strict":"should"},"q6":{"query":"XOOMWORKS LIMITED","type":"/organization/organization","type_strict":"should"},"q7":{"query":"X-TECH (OPEN SYSTEMS) LTD","type":"/organization/organization","type_strict":"should"},"q8":{"query":"SODEXO LIMITED","type":"/organization/organization","type_strict":"should"},"q9":{"query":"Exergetic Ltd","type":"/organization/organization","type_strict":"should"}} (15688ms)
java.io.IOException: Failed to batch recon with load:
{"q0":{"query":"Phoenix Software","type":"/organization/organization","type_strict":"should"},"q1":{"query":"Box.com (UK) Ltd","type":"/organization/organization","type_strict":"should"},"q2":{"query":"CEMEX UK Operations Ltd","type":"/organization/organization","type_strict":"should"},"q3":{"query":"LEX AUROLEASE LTD","type":"/organization/organization","type_strict":"should"},"q4":{"query":"JEDEX Ltd","type":"/organization/organization","type_strict":"should"},"q5":{"query":"BARTON ENGINEERING AND EXPORT","type":"/organization/organization","type_strict":"should"},"q6":{"query":"XOOMWORKS LIMITED","type":"/organization/organization","type_strict":"should"},"q7":{"query":"X-TECH (OPEN SYSTEMS) LTD","type":"/organization/organization","type_strict":"should"},"q8":{"query":"SODEXO LIMITED","type":"/organization/organization","type_strict":"should"},"q9":{"query":"Exergetic Ltd","type":"/organization/organization","type_strict":"should"}}
	at com.google.refine.model.recon.StandardReconConfig.postQueries(StandardReconConfig.java:444)
	at com.google.refine.model.recon.StandardReconConfig.batchRecon(StandardReconConfig.java:467)
	at com.google.refine.operations.recon.ReconOperation$ReconProcess.run(ReconOperation.java:282)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1364)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:973)
	at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
	at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:241)
	at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:53)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:298)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:594)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:219)
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:107)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:182)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:165)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:179)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
	at com.google.refine.util.HttpClient.postNameValue(HttpClient.java:174)
	at com.google.refine.model.recon.StandardReconConfig.postQueries(StandardReconConfig.java:441)
	... 3 more
```

### Expected behavior

The column should reconcile normally. When there are errors they should be reported.

### Versions
 - Operating System: Linux
 - Browser Version: Firefox
 - JRE or JDK Version:  OpenJDK 11
 - OpenRefine: 3.5-beta1

**Comment by thadguidry** [comment]
Back in the day with older Apache HTTP Components it was 3 minute timeout default, I know because I read the source of it back then.  Then after 4.x they switched to a OS system default for socket connections (ex. on Mac it's 60 seconds) https://stackoverflow.com/questions/9734384/default-timeout-for-httpcomponent-client

**Comment by wetneb** [comment]
Yes so far we are using a 10 sec socket timeout which seems really too low, I will at least bump that to 60 sec.

**Comment by olea** [comment]
I think I'm having the same problem with Wikidata:

```
13:06:22.601 [    refine-standard-recon] Failed to batch recon with load:
{"q0":{"query":"175236","type":"Q473972","properties":[{"pid":"P4762","v":"175236"}],"type_strict":"should"},"q1":{"query":"175243","type":"Q473972","properties":[{"pid":"P4762","v":"175243"}],"type_strict":"should"},"q2":{"query":"195298","type":"Q473972","properties":[{"pid":"P4762","v":"195298"}],"type_strict":"should"},"q3":{"query":"151229","type":"Q473972","properties":[{"pid":"P4762","v":"151229"}],"type_strict":"should"},"q4":{"query":"555515435","type":"Q473972","properties":[{"pid":"P4762","v":"555515435"}],"type_strict":"should"},"q5":{"query":"175382","type":"Q473972","properties":[{"pid":"P4762","v":"175382"}],"type_strict":"should"},"q6":{"query":"175372","type":"Q473972","properties":[{"pid":"P4762","v":"175372"}],"type_strict":"should"},"q7":{"query":"175198","type":"Q473972","properties":[{"pid":"P4762","v":"175198"}],"type_strict":"should"},"q8":{"query":"555515449","type":"Q473972","properties":[{"pid":"P4762","v":"555515449"}],"type_strict":"should"},"q9":{"query":"555551123","type":"Q473972","properties":[{"pid":"P4762","v":"555551123"}],"type_strict":"should"}} (300337ms)
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457)
        at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1095)
        at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:72)
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:815)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.google.refine.model.recon.StandardReconConfig.batchRecon(StandardReconConfig.java:478)
        at com.google.refine.operations.recon.ReconOperation$ReconProcess.run(ReconOperation.java:282)
        at java.lang.Thread.run(Thread.java:748)
```
and
```
13:12:17.364 [    refine-standard-recon] Failed to batch recon with load:
{"q0":{"query":"151065","type":"Q473972","properties":[{"pid":"P4762","v":"151065"}],"limit":2,"type_strict"
:"should"},"q1":{"query":"195196","type":"Q473972","properties":[{"pid":"P4762","v":"195196"}],"limit":2,"ty
pe_strict":"should"},"q2":{"query":"195316","type":"Q473972","properties":[{"pid":"P4762","v":"195316"}],"li
mit":2,"type_strict":"should"},"q3":{"query":"195395","type":"Q473972","properties":[{"pid":"P4762","v":"195
395"}],"limit":2,"type_strict":"should"},"q4":{"query":"64519","type":"Q473972","properties":[{"pid":"P4762"
,"v":"64519"}],"limit":2,"type_strict":"should"},"q5":{"query":"555515311","type":"Q473972","properties":[{"
pid":"P4762","v":"555515311"}],"limit":2,"type_strict":"should"},"q6":{"query":"555641519","type":"Q473972",
"properties":[{"pid":"P4762","v":"555641519"}],"limit":2,"type_strict":"should"},"q7":{"query":"195180","typ
e":"Q473972","properties":[{"pid":"P4762","v":"195180"}],"limit":2,"type_strict":"should"},"q8":{"query":"55
5515387","type":"Q473972","properties":[{"pid":"P4762","v":"555515387"}],"limit":2,"type_strict":"should"},"
q9":{"query":"555515266","type":"Q473972","properties":[{"pid":"P4762","v":"555515266"}],"limit":2,"type_strict":"should"}} (153521ms)
org.apache.http.NoHttpResponseException: wikidata.reconci.link:443 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.google.refine.model.recon.StandardReconConfig.batchRecon(StandardReconConfig.java:478)
        at com.google.refine.operations.recon.ReconOperation$ReconProcess.run(ReconOperation.java:282)
        at java.lang.Thread.run(Thread.java:748)

```

The difference is the second case OR seems to resume the conciliation task but, with the first. sessions hangs indefinitely. In any case I got no error message.

I'm using wikidata.reconci.link service.
