### ISSUE TITLE
Invalid type id for preference.TopList while trying to run 4.0 branch

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4083]
After building and starting the 4.0 branch, I eventually see the following in the logs:

```
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.IllegalArgumentException: Invalid type id 'com.google.refine.preference.TopList' (for id type 'Id.class'): no such class found    
        at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:66)
        at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:48)
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:154)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:108)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
```

### Expected Behavior
OpenRefine does run and seem to still work, so not sure, since I pointed my data dir to an older workspace where in the past I used OpenRefine 3.3 (I think) and had 1 or 2 large projects and wanted to compare performance.  Here's the JSON from that folders' `workspace.json` file that does contain `com.google.refine.preference.TopList`:

```json
{"projectIDs":[1760211018969,1913213567861,2096851540888,1835459164359,1909321524635,2241781220050,2402698879266,2292487797744,1926719300548,2043551462658,1763374049601,2132559949881,1813359848574,1781022898740,1789964725313,1926019343626],"preferences":{"entries":{"reconciliation.standardServices":[{"preview":{"width":400,"url":"https://wdreconcile.toolforge.org/en/preview?id={{id}}","height":100},"extend":{"property_settings":[{"default":0,"name":"limit","label":"Limit","type":"number","help_text":"Maximum number of values to return per row (0 for no limit)"},{"default":"best","name":"rank","label":"Ranks","type":"select","choices":[{"name":"Any rank","value":"any"},{"name":"Only the best rank","value":"best"},{"name":"Preferred and normal ranks","value":"no_deprecated"}],"help_text":"Filter statements by rank"},{"default":"any","name":"references","label":"References","type":"select","choices":[{"name":"Any statement","value":"any"},{"name":"At least one reference","value":"referenced"},{"name":"At least one non-wiki reference","value":"no_wiki"}],"help_text":"Filter statements by their references"},{"default":false,"name":"count","label":"Return counts instead of values","type":"checkbox","help_text":"The number of values will be returned."}],"propose_properties":{"service_url":"https://wdreconcile.toolforge.org","service_path":"/en/propose_properties"}},"view":{"url":"https://www.wikidata.org/wiki/{{id}}"},"ui":{"handler":"ReconStandardServicePanel","access":"json"},"identifierSpace":"http://www.wikidata.org/entity/","name":"Wikidata (en)","suggest":{"property":{"service_url":"https://wdreconcile.toolforge.org","flyout_service_path":"/en/flyout/property?id=${id}","service_path":"/en/suggest/property"},"type":{"service_url":"https://wdreconcile.toolforge.org","flyout_service_path":"/en/flyout/type?id=${id}","service_path":"/en/suggest/type"},"entity":{"service_url":"https://wdreconcile.toolforge.org","flyout_service_path":"/en/flyout/entity?id=${id}","service_path":"/en/suggest/entity"}},"defaultTypes":[{"name":"entity","id":"Q35120"}],"url":"https://wdreconcile.toolforge.org/en/api","schemaSpace":"http://www.wikidata.org/prop/direct/"}],"scripting.starred-expressions":{"top":2147483647,"list":[],"class":"com.google.refine.preference.TopList"},"scripting.expressions":{"top":100,"list":["grel:value.parseHtml().select(\"[title]\")[0].htmlAttr(\"title\").smartSplit(\"Plants: \")[1]","grel:value.contains('<a title=')"],"class":"com.google.refine.preference.TopList"},"ui.cell.rowSplitDefaultSeparator":","}}}
```

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: OpenJDK 13
 - OpenRefine: 4.0 branch

**Comment by wetneb** [comment]
Fixed by using a different workspace for 4.0.
