### ISSUE TITLE
Importing large byte sizes per Row causes PLL task failed

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4084]
Importing using CSV,TSV importer with large sized content on each row throws an error after clicking CREATE button.
Preview of data seemed to be OK, although large amount of scrolling to see each unique Row (because of the large content size of each Row).

### Current Results
```
09:18:49.731 [                   refine] POST /command/core/get-importing-job-status (1099ms)
09:18:50.957 [                   refine] POST /command/core/get-importing-job-status (1226ms)
org.openrefine.model.local.PLL$PLLExecutionError: Execution of the PLL task failed: java.lang.IllegalArgumentException: Desired row size is 
smaller than the actual row size: impossible to pad with null cells
        at org.openrefine.model.local.PLL.runOnPartitions(PLL.java:674)
        at org.openrefine.model.local.PLL.runOnPartitions(PLL.java:634)
        at org.openrefine.model.local.PLL.saveAsTextFile(PLL.java:573)
        at org.openrefine.model.LocalGridState.saveToFile(LocalGridState.java:332)
        at org.openrefine.model.LocalGridState.saveToFile(LocalGridState.java:320)
        at org.openrefine.history.HistoryEntryManager.save(HistoryEntryManager.java:80)
        at org.openrefine.io.FileProjectManager.saveProject(FileProjectManager.java:258)
        at org.openrefine.ProjectManager.ensureProjectSaved(ProjectManager.java:229)
        at org.openrefine.io.FileProjectManager.reloadProjectFromWorkspace(FileProjectManager.java:514)
        at org.openrefine.importing.ImportingUtilities.createProjectSynchronously(ImportingUtilities.java:868)
        at org.openrefine.importing.ImportingUtilities.access$300(ImportingUtilities.java:104)
        at org.openrefine.importing.ImportingUtilities$5.run(ImportingUtilities.java:828)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Desired row size is smaller than the actual row size: impossible to pad with null cells
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
09:18:51.755 [                   refine] POST /command/core/get-importing-job-status (798ms)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:104)
        at org.openrefine.model.local.PLL.runOnPartitions(PLL.java:668)
        ... 11 more
Caused by: java.lang.IllegalArgumentException: Desired row size is smaller than the actual row size: impossible to pad with null cells      
        at org.openrefine.model.Row.padWithNull(Row.java:269)
        at org.openrefine.importers.LineBasedImporterBase$1.call(LineBasedImporterBase.java:179)
        at org.openrefine.model.LocalGridState.lambda$mapRows$27(LocalGridState.java:410)
        at org.openrefine.model.local.PairPLL.lambda$mapValues$0(PairPLL.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at com.google.common.collect.Streams$2.tryAdvance(Streams.java:432)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
        at org.openrefine.model.local.PLL.writePartition(PLL.java:604)
        at org.openrefine.model.local.PLL.lambda$saveAsTextFile$21(PLL.java:574)
        at org.openrefine.model.local.PLL.lambda$runOnPartitions$23(PLL.java:664)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

### Expected Behavior
large byte size rows (where each row itself has the content of a very large HTML or XML doc) should still be imported if there is enough memory and disk space to store ALL the rows, such as 32GB ram heap, etc and working against the full byte size of entire file being imported which is 1.5GB

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: OpenJDK 13
 - OpenRefine: 4.0 branch

**Comment by wetneb** [comment]
@thadguidry any chances you have a file at hand that reproduces this? Otherwise I think it is likely it was fixed by my recent optimizations.
