### ISSUE TITLE
Java exception while loading large 1.4GB CSV file from single .zip file

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#4096]
With a 385 MB .zip file where there is only 1 .zip file (original size is 1.4 GB) contained in it that has a CSV file with about 10 common fields of company data such as website, name, description, country, etc.

### To Reproduce
1. choose local .zip file
2. Then, checkmark selected 1 csv file from file selector interface in OpenRefine's extracted viewer
3. Finally, clicked Create
4. Spinner showed it was working, and then Error was shown in logs and display in browser continued the spinner.

### Current Results
```
16:29:07.349 [                   refine] POST /command/core/get-importing-job-status (1014ms)
16:29:08.350 [                   refine] POST /command/core/get-importing-job-status (1001ms)
16:30:18.265 [                   refine] GET /command/core/get-csrf-token (69915ms)
16:30:18.269 [                   refine] POST /command/core/importing-controller (4ms)
16:30:18.271 [..etty.server.HttpChannel] /command/core/importing-controller (2ms)
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.Integer; ([Ljava.lang.Object; and [Ljava.lang.Integer; are in module java.base of loader 'bootstrap')
        at org.openrefine.importing.DefaultImportingController.doUpdateFileSelection(DefaultImportingController.java:143)
        at org.openrefine.importing.DefaultImportingController.doPost(DefaultImportingController.java:91)
        at org.openrefine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:67)
        at org.openrefine.RefineServlet.service(RefineServlet.java:206)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1395)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:50)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
17:06:57.440 [..erver.AbstractConnector] Stopped ServerConnector@2d554825{HTTP/1.1,[http/1.1]}{127.0.0.1:3333} (2199169ms)
17:06:57.440 [..se.jetty.server.session] node0 Stopped scavenging (0ms)
17:06:57.613 [...handler.ContextHandler] Stopped o.e.j.w.WebAppContext@496bc455{OpenRefine,/,null,UNAVAILABLE}{E:\GitHubRepos\OpenRefine\main\webapp} (173ms)
Terminate batch job (Y/N)? y
```

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: OpenJDK 13
 - OpenRefine: 4.0 branch

**Comment by sfkeller** [comment]
Did you try to increase maximum heap size by adding -Xmx to the Java interpreter when starting?

**Comment by LC24** [comment]
Hello, I volunteer to work on this issue in November/December. For the project maintainer, please let me know if this is okay and if you want it fixed.

**Comment by wetneb** [comment]
Hi @LC24, that would be amazing! Did you notice that this is about the 4.0 branch? This new architecture is only partly documented for now, but I am available to answer any questions you might have.

**Comment by wetneb** [comment]
@thadguidry I assume this works fine now and we can close this?

**Comment by thadguidry** [comment]
Yes seems to work
