### ISSUE TITLE
Error 500 when trying to sign into Google Drive

### ISSUE THREAD

**Issue by bkazez** [OpenRefine/OpenRefine#4256]
Error 500 when trying to sign into Google Drive.

```
Problem accessing /extension/gdata/authorized. Reason:

Butterfly Error
Butterfly caught the following error while processing the request:
org.mozilla.javascript.WrappedException: Wrapped com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
  "error" : "invalid_grant",
  "error_description" : "Bad Request"
} (file:/Applications/OpenRefine.app/Contents/Resources/webapp/extensions/gdata/module/MOD-INF/controller.js#108)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1773)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:183)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
	at org.mozilla.javascript.gen.c12._c3(file:/Applications/OpenRefine.app/Contents/Resources/webapp/extensions/gdata/module/MOD-INF/controller.js:108)
	at org.mozilla.javascript.gen.c12.call(file:/Applications/OpenRefine.app/Contents/Resources/webapp/extensions/gdata/module/MOD-INF/controller.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:57)
	at org.mozilla.javascript.gen.c12._c2(file:/Applications/OpenRefine.app/Contents/Resources/webapp/extensions/gdata/module/MOD-INF/controller.js:107)
	at org.mozilla.javascript.gen.c12.call(file:/Applications/OpenRefine.app/Contents/Resources/webapp/extensions/gdata/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.gen.c12.call(file:/Applications/OpenRefine.app/Contents/Resources/webapp/extensions/gdata/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.process(ButterflyModuleImpl.java:399)
```

### To Reproduce
1. Create Project
2. Google Data
3. Authorized Documents
4. Sign In and Authorize

### Versions
 - Operating System: macOS 11.6 (20G165)
 - Browser Version: Firefox 93.0 (64-bit)
 - OpenRefine: 3.4.1

**Comment by wetneb** [comment]
Hi @bkazez, thanks a lot for reporting this!

Have you tried our 3.5-beta2 version? I would be very interested to know if you still have the same problem with this version.

**Comment by bkazez** [comment]
Works on 3.5-beta2. Thanks!

**Comment by wetneb** [comment]
Thanks a lot for the confirmation!

**Comment by wetneb** [comment]
Duplicate of #3991.
