### ISSUE TITLE
Wikimedia Commons batch edit stalls at 12%

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4577]
I am performing a (rather simple) batch edit on Wikimedia Commons, in which I want to edit nearly 2,000 files. The batch upload stalls at 12%. (I've retried 3 consecutive times; always stalls at the same point. Last edited file can be seen in [the batch's Edit Group](https://editgroups-commons.toolforge.org/b/OR/a9e247ec31d/)).

### To Reproduce

See below for the dataset/project.

### Expected Behavior

Batch upload should continue. If something is going wrong, it would be great if I would see some understandable and actionable feedback why this is happening.

### Screenshots
![image](https://user-images.githubusercontent.com/9881645/156050752-76da2223-91b8-44cb-889a-fa83c1b0c873.png)

Log (last lines - the 'We are editing too fast' warning has repeatedly appeared since starting the batch):

```
20:56:17.957 [..ting.EditBatchProcessor] Requesting documents (12041ms)
20:56:19.538 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 5473 milliseconds. (1581ms)
20:56:25.311 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 54 milliseconds. (5773ms)
20:56:30.596 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 3416 milliseconds. (5285ms)
20:56:34.488 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 2429 milliseconds. (3892ms)
20:56:49.745 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 6173 milliseconds. (15257ms)
20:57:02.484 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 5831 milliseconds. (12739ms)
20:57:17.914 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 5405 milliseconds. (15430ms)
20:57:40.803 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 1518 milliseconds. (22889ms)
20:57:50.428 [..ting.EditBatchProcessor] Requesting documents (9625ms)
Exception in thread "Thread-1" java.lang.IndexOutOfBoundsException: Index: 21
	at java.base/java.util.Collections$EmptyList.get(Unknown Source)
	at org.wikidata.wdtk.wikibaseapi.WbGetEntitiesAction.wbGetEntities(WbGetEntitiesAction.java:239)
	at org.wikidata.wdtk.wikibaseapi.WbGetEntitiesAction.wbGetEntities(WbGetEntitiesAction.java:108)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataFetcher.getEntityDocumentMap(WikibaseDataFetcher.java:404)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataFetcher.getEntityDocuments(WikibaseDataFetcher.java:187)
	at org.openrefine.wikidata.editing.EditBatchProcessor.prepareNewBatch(EditBatchProcessor.java:229)
	at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:146)
	at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Versions
 - Operating System: Mac OS X 10.13.6
 - Browser Version: Chrome 98.0.4758.109
 - OpenRefine: 3.6-SNAPSHOT [353d562] (the February 20, 2022 snapshot release)

### Datasets
The OpenRefine project is:

[public-art-Belgium.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/8156425/public-art-Belgium.openrefine.tar.gz)

**Comment by trnstlntk** [comment]
I have filtered the same project to only the sculptures located in the city of Ghent (77 records). When starting the batch editing process, it's not even starting yet (stuck at 0%). The log says:

```
21:21:57.227 [                   refine] GET /command/wikidata/login (6370ms)
21:21:57.268 [                   refine] GET /command/core/get-csrf-token (41ms)
21:21:57.280 [                   refine] POST /command/wikidata/preview-wikibase-schema (12ms)
21:21:57.298 [..kidata.qa.EditInspector] scrutinizer [FormatScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (18ms)
21:21:57.298 [..kidata.qa.EditInspector] scrutinizer [InverseConstraintScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.298 [..kidata.qa.EditInspector] scrutinizer [UnsourcedScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.298 [..kidata.qa.EditInspector] scrutinizer [RestrictedPositionScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.298 [..kidata.qa.EditInspector] scrutinizer [QualifierCompatibilityScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.298 [..kidata.qa.EditInspector] scrutinizer [SingleValueScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.298 [..kidata.qa.EditInspector] scrutinizer [QuantityScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.299 [..kidata.qa.EditInspector] scrutinizer [RestrictedValuesScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (1ms)
21:21:57.299 [..kidata.qa.EditInspector] scrutinizer [EntityTypeScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.299 [..kidata.qa.EditInspector] scrutinizer [MultiValueScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.299 [..kidata.qa.EditInspector] scrutinizer [DifferenceWithinRangeScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.299 [..kidata.qa.EditInspector] scrutinizer [ConflictsWithScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.299 [..kidata.qa.EditInspector] scrutinizer [ItemRequiresScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:21:57.299 [..kidata.qa.EditInspector] scrutinizer [UseAsQualifierScrutinizer] is skipped due to missing necessary constraint configurations in the Wikibase manifest (0ms)
21:22:19.268 [                   refine] GET /command/core/get-csrf-token (21969ms)
21:22:19.282 [                   refine] POST /command/wikidata/perform-wikibase-edits (14ms)
21:22:19.330 [..mWikibaseEditsOperation] Performing edits (48ms)
21:22:19.332 [..ting.EditBatchProcessor] Requesting documents (2ms)
Exception in thread "Thread-3" java.lang.IndexOutOfBoundsException: Index: 17
	at java.base/java.util.Collections$EmptyList.get(Unknown Source)
	at org.wikidata.wdtk.wikibaseapi.WbGetEntitiesAction.wbGetEntities(WbGetEntitiesAction.java:239)
	at org.wikidata.wdtk.wikibaseapi.WbGetEntitiesAction.wbGetEntities(WbGetEntitiesAction.java:108)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataFetcher.getEntityDocumentMap(WikibaseDataFetcher.java:404)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataFetcher.getEntityDocuments(WikibaseDataFetcher.java:187)
	at org.openrefine.wikidata.editing.EditBatchProcessor.prepareNewBatch(EditBatchProcessor.java:229)
	at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:146)
	at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by j-sal** [comment]
Verbose 'Issues' output with 3.6-SNAPSHOT [1d729f7]

![image](https://user-images.githubusercontent.com/26920450/156381115-594a4dcb-0246-41ff-bde7-c02a7dcdad52.png)

**Comment by j-sal** [comment]
Verbose 'Issues' output with version 3.6-SNAPSHOT [1d729f7]

![image](https://user-images.githubusercontent.com/26920450/156384644-3007853c-0371-4102-8e20-eaa35e533049.png)
