### ISSUE TITLE
NoSuchMethodError during Wikidata edits through upload

### ISSUE THREAD

**Issue by mbch331** [OpenRefine/OpenRefine#5126]
While trying to add directors to movies, OpenRefine gets stuck on 45%. In my console I see an error:
```
Exception in thread "Thread-5" java.lang.NoSuchMethodError: 'org.wikidata.wdtk.datamodel.interfaces.TermUpdate org.wikidata.wdtk.datamodel.helpers.Datamodel.makeTermUpdate(java.util.Collection, java.util.Collection)'
        at org.openrefine.wikidata.updates.ItemEdit.toEntityUpdate(ItemEdit.java:147)
        at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:173)
        at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:262)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by wetneb** [comment]
That's embarassing! May I ask you which version of OpenRefine you are running?

**Comment by mbch331** [comment]
OpenRefine 3.6.0 [ff7de4d]
Platform: Windows (Downloaded the version including java)

**Comment by mbch331** [comment]
Solved it by removing my webapp folder and copying it from the zipfile.
When upgrading I only copied the files from the zip to the OpenRefine folder, overwriting existing files, but not deleting existing files.

**Comment by wetneb** [comment]
Ah, thanks! Closing it then.
