### ISSUE TITLE
No automatic re-login

### ISSUE THREAD

**Issue by mbch331** [OpenRefine/OpenRefine#5268]
I was trying to upload data and it was stuck on 0% for longer than usual. Checked my console and it showed the cause: `MediaWiki error while fetching documents to edit [assertuserfailed]: You are no longer logged in, so the action could not be completed.`
I expect 1 of 2 things to happen:
1. I get an error message and the upload attempt stops
2. I am automatically logged in again with the previous entered username and password

Now I have to go to Extensions > Wikidata > Manage Wikidata account, log out and log in again.

**Comment by wetneb** [comment]
That makes sense!

I would go for 1., because in many cases we are not able to re-login without the user's cooperation. If you logged in via username/password then we do not store your password at all (only the cookies we get from the wiki out of the login process), so if you invalidate the cookies independently (for instance by logging out of the wiki with your browser, outside of OpenRefine) then we are completely logged out and we need you to type your password again.

Not storing the user's password is a good thing to keep the credentials secure, so I would like to preserve that.

**Comment by tfmorris** [comment]
I ran into this too and got the following messages logged:

```
18:28:58.052 [                   refine] POST /command/wikidata/perform-wikibase-edits (6ms)
18:28:58.114 [..mWikibaseEditsOperation] Performing edits (62ms)
18:28:58.114 [..ting.EditBatchProcessor] Requesting documents (0ms)
18:28:58.381 [..ting.EditBatchProcessor] MediaWiki error while fetching documents to edit [assertuserfailed]: You are no longer logged in, so the action could not be completed. (267ms)
18:28:58.383 [..ting.EditBatchProcessor] Retrying in 10000 ms (2ms)
18:29:08.452 [..ting.EditBatchProcessor] MediaWiki error while fetching documents to edit [assertuserfailed]: You are no longer logged in, so the action could not be completed. (10069ms)
18:29:08.452 [..ting.EditBatchProcessor] Retrying in 20000 ms (0ms)
18:29:28.513 [..ting.EditBatchProcessor] MediaWiki error while fetching documents to edit [assertuserfailed]: You are no longer logged in, so the action could not be completed. (20061ms)
18:29:28.513 [..ting.EditBatchProcessor] Retrying in 40000 ms (0ms)
18:30:08.584 [..ting.EditBatchProcessor] MediaWiki error while fetching documents to edit [assertuserfailed]: You are no longer logged in, so the action could not be completed. (40071ms)
18:30:08.584 [..ting.EditBatchProcessor] Retrying in 80000 ms (0ms)
18:31:28.662 [..ting.EditBatchProcessor] MediaWiki error while fetching documents to edit [assertuserfailed]: You are no longer logged in, so the action could not be completed. (80078ms)
18:31:28.714 [..ting.EditBatchProcessor] Giving up on fetching documents to edit. Skipping 16 remaining edits. (52ms)
Exception in thread "Thread-33" java.lang.NullPointerException
	at org.openrefine.wikibase.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:176)
	at org.openrefine.wikibase.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:262)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I'm not sure if the NPE is associated with the error not getting returned to the client. Also, the operation shouldn't be retried, because it's never going to succeed.

**Comment by JAnDud** [comment]
I am logged out, but Openrefine still says I'm logged in
<img width="1387" height="281" alt="Image" src="https://github.com/user-attachments/assets/7bad9385-43ab-4d17-9746-55a058776c1c" />
I am not able relogin, so i must  restart OR, then reload in browser.

**Comment by tfmorris** [comment]
@JAnDud Are you saying that the workaround mentioned by the original poster didn't work for you? 

> Now I have to go to Extensions > Wikidata > Manage Wikidata account, log out and log in again.

**Comment by JAnDud** [comment]
> [@JAnDud](https://github.com/JAnDud) Are you saying that the workaround mentioned by the original poster didn't work for you?
> > > Now I have to go to Extensions > Wikidata > Manage Wikidata account, log out and log in again.

The [Log out] button does nothing. I also tried to login in anonymous window with this account and then log out but nothing changed. 

The only way is to close OpenRefine both in console and browser, but this means I must set again all filters.

**Comment by tfmorris** [comment]
Thanks for the clarification. A technique you can use to preserve facets in this (and other) situations is to click on (or copy) the "Permalink" above the grid. That will encode all of your facets in the URL.
