### ISSUE TITLE
Successful unit test runs should have clean console output

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#5352]
Currently a successful test run with all tests green generates a lot of noisy console output which has the potential to mask real issues and also causes doubt newcomers.

A successful build/test run should have clean output that can be verified at a glance.

### To Reproduce

`./refine test`

### Current Results

Table of Contents (need a separate issue for each entry below)

- [ ] JaCoCo instrumentation error
- [ ] com.google.refine.importers.JsonImporterTests.canThrowError(JsonImporterTests.java:130)
- [ ] com.google.refine.importers.OdsImporterTests.showErrorDialogWhenWrongFormat(OdsImporterTests.java:147)
- [ ] ERROR refine-standard-recon - Failed to parse string as JSON: <!DOCTYPE html>
- [ ] java.lang.IllegalStateException: hello world
- [ ] (multiple places) ERROR FileProjectManager - Failed to load workspace from any attempted alternatives.
- [ ] com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'sdfasdfas'
- [ ] (multiple) [main] ERROR org.testng.reporters.jq.Main - /Users/tfmorris/git/OpenRefine/main/target/surefire-reports/jquery-3.6.0.min.js
java.nio.file.FileAlreadyExistsException: /Users/tfmorris/git/OpenRefine/main/target/surefire-reports/jquery-3.6.0.min.js

OpenRefine main

```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting org/marc4j/converter/impl/CodeTableGenerated with JaCoCo 0.8.8.202204050719/5dcf34a.
	at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:94)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:377)
	at org.marc4j.converter.impl.AnselToUnicode.loadGeneratedTable(AnselToUnicode.java:210)

```

```
19:40:24.245 [main] ERROR XmlImportUtilities - Exception from XML parse
com.google.refine.importers.tree.TreeReaderException: Unexpected character (';' (code 59)): was expecting comma to separate Object entries
	at com.google.refine.importers.JsonImporter$JSONTreeReader.next(JsonImporter.java:364) ~[classes/:?]
	at com.google.refine.importers.tree.XmlImportUtilities.processSubRecord(XmlImportUtilities.java:460) ~[classes/:?]
	at com.google.refine.importers.tree.XmlImportUtilities.processSubRecord(XmlImportUtilities.java:462) ~[classes/:?]
	at com.google.refine.importers.tree.XmlImportUtilities.processRecord(XmlImportUtilities.java:305) ~[classes/:?]
	at com.google.refine.importers.tree.XmlImportUtilities.findRecord(XmlImportUtilities.java:248) ~[classes/:?]
	at com.google.refine.importers.tree.XmlImportUtilities.importTreeData(XmlImportUtilities.java:155) ~[classes/:?]
	at com.google.refine.importers.tree.TreeImportingParserBase.parseOneFile(TreeImportingParserBase.java:241) ~[classes/:?]
	at com.google.refine.importers.JsonImporter.parseOneFile(JsonImporter.java:209) ~[classes/:?]
	at com.google.refine.importers.JsonImporterTests.canThrowError(JsonImporterTests.java:130) ~[test-classes/:?]

```

```
Oct 18, 2022 7:40:25 PM org.odftoolkit.odfdom.dom.OdfSchemaDocument getTables
SEVERE: null
java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Element.getChildNodes()" because "startElement" is null
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.fillTableList(OdfSchemaDocument.java:351)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getTables(OdfSchemaDocument.java:334)
	at org.odftoolkit.odfdom.doc.OdfDocument.getTableList(OdfDocument.java:714)
	at com.google.refine.importers.OdsImporter.parseOneFile(OdsImporter.java:143)
	at com.google.refine.importers.ImporterTest.parseOneFileAndReturnExceptions(ImporterTest.java:120)
	at com.google.refine.importers.OdsImporterTests.showErrorDialogWhenWrongFormat(OdsImporterTests.java:147)

```

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error</title>
  </head>
  <body>
    You have reached an error page.
  </body>
</html>"; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4703)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076)
	at com.google.refine.util.ParsingUtilities.evaluateJsonStringToObjectNode(ParsingUtilities.java:277)
	at com.google.refine.model.recon.StandardReconConfig.batchRecon(StandardReconConfig.java:457)

```

```
19:40:52.022 [Thread-7] ERROR refine-standard-recon - Failed to parse string as JSON: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error</title>
  </head>
  <body>
    You have reached an error page.
  </body>
</html>

```

```
java.lang.IllegalStateException: hello world
	at com.google.refine.commands.history.CancelProcessesCommand.doPost(CancelProcessesCommand.java:67)
	at com.google.refine.commands.util.CancelProcessesCommandTests.doPostCatchesExceptionFromWriter(CancelProcessesCommandTests.java:243)
```

```
javax.servlet.ServletException: Failed to find project id #1234 - may be corrupt
	at com.google.refine.commands.Command.getProject(Command.java:178)
	at com.google.refine.commands.history.CancelProcessesCommand.doPost(CancelProcessesCommand.java:62)
	at com.google.refine.commands.util.CancelProcessesCommandTests.doPostThrowsIfCommand_getProjectReturnsNull(CancelProcessesCommandTests.java:213)
```

```
19:40:54.853 [main] ERROR FileProjectManager - Failed to load workspace from any attempted alternatives.
19:40:54.928 [main] ERROR FileProjectManager - Failed to load workspace from any attempted alternatives.
19:40:54.941 [main] ERROR FileProjectManager - Failed to load workspace from any attempted alternatives.
19:40:54.948 [main] ERROR FileProjectManager - Failed to load workspace from any attempted alternatives.
19:40:54.956 [main] ERROR FileProjectManager - Failed to load workspace from any attempted alternatives.
```

```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'sdfasdfas': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"sdfasdfas"; line: 1, column: 10]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:745)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2961)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2002)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at com.google.refine.browsing.EngineConfig.reconstruct(EngineConfig.java:68)
	at com.google.refine.commands.Command.getEngineConfig(Command.java:124)

```

Wikidata extension
```
19:41:47.759 [main] ERROR org.openrefine.wikidata.utils.LanguageCodeStore - An error occurred when fetching language codes from: http://not.exist/w/api.php, fall back to the default language codes
java.net.UnknownHostException: not.exist: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[?:?]
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[?:?]
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.10.0.jar:?]
	at org.openrefine.wikidata.utils.LanguageCodeStore.fetchLangCodes(LanguageCodeStore.java:57) ~[classes/:?]

```

Error below happens for OpenRefine main and extensions jython, wikidata, database, gdata, & phonetic
```
19:42:13.048 [main] ERROR org.testng.reporters.jq.Main - /Users/tfmorris/git/OpenRefine/extensions/phonetic/target/surefire-reports/jquery-3.6.0.min.js
java.nio.file.FileAlreadyExistsException: /Users/tfmorris/git/OpenRefine/extensions/phonetic/target/surefire-reports/jquery-3.6.0.min.js
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:224) ~[?:?]
	at java.nio.file.Files.copy(Files.java:3144) ~[?:?]
	at org.testng.reporters.jq.Main.generateReport(Main.java:95) ~[testng-7.6.1.jar:7.6.1]
	at org.testng.TestNG.generateReports(TestNG.java:1134) ~[testng-7.6.1.jar:7.6.1]

```

**Comment by wetneb** [comment]
One approach would be to try add some settings in the test harness so that it's responsible for capturing the output during the test run and only outputting it if the test fails (which is something that can be done with JUnit at least). For TestNG I found this: https://groups.google.com/g/testng-users/c/7y4rGPZLtog
