### ISSUE TITLE
JaCoCo fails to instrument marc4j CodeTableGenerated class due to size

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#5353]
The test suite gets an error attempting to use JaCoCo to instrument `org/marc4j/converter/impl/CodeTableGenerated` due to its size.  This is non-fatal, but it should be explicitly excluded from instrumentation to reduce the console clutter.

```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting org/marc4j/converter/impl/CodeTableGenerated with JaCoCo 0.8.8.202204050719/5dcf34a.
	at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:94)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:377)
	at org.marc4j.converter.impl.AnselToUnicode.loadGeneratedTable(AnselToUnicode.java:210)

```

**Comment by rlachinov-wish** [comment]
Hi @tfmorris. What was the fix of this issue? I'm getting same one our project.
Would appreciate any help.

**Comment by Aks-4125** [comment]
I am facing this issue after creating new module on my Android app and ran the tests. hope this helps.
