### ISSUE TITLE
Engine reconstruction error message doesn't use logging

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#5354]
A test for error handling in the browsing engine reconstruction code is generating the stack trace below which is coming directly from Exception.printStackTrace with no logging controls.
```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'sdfasdfas': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"sdfasdfas"; line: 1, column: 10]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:745)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2961)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2002)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at com.google.refine.browsing.EngineConfig.reconstruct(EngineConfig.java:68)
	at com.google.refine.commands.Command.getEngineConfig(Command.java:124)
```

**Comment by tfmorris** [comment]
The `EngineConfig.reconstruct()` method was deprecated in #7033, effectively resolving this. The more general issue #5366 still needs work (which I've started).
