### ISSUE TITLE
java.lang.NullPointerException - Wikidata data uploads fail

### ISSUE THREAD

**Issue by mshd** [OpenRefine/OpenRefine#5382]
I'm trying to upload edits to Wikidata. However I cannot pinpoint the record that fails. My question is:
Is it possible to debug openrefine, to check why it fails?
Is it possible to skip failed uploads and continue with the next one?

### Current Results
```
Exception in thread "Thread-4" java.lang.NullPointerException
	at org.openrefine.wikidata.updates.ItemEdit.lambda$toEntityUpdate$0(ItemEdit.java:146)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openrefine.wikidata.updates.ItemEdit.toEntityUpdate(ItemEdit.java:146)
	at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:173)
	at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:262)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

### Versions
 - Operating System: Ubuntu
 - Browser Version: 
 - JRE or JDK Version: 
 - OpenRefine: Version 3.6.2

**Comment by wetneb** [comment]
Thanks for the repor would be curious to know if it also happening with the latest snapshot release.

**Comment by mshd** [comment]
[Clipboard.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/10703561/Clipboard.openrefine.tar.gz)

Please try to upload this statement to Wikidata.
