### ISSUE TITLE
OpenRefine upload to Wikidata stalls on deleted items

### ISSUE THREAD

**Issue by VojtechDostal** [OpenRefine/OpenRefine#5385]
When you have a list of items and reconcile them "as identifiers", it often happens that some of the items had already been deleted from Wikidata. But they still reconcile. 

However, when the Wikidata upload gets to this item, it gives the following error:
Exception in thread "Thread-12" java.lang.NullPointerException
And then it basically just stops the upload...

Steps to reproduce:
Reconcile Q56640589 as Wikidata identifier
try to import something

Expected behavior:
Skip the deleted item. Or do not reconcile it at all.

**Comment by mshd** [comment]
Can you try again on the lastest dev version, I think this has been fixed (at least for merged items)

**Comment by VojtechDostal** [comment]
@mshd So, I downloaded version 3.7-beta5 (2023-01-26)
and I pasted the following row from clipboard: Q56640589 	Q6581097
I was able to reconcile both columns with Wikidata.

I assembled the following Wikidata schema:

Column1: Property "Sex or gender" : Column2.

And after starting the import, I get the following errors in the console:

`09:42:10.206 [..mWikibaseEditsOperation] Performing edits (14ms)
09:42:10.207 [..ting.EditBatchProcessor] Requesting documents (1ms)
09:42:10.508 [..ting.EditBatchProcessor] Retrying in 10000 ms (301ms)
Exception in thread "Thread-3" java.lang.NullPointerException: Cannot invoke "org.wikidata.wdtk.datamodel.interfaces.StatementDocument.getEntityId()" because "currentDocument" is null
        at org.openrefine.wikibase.updates.LabeledStatementEntityEdit.toStatementUpdate(LabeledStatementEntityEdit.java:187)
        at org.openrefine.wikibase.updates.ItemEdit.toEntityUpdate(ItemEdit.java:159)
        at org.openrefine.wikibase.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:176)
        at org.openrefine.wikibase.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:262)
        at java.base/java.lang.Thread.run(Thread.java:1589)`

The import job stalls at "0% complete" unless I manually cancel it.

**Comment by LibrErli** [comment]
i ran into the same problem with Version 3.7.0 on Wikidata-QID: [Q79691922](https://www.wikidata.org/wiki/Q79691922)
The upload process stops at the deleted but reconciled record in the project, unless manual cancelling of the upload process. 
The OpenRefine Shell shows the following output:
```
Exception in thread "Thread-2" java.lang.NullPointerException
        at org.openrefine.wikibase.updates.LabeledStatementEntityEdit.toStatementUpdate(LabeledStatementEntityEdit.java:187)
        at org.openrefine.wikibase.updates.ItemEdit.toEntityUpdate(ItemEdit.java:159)
        at org.openrefine.wikibase.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:176)
        at org.openrefine.wikibase.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:262)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Version: 3.7.0
OS: Windows 10

**Comment by tamunro** [comment]
I had the same problem with Wikidata-QID [Q17068417](https://www.wikidata.org/wiki/Q17068417), using v.3.7.1 on MacOS. No error message appeared.

**Comment by tillgrallert** [comment]
Same here with [Q98847703](https://www.wikidata.org/wiki/Q98847703), using v.3.7.2 on the latest macOS. No error message.

**Comment by wetneb** [comment]
Thank you all for reporting this annoying issue.
For now I've made a change to just skip those edits, which should be released in 3.8. In the meantime you can use our [snapshot releases](https://github.com/OpenRefine/OpenRefine#snapshot-releases).

Better error reporting is coming in 4.0.
