### ISSUE TITLE
Let the user provide a column mapping when applying a JSON workflow

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5540]
Say you have a list of 4 operations forming a workflow that you want to reuse:
* capitalize the `country_code` column
* reconcile the `city` column using `country_code` as a reconciliation property
* add columns from reconciled values, fetching the `mayor` and the `population` columns
* remove all rows where `population` is less than 1000 inhabitants

Once you have done this workflow on a project, you can extract it as a JSON blob in the Undo/Redo tab, and reapply it on a new project.
The workflow JSON looks like this:

```json
[
  {
    "op": "core/text-transform",
    "engineConfig": {
      "facets": [],
      "mode": "row-based"
    },
    "columnName": "country_code",
    "expression": "value.toUppercase()",
    "onError": "keep-original",
    "repeat": false,
    "repeatCount": 10,
    "description": "Text transform on cells in column country_code using expression value.toUppercase()"
  },
  {
    "op": "core/recon",
    "engineConfig": {
      "facets": [],
      "mode": "row-based"
    },
    "columnName": "city",
    "config": {
      "mode": "standard-service",
      "service": "https://tools.wmflabs.org/openrefine-wikidata/en/api",
      "identifierSpace": "http://www.wikidata.org/entity/",
      "schemaSpace": "http://www.wikidata.org/prop/direct/",
      "type": {
        "id": "Q486972",
        "name": "human settlement"
      },
      "autoMatch": true,
      "columnDetails": [
        {
          "column": "country_code",
          "propertyName": "SPARQL: P17/P297",
          "propertyID": "P17/P297"
        }
      ],
      "limit": 0
    },
    "description": "Reconcile cells in column city to type Q486972"
  },
  {
    "op": "core/extend-reconciled-data",
    "engineConfig": {
      "facets": [],
      "mode": "row-based"
    },
    "baseColumnName": "city",
    "endpoint": "https://tools.wmflabs.org/openrefine-wikidata/en/api",
    "identifierSpace": "http://www.wikidata.org/entity/",
    "schemaSpace": "http://www.wikidata.org/prop/direct/",
    "extension": {
      "properties": [
        {
          "id": "P1082",
          "name": "population"
        },
        {
          "id": "P6",
          "name": "head of government"
        }
      ]
    },
    "columnInsertIndex": 1,
    "description": "Extend data at index 1 based on column city"
  },
  {
    "op": "core/row-removal",
    "engineConfig": {
      "facets": [
        {
          "type": "range",
          "name": "population",
          "expression": "value",
          "columnName": "population",
          "from": 0,
          "to": 1000,
          "selectNumeric": true,
          "selectNonNumeric": true,
          "selectBlank": false,
          "selectError": true
        }
      ],
      "mode": "row-based"
    },
    "description": "Remove rows"
  }
]
```

If the new project does not use the same column names, or if some columns are missing, this problem will not be reported to the user in a clear way.
Instead, the tool will try to apply all 4 operations in sequence, without stopping if columns are missing.

For instance, say we try to apply the workflow to a project with a column `country_code`, but the `city` column has been renamed into `administrative_area`.
This is what currently happens:
* the first operation, capitalizing the column `country_code`, will run successfully;
* the reconciliation operation is skipped as there is no such column to reconcile;
* the fetching operation is skipped, since `city` still does not exist;
* the `population` column does not exist, so the facet used to select the rows to delete has an error. So all rows are selected by default. So all rows in the new project are removed.

This is obviously extremely bad in terms of user experience. No data is actually lost since we can still roll back to a previous stage, but it is far from ideal.

Very elegantly, OpenRefine dumps some stack traces in the console as well:
```
java.lang.Exception: No column named city
	at com.google.refine.operations.recon.ReconOperation$ReconProcess.populateEntries(ReconOperation.java:205)
	at com.google.refine.operations.recon.ReconOperation$ReconProcess.run(ReconOperation.java:239)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-9" java.lang.NullPointerException
	at com.google.refine.operations.recon.ReconOperation$ReconProcess.run(ReconOperation.java:247)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: No column named city
	at com.google.refine.operations.recon.ExtendDataOperation$ExtendDataProcess.populateRowsWithMatches(ExtendDataOperation.java:161)
	at com.google.refine.operations.recon.ExtendDataOperation$ExtendDataProcess.run(ExtendDataOperation.java:244)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-10" java.lang.NullPointerException
	at com.google.refine.model.changes.DataExtensionChange.apply(DataExtensionChange.java:153)
	at com.google.refine.history.HistoryEntry.apply(HistoryEntry.java:148)
	at com.google.refine.history.History.addEntry(History.java:135)
	at com.google.refine.operations.recon.ExtendDataOperation$ExtendDataProcess.run(ExtendDataOperation.java:296)
	at java.lang.Thread.run(Thread.java:748)
```

## Proposed solution

Given a workflow, the tool needs to be able to determine if it applies to the current project, by infering from the workflow what the initial shape of the data should look like.

As a user, I expect that:
* the tool detects that this workflow depends on columns `city` and `country_code`
* I get the opportunity to map which columns in my new project correspond to these old columns (without actually renaming my columns to the old names)
* the tool translates the workflow to work on these new column names (`administrative_area` and `country_code`) automatically and applies the workflow.

**Comment by thadguidry** [comment]
Mapping is definitely a missing ingredient.  I actually mentioned this to David long ago, as Talend (and Ab Initio) actually have a pretty good mapping experience with drag and drop.  They show a single column table on LEFT side representing ProjectA and RIGHT side the columns for ProjectB, and then allow to click and grab from either side a particular column name and drag onto the other side's column name, basically a visual node relationship handler between 2 sets of column names.

In other programs it's experienced different with verticality dragdrop and no visual node threadsd.  Instead the LEFT|RIGHT column from both projects are shown, and you dragdrop vertically (reorder) either side to establish the horizontal line equivalency of each column name.  Which I find sometimes harder to use (there's more dragdrop movements typically needed), but others like it and not the spaghetti lines if a project has many columns to map in the above described interfaces.  And if a column is not needed to be mapped and excluded there's a disable button on each one.

**Comment by wetneb** [comment]
Thanks Thad! If you have any screenshots of such UIs I think it would be very helpful for inspiration.

**Comment by thadguidry** [comment]
![image](https://user-images.githubusercontent.com/986438/210522208-160793c3-a69e-44ff-b281-c71354f89c16.png)
![image](https://user-images.githubusercontent.com/986438/210522298-55caf034-0f28-4675-9133-eb09e068e4cd.png)

And a video:
https://youtu.be/tno_hrEM-ro?t=250

I could not quickly find any vertical examples but there are many and you can probably imagine that one since it's simple horizontal alignment of cell values between a left and right tabular listing of column names.  The good UI's typically use drag or drop to move the cells up or down, and the bad ones just use small arrows on each cell to click repeatedly and move up or down for each one. (Definitely not for those with carpal tunnel syndrome!!!)

There are actually more task or interactive examples however, which "might" be something to think about (especially given that data mapping might later involve not only `column name` but also other metadata or typing.   This article which has great research which I encourage you to read and demonstrates a bit of that https://www.arachuk.com/column-mapping

That task or interactive example, is simply a more guided approach to what Talend Open Studio offers with it's **tMap** function view and its upper left/right panels and lower Schema editor and Expression editor...all combined.

**Comment by thadguidry** [comment]
And in Apache Hop, it's easy to run it yourself locally and drop in a **Table Input** component or a **Mapping Input and Output** as well as perhaps the **Json Input** and their _Fields tab._

**Comment by Abbe98** [comment]
Something that would be useful in an automation scenario would be to specify multiply possible column names for a given operation. `"columnNames": ["city", "other_possible_city_column_name"]`, etc, one can kinda accomplish it already by just duplicating the operation or by setting up a bunch of renames but such solutions add a lot of complexity.

**Comment by thadguidry** [comment]
Also we might look to [Avro Records](https://avro.apache.org/docs/1.11.1/specification/) and Avro's schema evolution to provide mapping via Aliases.  For development, this is good and close enough to JSON Schema (it's Schema in JSON format, so good enough for me when it comes to developers being able to display, share, troubleshoot).  And I really appreciate Avro's encoding of records and [keeping values in the order they are declared](https://avro.apache.org/docs/1.11.1/specification/#complex-types-1) and [schema diffrences](https://avro.apache.org/docs/1.11.1/specification/#schema-resolution).

**Comment by wetneb** [comment]
> Something that would be useful in an automation scenario would be to specify multiply possible column names for a given operation. `"columnNames": ["city", "other_possible_city_column_name"]`, etc, one can kinda accomplish it already by just duplicating the operation or by setting up a bunch of renames but such solutions add a lot of complexity.

I am not too sure about this, because of the following problems:
* by introducing alternate column names in the JSON representation of an operation, you are introducing information that will not be input by the user when applying the operation via our UI. That means you are really encouraging users to edit the JSON representation themselves, which I do not think is a viable route for good UX.
* You could try to change the UI to expose this information, but it's going to be a quite awkward thing to expose: you would need to prompt the user for all possible sensible column names the operation could be applied to, should it be used in other datasets… And as a user applying an operation on my current dataset, I just do not care about this - I want to run this operation now, on the current dataset, and such a field would get in my way.
* for a lot of generic recipes (such as [sorting values within a record](https://stackoverflow.com/questions/75024320/openrefine-sorting-column-contents-within-a-record)) you clearly cannot list such possible column names: the recipe could legitimately be applied to any column.

@thadguidry there are a lot of pointers in your last comment but it's not clear to me how they tie in with the issue at hand. Let's try to keep the discussion as grounded as possible :)

**Comment by Abbe98** [comment]
@wetneb all valid concerns. My wish is (in a much broader sense than this issue) that integration developers would be as much users as those primary/only using the GUI, it's okay for some features only being available for one audience.

**Comment by thadguidry** [comment]
@wetneb I was just pointing out that fields can have more than 1 name/label.  And in Avro's case, even a record can have an optional alias.  Aliases is how Avro handles more than 1 name or label.  It's all column metadata in the end for us and users to keep track of things when column mapping (a from and to).  This was mentioned in one of our other issues before regarding column metadata and exporting/importing.  Like we have in https://schema.org/alternateName or DC: AlternativeTitle

**Comment by tfmorris** [comment]
Using the phrase "JSON workflow" to refer to OpenRefine's Undo history objects carries the connotation that the current implementation is a good basis upon which to build OpenRefine's data transformation DSL. 

Has this been validated in any way? 

Exposing that internal structure for external use was a quick and dirty hack over a decade ago, but I don't think it's one that necessarily needs to be propagated in perpetuity.

**Comment by wetneb** [comment]
@tfmorris I very much agree that the current situation is very far from what I think we should have. I am keen to change this in major ways, including ones that break compatibility with the existing syntax (let alone because we should not be exposing such JSON to the user, indeed).

I am currently going for an iterative approach based on the current system, because:
* I think it reduces the risk that I go in a completely wrong direction, and lets the community validate incremental progress;
* I think the underlying changes in the backend should be able to support a radically different system. For instance, one where the user would only manipulate a visual representation of a workflow (still with the ability to copy-paste it, save it to a file, edit operation parameters, and so on).

That being said, if you think I should rather follow a different approach, I am very keen to hear it. Perhaps the forum is more appropriate for this discussion, for instance this thread I opened today:
https://forum.openrefine.org/t/work-plan-for-the-reproductibility-improvements-project/332
