### ISSUE TITLE
4.0 Branch errors at runtime on MacOS

### ISSUE THREAD

**Issue by 5tigerjelly** [OpenRefine/OpenRefine#5846]
### To Reproduce
I have been having issues loading a 1.3GB file with 7M rows on the 3.7 release. After digging around, I saw 4.0 branch and the alpha package was created for this. The alpha package just hangs after clicking on create project. I tried to run the latest 4.0 commit on my local machine, but run into the issue below.

I am currently using MacOS

### Current Results
```
<h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">HTTP ERROR 500 javax.servlet.ServletException: refine==org.openrefine.RefineServlet@c847b26d{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///Users/5tigerjelly/Downloads/OpenRefine-4.0/main/webapp/WEB-INF/web.xml,STARTED}</h2>

URI: | /
-- | --
500
javax.servlet.ServletException: refine==org.openrefine.RefineServlet@c847b26d{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///Users/5tigerjelly/Downloads/OpenRefine-4.0/main/webapp/WEB-INF/web.xml,STARTED}
refine
javax.servlet.ServletException: refine==org.openrefine.RefineServlet@c847b26d{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///Users/5tigerjelly/Downloads/OpenRefine-4.0/main/webapp/WEB-INF/web.xml,STARTED}
java.lang.IllegalArgumentException: argument "src" is null

<h3 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Caused by:</h3><pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">javax.servlet.ServletException: refine==org.openrefine.RefineServlet@c847b26d{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///Users/5tigerjelly/Downloads/OpenRefine-4.0/main/webapp/WEB-INF/web.xml,STARTED}
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:650)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:486)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.openrefine.ValidateHostHandler.handle(ValidateHostHandler.java:91)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: argument "src" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4757)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3584)
	at org.openrefine.RefineServlet.init(RefineServlet.java:120)
	at javax.servlet.GenericServlet.init(GenericServlet.java:203)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:179)
	at org.openrefine.RefineServlet.init(RefineServlet.java:137)
	at org.eclipse.jetty.servlet.ServletHolder$Wrapper.init(ServletHolder.java:1345)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632)
	... 30 more</pre>
```

Refreshing I get
```
HTTP ERROR 404 Not Found

URI: | /
-- | --
404
Not Found
refine


```
### Versions
 - Operating System:  MacOS 13.3.1 (22E261)
 - Browser Version:  Safari, Chrome
 - JRE or JDK Version: 
 - OpenRefine:

**Comment by 5tigerjelly** [comment]
Actually I get the same error when I run `main` branch locally as well. Must be something that is configured wrong on my local machine.

**Comment by thadguidry** [comment]
@5tigerjelly The servlet says "src" is null.  That means things (files/folders) didn't get copied over to the right places.  Or the folders cannot be found because they are in the wrong place, or the system is looking in the wrong place.  I don't think it would be a permissions issue since that typically on Mac gives a different error message in the Jetty init for the Servlet and files needed by Butterfly.

To help troubleshoot, first ensure your Java environment is working well.  Open a terminal and ensure at least >11 version is output with the command `java --version`.

**Comment by wetneb** [comment]
@5tigerjelly thanks a lot for reporting!
To debug this further it could be helpful to have the entire build logs (the output of `./refine clean && ./refine build`).
If you want to test the 4.0 branch you can use the following prebuilt packages:
* [Linux](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=linux&p=tar.gz)
* [Mac OS](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=mac&p=dmg)
* [Windows (in you already have Java installed)](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=win&p=zip)
* [Windows (with Java included)](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=win-with-java&p=zip)

Curious to see what you think of it!

**Comment by 5tigerjelly** [comment]
After running `./refine clean && ./refine build` I was able to build locally, thank you @wetneb
