### ISSUE TITLE
Trying to load a 3.4.1 (or 3.6?) project using OpenRefine v3.8.1

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#6680]
I recently wanted to go back and run some updated operations on an older SEC data project I originally created in OpenRefine 3.4.1 (or it might have been 3.6, dunno) and this time using 3.8.1 for testing purposes.  

My doubt on one thing is that maybe the project itself is somehow slightly damaged and thus causing a weird parsing situation that is then causing Jackson to parse something very large that it shouldn't be in the error below?  or the project might be just fine, and instead something else is causing it to hit this limit now - like a new Jackson bug yet uncovered?

NOTE:  I did not have this issue with the project using 3.4.1 or 3.6 in 2022 when I created and used it then.

### Current Results
I received the following Java stacktrace when trying to open the file from Project Manager screen:

```
09:09:35.555 [        project_utilities] Failed to load from data file C:\Users\thadg\AppData\Roaming\OpenRefine\2360997867709.project / data.zip (334ms)
com.fasterxml.jackson.databind.JsonMappingException: String value length (20054016) exceeds the maximum allowed (20000000, from `StreamReadConstraints.getMaxStringLength()`) (through reference chain: com.google.refine.model.Row["cells"]->java.util.ArrayList[6]->com.google.refine.model.Cell["v"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1937)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:572)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:440)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:440)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
        at com.google.refine.model.Row.loadStreaming(Row.java:225)
        at com.google.refine.model.Row.load(Row.java:207)
        at com.google.refine.model.Project.loadFromReader(Project.java:233)
        at com.google.refine.model.Project.loadFromInputStream(Project.java:193)
        at com.google.refine.io.ProjectUtilities.loadFromFile(ProjectUtilities.java:142)
        at com.google.refine.io.ProjectUtilities.load(ProjectUtilities.java:121)
        at com.google.refine.io.FileProjectManager.loadProject(FileProjectManager.java:270)
        at com.google.refine.ProjectManager.getProject(ProjectManager.java:559)
        at com.google.refine.commands.Command.getProject(Command.java:180)
        at com.google.refine.commands.project.GetProjectMetadataCommand.doGet(GetProjectMetadataCommand.java:54)
        at com.google.refine.RefineServlet.service(RefineServlet.java:181)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at com.google.refine.ValidateHostHandler.handle(ValidateHostHandler.java:93)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Expected Behavior
Project loaded and showing data grid using 3.8.1 without showing infinity spinner and terminal showing Java stacktrace.

### Versions
 - Operating System: Windows 11 Pro 
 - Browser Version: Edge latest
 - JRE or JDK Version: whatever we now ship with 3.8.1 embedded Java
 - OpenRefine: 3.8.1

### Datasets

[2360997867709.project.zip](https://github.com/user-attachments/files/15879019/2360997867709.project.zip)

### Additional context
Since jackson-core [has a configuration option for `StreamReadConstraints` to control the maximum string length](https://github.com/FasterXML/jackson/discussions/217), and there is an internal limit of `20000000` (20M) then we can increase that? or better to add a new preference setting to read the jackson config option from with a default setting in the preference key/value like `jackson.getMaxStringLength = 100000000` (100M) ?

**Comment by tfmorris** [comment]
That project claims that it was written with OpenRefine 3.8-SNAPSHOT, but regardless, this problem was introduced by Jackson 2.15 (see https://github.com/FasterXML/jackson-core/issues/958) which we updated to (or through) in #6211 in Dec 2023, so OpenRefine 3.8 is the first release to exhibit the problem. 

Any old project with rows (cells?) above the 20MB limit will be unloadable in OpenRefine 3.8. Earlier releases of OpenRefine which use older versions of Jackson will not exhibit this problem.
