### ISSUE TITLE
Snapshot releases builds for MacOS intermittently fail

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6753]
Follow the steps to access our snapshot releases as documented here:
https://github.com/OpenRefine/OpenRefine?tab=readme-ov-file#snapshot-releases

There are only available artifacts for Windows and Linux, not MacOS.

The GitHub Actions workflow or our build process probably needs fixing so that the MacOS DMG file also appears there.

**Comment by wetneb** [comment]
This seems to be a transient issue, as the latest snapshot release does seem to have a DMG attached:
https://github.com/OpenRefine/OpenRefine/actions/runs/10200488541

**Comment by tfmorris** [comment]
An example of a run where the DMG wasn't produced is: https://github.com/OpenRefine/OpenRefine/actions/runs/10187510735

The mac_test_and_deploy job errored, but that didn't cause a build failure for some reason, which is a little worrying.
 https://github.com/OpenRefine/OpenRefine/actions/runs/10187510735/job/28181716478



```
[INFO] --- appbundle:1.2.0:bundle (default) @ packaging ---
[INFO] Creating and setting up the bundle directories
[INFO] Copying the native Java Application Stub
[INFO] Copying the Icon File
[INFO] Copying dependencies
[INFO] Copying 25 additional resources
[INFO] Copying 1 additional resource
[INFO] Copying the JRE Folder from : [/Users/runner/work/OpenRefine/OpenRefine/packaging/target/mac_jre/Contents/Home] to PlugIn folder: [/Users/runner/work/OpenRefine/OpenRefine/packaging/target/OpenRefine 3.9-SNAPSHOT/OpenRefine.app/Contents/PlugIns/JRE/Contents/Home/jre]
[INFO] Writing the Info.plist file
[INFO] Copying additional resources
[INFO] Copying 764 additional resources
[INFO] Making stub executable
[INFO] App Bundle generation finished
[INFO] 
[INFO] --- antrun:3.1.0:run (generate-dmg) @ packaging ---
[INFO] Executing tasks
[INFO]      [exec] OpenRefine 3.9-SNAPSHOT/OpenRefine.app/Contents/PlugIns/JRE/Contents/Home/jre/lib/jli/libjli.dylib: replacing existing signature
[INFO]      [exec] Codesigning JAR file: jna-5.13.0.jar
[INFO]      [exec] Codesigning file libjnidispatch.jnilib
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/database/module/MOD-INF/lib/tmp/com/sun/jna/darwin-aarch64/libjnidispatch.jnilib: replacing existing signature
[INFO]      [exec] Codesigning file libjnidispatch.jnilib
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/database/module/MOD-INF/lib/tmp/com/sun/jna/darwin-aarch64/libjnidispatch.jnilib: signed Mach-O thin (arm64) [libjnidispatch]
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/database/module/MOD-INF/lib/tmp/com/sun/jna/darwin-x86-64/libjnidispatch.jnilib: signed Mach-O thin (x86_64) [libjnidispatch]
[INFO]      [exec] Codesigning JAR file: sqlite-jdbc-3.46.0.0.jar
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/database/module/MOD-INF/lib/tmp/org/sqlite/native/Mac/aarch64/libsqlitejdbc.dylib: replacing existing signature
[INFO]      [exec] Codesigning file libsqlitejdbc.dylib
[INFO]      [exec] Codesigning file libsqlitejdbc.dylib
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/database/module/MOD-INF/lib/tmp/org/sqlite/native/Mac/aarch64/libsqlitejdbc.dylib: signed Mach-O thin (arm64) [libsqlitejdbc]
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/database/module/MOD-INF/lib/tmp/org/sqlite/native/Mac/x86_64/libsqlitejdbc.dylib: replacing existing signature
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/database/module/MOD-INF/lib/tmp/org/sqlite/native/Mac/x86_64/libsqlitejdbc.dylib: signed Mach-O thin (x86_64) [libsqlitejdbc]
[INFO]      [exec] Codesigning JAR file: jython-standalone-2.7.3.jar
[INFO]      [exec] Codesigning file libjansi.jnilib
[INFO]      [exec] Replacing OpenRefine.app/Contents/Resources/webapp/extensions/jython/module/MOD-INF/lib/tmp/jni/Darwin/libjffi-1.2.jnilib by /Users/runner/work/OpenRefine/OpenRefine/packaging/apple_certs/libjffi-1.2.jnilib
[INFO]      [exec] Codesigning file libjffi-1.2.jnilib
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/jython/module/MOD-INF/lib/tmp/META-INF/native/osx/libjansi.jnilib: signed Mach-O universal (i386 x86_64) [libjansi]
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/jython/module/MOD-INF/lib/tmp/jni/Darwin/libjffi-1.2.jnilib: replacing existing signature
[INFO]      [exec] OpenRefine.app/Contents/Resources/webapp/extensions/jython/module/MOD-INF/lib/tmp/jni/Darwin/libjffi-1.2.jnilib: signed Mach-O universal (x86_64 arm64) [libjffi-1]
[INFO]      [exec] hdiutil: couldn't eject "disk2" - Resource busy
[INFO]      [exec] hdiutil: couldn't eject "disk2" - Resource busy
[INFO]      [exec] hdiutil: couldn't eject "disk2" - Resource busy
[INFO]      [exec] hdiutil: couldn't eject "disk2" - Resource busy
[INFO]      [exec] hdiutil: couldn't eject "disk2" - Resource busy
[INFO]      [exec] hdiutil: couldn't eject "disk2" - Resource busy
[INFO]      [exec] Traceback (most recent call last):
[INFO]      [exec]   File "<frozen runpy>", line 198, in _run_module_as_main
[INFO]      [exec]   File "<frozen runpy>", line 88, in _run_code
[INFO]      [exec]   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/__main__.py", line 58, in <module>
[INFO]      [exec]     main()
[INFO]      [exec]   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/__main__.py", line 48, in main
[INFO]      [exec]     build_dmg(
[INFO]      [exec]   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/core.py", line 832, in build_dmg
[INFO]      [exec]     raise DMGError(callback, "Unable to detach device cleanly")
[INFO]      [exec] dmgbuild.core.DMGError: Unable to detach device cleanly
Error:       [exec] Result: 1
[INFO]      [exec] Error: The value '/Users/runner/work/OpenRefine/OpenRefine/packaging/target/openrefine-mac-3.9-SNAPSHOT.dmg' is invalid for '<file-path>': The file couldn’t be opened because it doesn’t exist.
[INFO]      [exec] Help:  <file-path>  Path to the archive
[INFO]      [exec] Usage: notarytool submit [<options>] <file-path>
[INFO]      [exec]   See 'notarytool submit --help' for more information.
Error:       [exec] Result: 64
[INFO]      [exec] File /Users/runner/work/OpenRefine/OpenRefine/packaging/target/openrefine-mac-3.9-SNAPSHOT.dmg does not exist. Error Domain=NSCocoaErrorDomain Code=260 "The file “openrefine-mac-3.9-SNAPSHOT.dmg” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/runner/work/OpenRefine/OpenRefine/packaging/target/openrefine-mac-3.9-SNAPSHOT.dmg, NSFilePath=/Users/runner/work/OpenRefine/OpenRefine/packaging/target/openrefine-mac-3.9-SNAPSHOT.dmg, NSUnderlyingError=0x600000848030 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Error:       [exec] Result: 66
```

**Comment by tfmorris** [comment]
It looks like the default for detach_retries if 5 (with one retry per second), so perhaps we could try increasing that.

https://github.com/dmgbuild/dmgbuild/blob/f16f2c39c54a6a60b7276f3e0b6f8b566bd864f0/src/dmgbuild/core.py#L155

It isn't clear to me whether this is a once in a blue moon thing or something that happens regularly, but it seems like doubling (or more) the retries would be pretty safe.

**Comment by tfmorris** [comment]
Unfortunately, the retry parameter isn't exposed via the CLI (I've asked for it to be [here](https://github.com/dmgbuild/dmgbuild/issues/128)), but it looks like the problem isn't terribly frequent, so we can probably live with just retrying the job for now.

It has happened 3 times in the last ~125 builds (500 build artefacts, which is how I did the analysis). In addition to the failure yesterday, the other two were:

last week
https://github.com/OpenRefine/OpenRefine/actions/runs/10106569274
https://github.com/OpenRefine/OpenRefine/actions/runs/10106569274/job/27948923295

2 weeks ago
https://github.com/OpenRefine/OpenRefine/actions/runs/10028079447
https://github.com/OpenRefine/OpenRefine/actions/runs/10028079447/job/27714559941

**Comment by tfmorris** [comment]
I patched the tool to expose the retry count to the command line
https://github.com/dmgbuild/dmgbuild/pull/129
It should be available in 1.6.2 and later.

**Comment by wetneb** [comment]
This is likely solved by the new version of dmgbuild, which we are already using (since we don't pin the dmgbuild version in the CI).
