### ISSUE TITLE
Four Cypress e2e tests are flaky

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6824]
The first one is flaky 100% of the time and the other three about 50%:

1. Test the history behavior, ensure expressions are stored
  project/grid/column/edit-column/add_columns_based_on_this_column.cy.js
I suspect perhaps this fails the first time through every time and succeeds on retry
1. Ensure new column is added based on previous column in Python
project/grid/column/edit-column/add_columns_based_on_this_column.cy.js
this has a 10 second timeout which is longer than normal, so perhaps it's known to run long?
1. Ensures the working of Start-Over Button
create-project/preview_project.cy.js
This might be a bug in the application code as claimed by Cypress which says the error is   "Cannot read properties of undefined (reading 'length')"
1. Test a valid Python expression 
project/grid/misc/expressions.cy.js

https://cloud.cypress.io/projects/s5du3k/analytics/flaky-tests/ddc1a2a4-3b8d-d38c-392f-261e0738a123-d77ab44a-cb4f-d134-2324-2a5d78ece7db?branches=%5B%7B%22label%22%3A%22master%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22master%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222024-08-23%22%2C%22endDate%22%3A%222024-08-30%22%7D&viewBy=TEST_CASE

### Current Results
Several tests are consistently flaky.

### Expected Behavior
No consistently flaky tests

**Comment by tfmorris** [comment]
The Cypress dashboard doesn't capture the Javascript stack trace from item 3 above. Here it is:

```
      at Refine.PreviewTable._render (http://127.0.0.1:3333/index-bundle.js:47981:28)
      at new Refine.PreviewTable (http://127.0.0.1:3333/index-bundle.js:47904:8)
      at <unknown> (http://127.0.0.1:3333/index-bundle.js:48284:9)
      at Object.success (http://127.0.0.1:3333/index-bundle.js:47066:13)
      at fire (http://127.0.0.1:3333/index-bundle.js:3225:31)
      at Object.fireWith [as resolveWith] (http://127.0.0.1:3333/index-bundle.js:3355:7)
      at done (http://127.0.0.1:3333/index-bundle.js:9629:14)
      at XMLHttpRequest.<anonymous> (http://127.0.0.1:3333/index-bundle.js:9890:9)
```

There are also several Java errors logged by the OpenRefine server around the same time, similar to the following:

```
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:721)
	at java.base/java.lang.Long.parseLong(Long.java:836)
	at com.google.refine.commands.row.GetRowsCommand.internalRespond(GetRowsCommand.java:197)
	at com.google.refine.commands.row.GetRowsCommand.doPost(GetRowsCommand.java:180)
```

From https://github.com/OpenRefine/OpenRefine/actions/runs/10574787447/job/29297087809

Looking at the test, my working theory is that the preview grid is still being rendered when the Start Over button is clicked and the project is deleted.
