### ISSUE TITLE
Flaky Cypress test - facet include/exclude

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6940]
This e2e test has failed multiple times recently (4 of last 64 runs). The text of the error message includes some suggestions for how to fix it. The tests include 100msec waits with warning comments, which seems suspicious.

```
  1) cypress/e2e/project/grid/column/facet/facets.cy.js
       Test include/exclude filters:
     CypressError: Timed out retrying after 4050ms: `cy.click()` failed because the page updated while this command was executing. Cypress tried to locate elements based on this query:

> <a.facet-choice-link.facet-choice-toggle>

We initially found matching element(s), but while waiting for them to become actionable, they disappeared from the page. Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You can typically solve this by breaking up a chain. For example, rewrite:

> `cy.get('button').click().click()`

to

> `cy.get('button').as('btn').click()`
> `cy.get('@btn').click()`

https://on.cypress.io/element-has-detached-from-dom
      at retryActionability (http://[127](https://github.com/OpenRefine/OpenRefine/actions/runs/11494591933/job/31992379921#step:9:128).0.0.1:3333/__cypress/runner/cypress_runner.js:113378:74)
      at tryCatcher (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:1807:23)
      at Promise.attempt.Promise.try (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:4315:29)
      at whenStable (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:143797:68)
      at <unknown> (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:143738:14)
      at tryCatcher (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:1701:18)
      at Promise._fulfill (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:1645:18)
      at <unknown> (http://127.0.0.1:3333/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at Context.eval (webpack://openrefine-cypress-test-suite/./cypress/e2e/project/grid/column/facet/facets.cy.js:21:15)
```

### To Reproduce

Unfortunately, since it fails less than 10% of the time, this may be difficult to reproduce, so a good first step might be to try and increase the failure rate by removing the waits.

### Current Results
Test is flaky

### Expected Behavior
Test passes reliably with no timing dependent behavior.

**Comment by tfmorris** [comment]
This has gotten too annoying to ignore.
