### ISSUE TITLE
Exception when sorting

### ISSUE THREAD

**Issue by ernestoalejo** [OpenRefine/OpenRefine#753]
This commit:
  https://github.com/OpenRefine/OpenRefine/commit/b91fc8a2b16f735109fefaadac52a7e4ccb9194e

Makes any kind of text sorting throw this exception:

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.text.CollationKey
    at com.google.refine.sorting.StringCriterion$1.compareKeys(StringCriterion.java:80)
    at com.google.refine.sorting.BaseSorter$ComparatorWrapper.compare(BaseSorter.java:101)
    at com.google.refine.sorting.BaseSorter.compare(BaseSorter.java:169)
    at com.google.refine.sorting.SortingRowVisitor$1.compare(SortingRowVisitor.java:85)
    at com.google.refine.sorting.SortingRowVisitor$1.compare(SortingRowVisitor.java:75)
    at java.util.Arrays.mergeSort(Arrays.java:1270)
    at java.util.Arrays.sort(Arrays.java:1210)
    at java.util.Collections.sort(Collections.java:157)
    at com.google.refine.sorting.SortingRowVisitor.end(SortingRowVisitor.java:75)
    at com.google.refine.browsing.util.ConjunctiveFilteredRows.accept(ConjunctiveFilteredRows.java:71)
    at com.google.refine.commands.row.GetRowsCommand.internalRespond(GetRowsCommand.java:146)
    at com.google.refine.commands.row.GetRowsCommand.doPost(GetRowsCommand.java:70)
    at com.google.refine.RefineServlet.service(RefineServlet.java:179)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)
```

**Comment by ultrageek** [comment]
I'm having this problem this very moment with a numeric column. It worked for three other numeric columns but not this one. This never happened to me before. All are numeric stock prices. I tried on a recent Mac Mini (OpenRefine installed around June or July 2016) and on a Dell Inspiron running Win 10 (OpenRefine installed around early April 2016). At this point, to meet client deadlines, I'm going to have to write code and start my analysis all over, but I can supply more details

**Comment by thadguidry** [comment]
@ultrageek please email our mailing list so we can help further.  https://groups.google.com/forum/#!forum/openrefine
