### ISSUE TITLE
Tests pass even when extension modules fail to load

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#754]
The Travis CI jobs are getting errors similar to the following from all extensions at startup time.  This indicates (at least) two problems: 1) lack of error reporting on extension loading (although it could be argued that that's a feature) and 2) lack of test coverage for the extensions.

The root cause is likely to be that the extensions are being compile for a later version of Java than the base system.

19:25:20.576 [         butterfly.module] Error initializing module pc-axis by script function init() (1354ms)
org.mozilla.javascript.EcmaError: TypeError: [JavaPackage com.google.refine.pcaxis.PCAxisImporter] is not a function, it is object. (file:/home/travis/build/tfmorris/OpenRefine/main/webapp/../../extensions/pc-axis/module/MOD-INF/controller.js#39)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3654)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3632)
    at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3660)
    at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3679)
    at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3734)
    at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3722)
    at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2324)
    at org.mozilla.javascript.gen.c2._c1(file:/home/travis/build/tfmorris/OpenRefine/main/webapp/../../extensions/pc-axis/module/MOD-INF/controller.js:39)
    at org.mozilla.javascript.gen.c2.call(file:/home/travis/build/tfmorris/OpenRefine/main/webapp/../../extensions/pc-axis/module/MOD-INF/controller.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
##

**Comment by wetneb** [comment]
It looks like this is solved (but the test coverage is still very low). I am proposing #1224 to help solve that.
