### ISSUE TITLE
Error creating project from a tar file

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#872]
Got this stack trace with OpenRefine 2.6 alpha while trying to create a project from a tar file containing a set of N-Triples files (http://echanges.bnf.fr/PIVOT/databnf_person_authors_n3.tar.gz?user=databnf&password=databnfr)

No error was displayed to the user - just an empty preview window.
```
11:41:37.891 [                   refine] POST /command/core/get-importing-job-status (999ms)
java.io.FileNotFoundException: C:\Users\tfmorris\AppData\Local\Temp\Jetty_127_0_0_1_3333_webapp____4ulpc9\import\1399736
675504\raw-data\F?*S (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:165)
        at com.google.refine.importing.ImportingUtilities.saveStreamToFile(ImportingUtilities.java:508)
        at com.google.refine.importing.ImportingUtilities.explodeArchive(ImportingUtilities.java:636)
        at com.google.refine.importing.ImportingUtilities.postProcessRetrievedFile(ImportingUtilities.java:536)
        at com.google.refine.importing.ImportingUtilities.retrieveContentFromPostRequest(ImportingUtilities.java:379)
        at com.google.refine.importing.ImportingUtilities.loadDataAndPrepareJob(ImportingUtilities.java:115)
        at com.google.refine.importing.DefaultImportingController.doLoadRawData(DefaultImportingController.java:119)
        at com.google.refine.importing.DefaultImportingController.doPost(DefaultImportingController.java:87)
        at com.google.refine.commands.importing.ImportingControllerCommand.doPost(ImportingControllerCommand.java:62)
        at com.google.refine.RefineServlet.service(RefineServlet.java:177)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
        at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
```

**Comment by tfmorris** [comment]
That site times out on connection currently, but I suspect the error (if it still exists) could be triggered by any URL containing a query string. It should be possible to create a mocked failing test to cover this case and confirm.

**Comment by wetneb** [comment]
I tested this with a similar URL (also with a `.tar.gz` and some query parameters) and it all works as expected in 4.0 (and likely in 3.6.2 as well).
