### ISSUE TITLE
Unable to upload data from URL

### ISSUE THREAD

**Issue by martavillegas** [OpenRefine/OpenRefine#910]
Hi,

I installed OpenRefine 2.6beta on a Windows7 machine. (I'm using Chrome)
When I try to create a project and upload data via URL nothing happens. The message on the screen says "Uploading data" and stops there.

This is what I get in the log window:
atus (1000ms)
09:35:06.305 [                   refine] POST /command/core/get-importing-job-st
atus (1001ms)
09:35:07.304 [                   refine] POST /command/core/get-importing-job-st
atus (999ms)
09:35:08.304 [                   refine] POST /command/core/get-importing-job-st
atus (1000ms)
09:35:09.304 [                   refine] POST /command/core/get-importing-job-st
atus (1000ms)
09:35:10.304 [                   refine] POST /command/core/get-importing-job-st
atus (1000ms)
09:35:11.305 [                   refine] POST /command/core/get-importing-job-st
atus (1001ms)
09:35:12.305 [                   refine] POST /command/core/get-importing-job-st
atus (1000ms)
09:35:13.132 [                   refine] POST /command/core/cancel-importing-job
 (827ms)
09:36:49.695 [..lient.DefaultHttpClient] I/O exception (java.net.SocketException
) caught when connecting to the target host: Malformed reply from SOCKS server (
96563ms)
09:36:49.695 [..lient.DefaultHttpClient] Retrying connect (0ms)
09:38:49.704 [..lient.DefaultHttpClient] I/O exception (java.net.SocketException
) caught when connecting to the target host: Malformed reply from SOCKS server (
120009ms)
09:38:49.704 [..lient.DefaultHttpClient] Retrying connect (0ms)
09:40:49.705 [..lient.DefaultHttpClient] I/O exception (java.net.SocketException
) caught when connecting to the target host: Malformed reply from SOCKS server (
120001ms)
09:40:49.705 [..lient.DefaultHttpClient] Retrying connect (0ms)

I previously installed version 2.5 and Upload data via URL worked fine. However, I had problems with reconciliation RDF using DBpedia, Europeana etc and I decided to install 2.6beta

Any help? Thanks

**Comment by eliohb** [comment]
have install red extension 1.1.0 and i put all the file in  ..\openrefine-3.1\webapp\extensions
and when i run the program the following error appear:
HTTP ERROR 500
Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later. (file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8._c_init_4(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js:89)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later.
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:213)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:302)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:286)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:938)
	at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:74)
	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
	at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 18 more
any advice

**Comment by wetneb** [comment]
@eliohb Again, this is not the appropriate place to report issues about the RDF extension. I am deleting your post as promised.
