### ISSUE TITLE
Out of memory crash with 7MB excel file

### ISSUE THREAD

**Issue by martingraham** [OpenRefine/OpenRefine#940]
Java memory allocation soars past whatever I can max at (-Xmx1200M on a 32-bit Windows 7 OS, Java 8u31) when trying to open what would seem to be (at first glance) a small .xslx file

In truth, it's a file of 10 worksheets, 35,000 rows by 4 columns each = 1.4 million cells in total, so it's well compressed in the .xslx format. However, if I convert it to the old .xls format, the file becomes bigger, but is now manageable by OpenRefine.

One thing I did notice is that the POI documentation (http://poi.apache.org/spreadsheet/quick-guide.html#FileInputStream) states that using InputStreams rather than Files can increase memory footprint, and poking about in the code (ExcelImporter.java) it seems to be using InputStreams rather than Files to open worksheets etc, I wonder if changing to use Files for excel .xslx data is possible and would make a difference?
##

**Comment by jackyq2015** [comment]
The problem may be from somewhere else.
I will try reproduce and check the exception stack and the memory usage.

**Comment by martingraham** [comment]
I had a poke about and it looks like the POI library is generating massive amounts of xml wrapper objects - up to 4million Xobj$AttrXobj and 3 million Xobj$ElementXObj. Then having a poke around in the .xslx file (by changing the suffix to .zip) I find an example of one of the sheets and lo and behold every cell value is nested in 'v' and 'c' elements, so 3 million elements is actually about right, and the attributes will be about right too, there are multiple of those per cell :-(

The problem isn't OpenRefine - the POI library is faithfully turning every attribute and element in the xml files in the xslx into a separate object instance - whether that's an efficient use of space is another question but for the POI authors not Refine. It also explains why switching to .xls works

Maybe the real wtf is xml :-(

**Comment by jackyq2015** [comment]
I upgraded the POI to updated version 3.11, still got:

10:22:56.705 [                   refine] POST /command/core/get-importing-job-status (990ms)
10:22:57.735 [                   refine] POST /command/core/get-importing-job-status (1030ms)
10:22:58.733 [                   refine] POST /command/core/get-importing-job-status (998ms)
10:23:00.690 [                   refine] POST /command/core/get-importing-job-status (1957ms)
10:23:05.534 [                   refine] POST /command/core/get-importing-job-status (4844ms)
Exception in thread "Thread-5" 10:23:05.899 [                   refine] POST /command/core/get-importing-job-status (365ms)
java.lang.OutOfMemoryError: GC overhead limit exceeded10:23:05.901 [                   refine] POST /command/core/get-importing-job-status (2ms)

10:23:05.904 [                   refine] POST /command/core/get-importing-job-status (3ms)
        at org.apache.xmlbeans.impl.values.NamespaceContext$NamespaceContextStack.<init>(NamespaceContext.java:78)10:23:05.908 [                   refine] POST /command/core/get-importing-job-status (4ms)

10:23:05.910 [                   refine] POST /command/core/get-importing-job-status (2ms)
        at org.apache.xmlbeans.impl.values.NamespaceContext$NamespaceContextStack.<init>(NamespaceContext.java:75)
        at org.apache.xmlbeans.impl.values.NamespaceContext.getNamespaceContextStack(NamespaceContext.java:98)
        at org.apache.xmlbeans.impl.values.NamespaceContext.push(NamespaceContext.java:106)
        at org.apache.xmlbeans.impl.values.XmlObjectBase.check_dated(XmlObjectBase.java:1273)
        at org.apache.xmlbeans.impl.values.XmlObjectBase.stringValue(XmlObjectBase.java:1484)
        at org.apache.xmlbeans.impl.values.XmlObjectBase.getStringValue(XmlObjectBase.java:1492)
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTRstImpl.getT(Unknown Source)
        at org.apache.poi.xssf.usermodel.XSSFRichTextString.getString(XSSFRichTextString.java:297)
        at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:247)
        at com.google.refine.importers.ExcelImporter.extractCell(ExcelImporter.java:252)
        at com.google.refine.importers.ExcelImporter.extractCell(ExcelImporter.java:262)
        at com.google.refine.importers.ExcelImporter$1.getNextRowOfCells(ExcelImporter.java:201)
        at com.google.refine.importers.TabularImportingParserBase.readTable(TabularImportingParserBase.java:132)
        at com.google.refine.importers.ExcelImporter.parseOneFile(ExcelImporter.java:210)
        at com.google.refine.importers.ImportingParserBase.parseOneFile(ImportingParserBase.java:112)
        at com.google.refine.importers.ImportingParserBase.parse(ImportingParserBase.java:83)
        at com.google.refine.importing.ImportingUtilities.createProjectSynchronously(ImportingUtilities.java:1017)
        at com.google.refine.importing.ImportingUtilities.access$200(ImportingUtilities.java:92)
        at com.google.refine.importing.ImportingUtilities$7.run(ImportingUtilities.java:992)
10:23:06.233 [                   refine] POST /command/core/get-importing-job-status (323ms)
10:23:07.234 [                   refine] POST /command/core/get-importing-job-status (1001ms)
Terminate batch job (Y/N)?
^C

I think the current XSSF parser is using the DOM instead of SAX. Another SAX implementation for excel import may fix the issue: 
http://poi.apache.org/spreadsheet/how-to.html#xssf_sax_api

**Comment by tfmorris** [comment]
@martingraham Thanks (belatedly) for all the analysis.  I'm glad you found a workaround.  

Any chance we could get a copy of the spreadsheet for debugging purposes?

**Comment by martingraham** [comment]
I've got an anonymised version now, where would you want it put?

**Comment by tfmorris** [comment]
@martingraham If you can attach the file here if you are comfortable with its level of anonymization or you can email it to me.

**Comment by martingraham** [comment]
aargh, it's not letting me attach anything that isn't a picture file...
